








app.views.BaseArtworkList=Ext.extend(Ext.Panel,{layout:"fit",listeners:{destroy:function(){if(this.CurrentAudio)NatsiaSetting.isAndroid?this.CurrentAudio.stop():this.CurrentAudio.pause(),this.CurrentAudio=null},activate:function(a){var b=new Ext.List({layout:"fit",store:app.stores.artworks,itemTpl:a.listTemplate,onItemDisclosure:function(a){Ext.dispatch({controller:app.controllers.artwork,action:"showArtworkDetail",id:a.getId(),animation:{type:"slide",direction:"left"}})},listeners:{itemtap:function(a,
b){if(!this.panel.isVirtual){var d=app.stores.artworks.getAt(b);Ext.dispatch({controller:app.controllers.artwork,action:"showArtworkDetail",id:d.getId(),animation:{type:"slide",direction:"left"}})}},afterrender:function(a){Ext.defer(function(){a.show()},300)},el:{click:function(a){var a=a.target.id.replace("soundIcon","").replace("sound-t-",""),b=Ext.getCmp("VirtualTourArtworkList");if(b.CurrentAudioId){var d=document.getElementById("soundIcon"+b.CurrentAudioId);d.className="_sound_off x-icon-mask sound-t";
NatsiaSetting.isAndroid?b.CurrentAudio.stop():b.CurrentAudio.pause()}if(!b.CurrentAudioId||b.CurrentAudioId!=a)d=document.getElementById("soundIcon"+a),d.className="_sound_on x-icon-mask sound-t",b.CurrentAudioId=a,b.CurrentAudio=NatsiaSetting.isAndroid?new Media("/android_asset/www/audio/A"+a+".m4a"):new Audio("audio/A"+a+".m4a"),b.CurrentAudio.play()},delegate:".sound-t"}}});b.panel=this;this.add(b);this.doLayout();b.setVisible(!1);(!a.ownerCt.isMainContainer||a.ownerCt.isActive)&&!NatsiaSetting.isAndroid&&
NatsiaSetting.checkScroller(b.scroller);NatsiaSetting.isAndroid||Ext.defer(function(){a.on("beforedeactivate",function(){NatsiaSetting.setArrow(!1)})},1E3)}},initComponent:function(){app.views.BaseArtworkList.superclass.initComponent.apply(this,arguments);this.addDocked([{xtype:"toolbar",title:"Artworks",items:[{ui:"back",text:"Categories",itemId:"back"}]}])}});
app.views.ArtworkDetails=Ext.extend(Ext.Panel,{scroll:"vertical",layout:"fit",padding:"0 0 50 0",fullscreen:!0,styleHtmlContent:!0,initComponent:function(){app.views.ArtworkDetails.superclass.initComponent.apply(this,arguments);this.addDocked([{xtype:"toolbar",title:"",items:[{text:"Back",ui:"back",itemId:"backDetail"},{xtype:"spacer"},{iconCls:"_favourites",cls:"favourite-button",iconMask:!0,ui:"plain",itemId:"favouriteIcon"},{iconCls:"_sound_off",cls:"sound-button",iconMask:!0,ui:"plain",id:"soundIcon"}]}]);
this.addDocked([{xtype:"logoPanel"}])},tpl:Ext.XTemplate.from("detail-template"),listeners:{deactivate:function(){NatsiaSetting.setArrow(!1);Ext.dispatch({controller:app.controllers.artwork,action:"stopSound"})},beforedestroy:function(a){Ext.get("soundIcon").removeListener("click",a.soundHandler)},activate:function(a){Ext.defer(function(){a.update(a.record.data);if(a.record.data.winner=="")document.getElementById("winner-badge").style.display="none";var b=a.el.down("#DetailMainImage");a.record.data.isLandscape?
b.dom.style.width="100%":b.dom.style.height="60%";a.doLayout();b.on("click",function(){a.record.data.hasVideo?showVideoCommon("v"+a.record.data.id):Ext.dispatch({controller:app.controllers.artwork,action:"showImageDetail",record:a.record,animation:{type:"slide",direction:"left"}})});b=Ext.get("soundIcon");b.record=a.record;b.on("click",a.soundHandler);b=a.scroller;b.containerBox.height!=b.size.height&&(NatsiaSetting.setArrow(!0),b.on("scroll",function(){NatsiaSetting.setArrow(!1)}))},600)}},setPlayButton:function(a){var b=
this.getDockedItems()[0].getComponent("soundIcon");a?b.setIconClass("_sound_on"):b.setIconClass("_sound_off")},setFavourite:function(a){var b=this.getDockedItems()[0].getComponent("favouriteIcon");a?b.addCls("orange-colour-icon"):b.removeCls("orange-colour-icon")},updateWithRecord:function(a){this.record=a;var b=this.getDockedItems()[0];b.getComponent("favouriteIcon").on("tap",function(){Ext.dispatch({controller:app.controllers.artwork,action:"toggleFavourites",record:a})});var c=a.get("hasSound"),
e=b.getComponent("soundIcon");e.setVisible(c);e.addListener({click:this.soundHandler,tap:this.soundHandler,element:"img"});b=b.getComponent("backDetail");b.on("tap",this.backHandler);NatsiaSetting.isAndroid&&(b.setVisible(!1),NatsiaSetting.setBackHander(this.backHandler))},soundHandler:function(){Ext.dispatch({controller:app.controllers.artwork,action:"togglePlaySound",recordId:this.record.data.id})},backHandler:function(){Ext.dispatch({controller:app.controllers.artwork,action:"backToList",animation:{type:"slide",
direction:"right"}})}});Ext.reg("artworkDetails",app.views.ArtworkDetails);
app.views.ArtworkListByCategory=Ext.extend(app.views.BaseArtworkList,{setCategoryname:function(a){this.getDockedItems()[0].setTitle(a)},initComponent:function(){this.listTemplate='<table><tr class="t-row"><td class="i-thmb"><img class="t-thmb" src="images/thumbs/IT{id}.jpg" /></td><td class="i-title"><h2>{author}</h2><p>{artName}</p></td></tr></table>';app.views.ArtworkListByCategory.superclass.initComponent.apply(this,arguments);this.addDocked([{xtype:"logoPanel"}]);var a=this.getDockedItems()[0].getComponent("back");
a.setText("Back");a.on("tap",this.backHandler);NatsiaSetting.isAndroid&&(a.setVisible(!1),NatsiaSetting.setBackHander(this.backHandler))},backHandler:function(){Ext.dispatch({controller:app.controllers.artwork,action:"showCategoryList",animation:{type:"slide",direction:"right"}})}});
app.views.CategoriesContainer=Ext.extend(Ext.Panel,{title:"Categories",iconCls:"_categories",layout:"card",initComponent:function(){Ext.apply(this,{items:[new app.views.CategoryList]});app.views.CategoriesContainer.superclass.initComponent.apply(this,arguments)},listeners:{cardswitch:function(a,b,c){c&&c.destroy()},activate:function(){app.controllers.artwork.mainPanel=this;var a=this.getActiveItem().items.items[0].scroller;NatsiaSetting.checkScroller(a)},beforeactivate:function(){this.isActive=!0},
deactivate:function(){this.isActive=!1;Ext.dispatch({controller:app.controllers.artwork,action:"showCategoryList",overrideMainPanel:this})}}});Ext.reg("categoriesContainer",app.views.CategoriesContainer);
app.views.CategoryList=Ext.extend(Ext.Panel,{layout:"fit",items:[{xtype:"list",store:app.stores.categories,itemTpl:'<table><tr class="t-row"><td class="cat-title"><h2>{label}</h2></td></tr></table>',onItemDisclosure:function(a){Ext.dispatch({controller:app.controllers.artwork,action:"showListFilterCategory",animation:{type:"slide",direction:"left"},id:a.getId()})},listeners:{itemtap:function(a,b){var c=app.stores.categories.getAt(b);Ext.dispatch({controller:app.controllers.artwork,action:"showListFilterCategory",
animation:{type:"slide",direction:"left"},id:c.getId()})}}}],listeners:{render:function(){this.getDockedItems();this.doComponentLayout()},activate:function(a){if(a.ownerCt.isActive&&!NatsiaSetting.isAndroid)a=a.items.items[0].scroller,a.containerBox.height!=a.size.height&&(NatsiaSetting.setArrow(!0),a.on("scroll",function(){NatsiaSetting.setArrow(!1)}))},beforedeactivate:function(){NatsiaSetting.isAndroid||NatsiaSetting.setArrow(!1)}},initComponent:function(){NatsiaSetting.isAndroid&&NatsiaSetting.resetBackHandler();
app.views.CategoryList.superclass.initComponent.apply(this,arguments);this.addDocked([{xtype:"toolbar",title:"Categories"}]);this.addDocked([{xtype:"logoPanel"}])}});Ext.reg("categoryList",app.views.CategoryList);
app.views.CommendedCategoryList=Ext.extend(Ext.Panel,{layout:"fit",items:[{xtype:"list",store:app.stores.commended,itemTpl:'<table><tr class="t-row"><td class="cat-title"><h2>{category}</h2></td></tr></table>',onItemDisclosure:function(a){Ext.dispatch({controller:app.controllers.artwork,action:"showArtworkDetail",id:a.get("winnerId"),animation:{type:"slide",direction:"left"}})},listeners:{itemtap:function(a,b){var c=app.stores.commended.getAt(b);Ext.dispatch({controller:app.controllers.artwork,action:"showArtworkDetail",
id:c.get("winnerId"),animation:{type:"slide",direction:"left"}})}}}],listeners:{render:function(){this.getDockedItems();this.doComponentLayout()},activate:function(a){app.controllers.artwork._backConfig={IsCommended:!0};if(!NatsiaSetting.isAndroid)a=a.items.items[0].scroller,a.containerBox.height!=a.size.height&&(NatsiaSetting.setArrow(!0),a.on("scroll",function(){NatsiaSetting.setArrow(!1)}))},beforedeactivate:function(){NatsiaSetting.isAndroid||NatsiaSetting.setArrow(!1)}},initComponent:function(){app.views.CommendedCategoryList.superclass.initComponent.apply(this,
arguments);this.addDocked([{xtype:"toolbar",title:"",items:[{ui:"back",text:"Winners",id:"backCommended"}]}]);this.addDocked([{xtype:"logoPanel"}]);var a=this.getDockedItems()[0].getComponent("backCommended");a.on("tap",this.backHandler);NatsiaSetting.isAndroid&&(a.setVisible(!1),NatsiaSetting.setBackHander(this.backHandler))},backHandler:function(){Ext.dispatch({controller:app.controllers.artwork,action:"showWinnersCategoryList",animation:{type:"slide",direction:"right"}})}});
Ext.reg("commendedCategoryList",app.views.CommendedCategoryList);
app.views.FavouritesArtworkList=Ext.extend(app.views.BaseArtworkList,{initComponent:function(){this.listTemplate='<table><tr class="t-row"><td class="t-number"><span class="sound-t-number" id="sound-t-{id}">{id}</span></td><td class="i-title"><h2>{author}</h2><p>{artName}</p></td></tr></table>';app.views.FavouritesArtworkList.superclass.initComponent.apply(this,arguments);this.addDocked([{xtype:"logoPanel"}]);var a=this.getDockedItems()[0];a.setTitle("Favourites");a.getComponent("back").setVisible(!1);
NatsiaSetting.isAndroid&&NatsiaSetting.resetBackHandler()}});
app.views.FavouritesContainer=Ext.extend(Ext.Panel,{title:"Favourites",iconCls:"_favourites",layout:"card",initComponent:function(){this.isMainContainer=!0;Ext.apply(this,{items:[new app.views.FavouritesArtworkList]});app.views.FavouritesContainer.superclass.initComponent.apply(this,arguments)},listeners:{cardswitch:function(a,b,c){c&&c.destroy()},beforeactivate:function(){this.isActive=!1;Ext.dispatch({controller:app.controllers.artwork,action:"filterFavourites"})},activate:function(){app.controllers.artwork.mainPanel=
this},beforedeactivate:function(){this.getActiveItem().setVisible(!1)},deactivate:function(){this.isActive=!1;this.setActiveItem(new app.views.FavouritesArtworkList)}}});Ext.reg("favouritesContainer",app.views.FavouritesContainer);
app.views.ImageDetails=Ext.extend(Ext.Panel,{scroll:"vertical",fullscreen:!0,tpl:'<img src="images/high/I{id}.jpg" />',initComponent:function(){app.views.ImageDetails.superclass.initComponent.apply(this,arguments);this.addDocked([{xtype:"toolbar",title:"",items:[{text:"Back",ui:"back",id:"backImageDetail"}]}])},listeners:{activate:function(a){Ext.defer(function(){a.update(a.record.data);a.doLayout()},800)}},updateWithRecord:function(a){this.record=a;NatsiaSetting.record=a;var b=this.getDockedItems()[0].getComponent("backImageDetail");
b.record=a;b.on("tap",this.backHandler);NatsiaSetting.isAndroid&&(b.setVisible(!1),NatsiaSetting.setBackHander(this.backHandler));a.data.isLandscape?(this.addCls("image-landscape-panel"),this.setScrollable("horizontal")):(this.addCls("image-portrait-panel"),this.setScrollable("vertical"))},backHandler:function(){Ext.dispatch({controller:app.controllers.artwork,action:"showArtworkDetail",id:NatsiaSetting.record.getId(),animation:{type:"slide",direction:"right"}});Ext.Anim.run(Ext.getCmp("pnlViewPort").getTabBar(),
"slide",{direction:"up",out:!1})}});Ext.reg("imageDetails",app.views.ImageDetails);app.views.LogoPanel=Ext.extend(Ext.Panel,{html:'<table id="logo-placement"><tr id="natsiaa-award-logo"><td><img id="logoPanelImage" src="images/award-logo.png" class="img-element" /></td></tr></table>'});Ext.reg("logoPanel",app.views.LogoPanel);
app.views.PeopleChoice=Ext.extend(Ext.Panel,{scroll:"vertical",layout:"fit",styleHtmlContent:!0,tpl:Ext.XTemplate.from("people-template"),listeners:{render:function(){this.getDockedItems();this.doComponentLayout()},activate:function(a){Ext.defer(function(){a.update(0)},300)}},initComponent:function(){app.views.PeopleChoice.superclass.initComponent.apply(this,arguments);this.addDocked([{xtype:"toolbar",title:"",items:[{ui:"back",text:"Winners",id:"backPeople"}]}]);this.addDocked([{xtype:"logoPanel"}]);
var a=this.getDockedItems()[0].getComponent("backPeople");a.on("tap",this.backHandler);NatsiaSetting.isAndroid&&(a.setVisible(!1),NatsiaSetting.setBackHander(this.backHandler))},backHandler:function(){Ext.dispatch({controller:app.controllers.artwork,action:"showWinnersCategoryList",animation:{type:"slide",direction:"right"}})}});Ext.reg("peopleChoice",app.views.PeopleChoice);
app.views.SearchArtworkList=Ext.extend(app.views.BaseArtworkList,{initComponent:function(){this.listTemplate='<table><tr class="t-row"><td class="t-number"><span class="sound-t-number" id="sound-t-{id}">{id}</span></td><td class="i-title"><h2>{author}</h2><p>{artName}</p></td></tr></table>';app.views.SearchArtworkList.superclass.initComponent.apply(this,arguments);this.addDocked([{xtype:"toolbar",items:[{xtype:"selectfield",name:"options",options:[{text:"All States",value:"All"},{text:"Northern Territory",
value:"NT"},{text:"Victoria",value:"VIC"},{text:"New South Wales",value:"NSW"},{text:"Western Australia",value:"WA"},{text:"Queensland",value:"QLD"},{text:"South Australia",value:"SA"},{text:"Australia Capital Territory",value:"ACT"},{text:"Tasmania",value:"TAS"}],listeners:{change:function(a){a.panel.applyFilter()}}}]}]);this.addDocked([{xtype:"toolbar",dock:"top",items:[{xtype:"searchfield",placeholder:"Search",name:"searchField",listeners:{keyup:function(a){a.panel.applyFilter()}}}]}]);var a=this.getDockedItems()[0];
a.setTitle("Search");a.getComponent("back").setVisible(!1);a=this.getDockedItems()[1];this.stateSelector=a.items.items[0];this.stateSelector.panel=this;a=this.getDockedItems()[2];this.searchTextBox=a.items.items[0];this.searchTextBox.panel=this;NatsiaSetting.isAndroid&&NatsiaSetting.resetBackHandler()},applyFilter:function(){var a=this.searchTextBox.getValue().toLowerCase(),b=this.stateSelector.getValue();a==""&&b=="All"?app.stores.artworks.clearFilter():app.stores.artworks.filterBy(function(c){if((a==
""||c.data.artName.toLowerCase().indexOf(a)>-1||c.data.author.toLowerCase().indexOf(a)>-1)&&(b=="All"||c.data.state==b))return!0;return!1})}});
app.views.SearchContainer=Ext.extend(Ext.Panel,{title:"Search",iconCls:"_search",layout:"card",initComponent:function(){this.isMainContainer=!0;app.views.SearchContainer.superclass.initComponent.apply(this,arguments);this.add(new app.views.SearchArtworkList)},listeners:{cardswitch:function(a,b,c){c&&c.destroy()},activate:function(){app.controllers.artwork.mainPanel=this;app.controllers.artwork._backConfig={IsSearch:!0};if(!NatsiaSetting.isAndroid){var a=this.getActiveItem().items.items[0].scroller;
NatsiaSetting.setArrow(!0);a.on("scroll",function(){NatsiaSetting.setArrow(!1)})}},beforeactivate:function(){app.stores.artworks.clearFilter();this.isActive=!0},beforedeactivate:function(){this.getActiveItem().setVisible(!1)},deactivate:function(){this.isActive=!1;this.setActiveItem(new app.views.SearchArtworkList)}}});Ext.reg("searchContainer",app.views.SearchContainer);
app.views.SplashScreen=Ext.extend(Ext.Panel,{iconCls:"toHide",layout:"card",styleHtmlContent:!0,data:{},tpl:Ext.XTemplate.from("splash-template"),initComponent:function(){app.views.SplashScreen.superclass.initComponent.apply(this,arguments)},listeners:{cardswitch:function(a,b,c){c&&c.destroy()},activate:function(){},deactivate:function(){NatsiaSetting.canRotate=!0}}});Ext.reg("splashScreen",app.views.SplashScreen);
app.views.Viewport=Ext.extend(Ext.TabPanel,{id:"pnlViewPort",cls:"tempViewPort",fullscreen:!0,cardSwitchAnimation:"fade",layout:"fit",tabBar:{dock:"bottom",layout:{pack:"center"}},items:[{xtype:"splashScreen"},{xtype:"categoriesContainer"},{xtype:"virtualTourContainer"},{xtype:"searchContainer"},{xtype:"favouritesContainer"},{xtype:"winnersContainer"}],listeners:{beforecardswitch:function(){},orientationchange:function(){},render:function(){this.getTabBar().remove(this.getTabBar().items.items[0]);
this.getTabBar().remove(this.getTabBar().items.items[5]);this.getTabBar().remove(this.getTabBar().items.items[5])}},initComponent:function(){app.views.Viewport.superclass.initComponent.apply(this,arguments);this.add(new app.views.VirtualTour,new app.views.ClosePanel)}});
app.views.VirtualTour=Ext.extend(Ext.Video,{xtype:"video",id:"virtualTourVideo",width:474,height:264,initComponent:function(){app.views.VirtualTour.superclass.initComponent.apply(this,arguments)},listeners:{show:function(){Ext.Anim.run(Ext.getCmp("pnlViewPort").getTabBar(),"slide",{direction:"down",autoClear:!1});Ext.getCmp("closePanel").show();if(document.getElementById("logoPanelImage"))document.getElementById("logoPanelImage").style.display="none"},hide:function(){Ext.Anim.run(Ext.getCmp("pnlViewPort").getTabBar(),
"slide",{direction:"up",out:!1});Ext.getCmp("closePanel").hide();if(document.getElementById("logoPanelImage"))document.getElementById("logoPanelImage").style.display="inline"},activate:function(){document.getElementsByTagName("video")[0].addEventListener("webkitendfullscreen",function(){Ext.getCmp("virtualTourVideo").hide()})}}});
function showVideoCommon(a){if(NatsiaSetting.isAndroid)showVideo(a);else{var b=document.getElementsByTagName("video")[0];b.src="videos/"+a+".mp4";b.load();Ext.getCmp("virtualTourVideo").show()}}app.views.ClosePanel=Ext.extend(Ext.Panel,{id:"closePanel",initComponent:function(){app.views.ClosePanel.superclass.initComponent.apply(this,arguments);var a=new Ext.Button({ui:"round",text:"Back",id:"closeButtonVideo"});a.on("tap",function(){Ext.getCmp("virtualTourVideo").hide()});this.add(a)}});
app.views.VirtualTourArtworkList=Ext.extend(app.views.BaseArtworkList,{id:"VirtualTourArtworkList",initComponent:function(){this.listTemplate='<table><tr class="t-row"><td class="t-number"><div class="numbers"><div class="sound-t" id="sound-t-{id}">{id}</div><div class="soundIcon x-button x-button-plain"><img src="data:image/gif;base64,R0lGODlhAQABAID/AMDAwAAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" class="_sound_off sound-t x-icon-mask" id="soundIcon{id}"></div></div></td><td class="i-title"><h2>{author}</h2><p>{artName}</p></td></tr></table>';
app.views.VirtualTourArtworkList.superclass.initComponent.apply(this,arguments);this.addDocked([{xtype:"logoPanel"}]);var a=this.getDockedItems()[0];a.setTitle("Audio Tour");a=a.getComponent("back");a.setText("Tours");a.on("tap",this.backHandler);NatsiaSetting.isAndroid&&(a.setVisible(!1),NatsiaSetting.setBackHander(this.backHandler));this.isVirtual=!0},backHandler:function(){Ext.dispatch({controller:app.controllers.artwork,action:"showVirtualTourList",animation:{type:"slide",direction:"right"}})}});
app.views.VirtualTourContainer=Ext.extend(Ext.Panel,{title:"Tours",iconCls:"_tours",layout:"card",initComponent:function(){Ext.apply(this,{items:[new app.views.VirtualTourList]});app.views.VirtualTourContainer.superclass.initComponent.apply(this,arguments)},listeners:{cardswitch:function(a,b,c){c&&c.destroy()},activate:function(){app.controllers.artwork.mainPanel=this},deactivate:function(){Ext.dispatch({controller:app.controllers.artwork,action:"showVirtualTourList",overrideMainPanel:this})}}});
Ext.reg("virtualTourContainer",app.views.VirtualTourContainer);
app.views.VirtualTourList=Ext.extend(Ext.Panel,{layout:"fit",items:[{xtype:"list",store:app.stores.virtuals,itemTpl:'<table><tr class="t-row"><td class="cat-title"><h2>{name}</h2></td></tr></table>',onItemDisclosure:function(a){Ext.dispatch({controller:app.controllers.artwork,action:"showTour",animation:{type:"slide",direction:"left"},id:a.getId()})},listeners:{itemtap:function(a,b){var c=app.stores.categories.getAt(b);Ext.dispatch({controller:app.controllers.artwork,action:"showTour",animation:{type:"slide",
direction:"left"},id:c.getId()})}}}],initComponent:function(){app.views.CategoryList.superclass.initComponent.apply(this,arguments);this.addDocked([{xtype:"toolbar",title:"Tours"}]);this.addDocked([{xtype:"logoPanel"}]);NatsiaSetting.isAndroid&&NatsiaSetting.resetBackHandler()}});Ext.reg("virtualTourList",app.views.VirtualTourList);
app.views.WinnersCategoryList=Ext.extend(Ext.Panel,{layout:"fit",items:[{xtype:"list",store:app.stores.winners,itemTpl:'<table><tr class="t-row"><td class="cat-title"><h2>{category}</h2></td></tr></table>',onItemDisclosure:function(a){a.data.id==8?Ext.dispatch({controller:app.controllers.artwork,action:"showCommendedCategoryList",animation:{type:"slide",direction:"left"}}):a.data.id==7?Ext.dispatch({controller:app.controllers.artwork,action:"showPeopleChoice",animation:{type:"slide",direction:"left"}}):
Ext.dispatch({controller:app.controllers.artwork,action:"showArtworkDetail",id:a.get("winnerId"),animation:{type:"slide",direction:"left"}})},listeners:{itemtap:function(a,b){var c=app.stores.winners.getAt(b);c.data.id==8?Ext.dispatch({controller:app.controllers.artwork,action:"showCommendedCategoryList",animation:{type:"slide",direction:"left"}}):Ext.dispatch({controller:app.controllers.artwork,action:"showArtworkDetail",id:c.get("winnerId"),animation:{type:"slide",direction:"left"}})}}}],listeners:{render:function(){this.getDockedItems();
this.doComponentLayout()},activate:function(a){app.controllers.artwork._backConfig={IsWinners:!0};a.ownerCt.isActive&&!NatsiaSetting.isAndroid&&NatsiaSetting.checkScroller(a.items.items[0].scroller)},beforedeactivate:function(){NatsiaSetting.isAndroid||NatsiaSetting.setArrow(!1)}},initComponent:function(){NatsiaSetting.isAndroid&&NatsiaSetting.resetBackHandler();app.views.WinnersCategoryList.superclass.initComponent.apply(this,arguments);this.addDocked([{xtype:"toolbar",title:"Winners"}]);this.addDocked([{xtype:"logoPanel"}])}});
Ext.reg("winnersCategoryList",app.views.WinnersCategoryList);
app.views.WinnersContainer=Ext.extend(Ext.Panel,{title:"Winners",iconCls:"_winners",layout:"card",initComponent:function(){Ext.apply(this,{items:[new app.views.WinnersCategoryList]});if(this.checkShowBadgeWinners())this.badgeText="1";app.views.WinnersContainer.superclass.initComponent.apply(this,arguments)},checkShowBadgeWinners:function(){var a=app.stores.persistedSettings.getById(1);return a?a.data.value==0:(app.stores.persistedSettings.add({id:1,name:"seenWinners",value:"0"}),app.stores.persistedSettings.sync(),
!0)},listeners:{cardswitch:function(a,b,c){c&&c.destroy()},activate:function(){app.controllers.artwork.mainPanel=this;app.controllers.artwork._backConfig={IsWinners:!0};this.badgeText="";app.controllers.artwork.setSeenWinners();if(!NatsiaSetting.isAndroid){var a=this.getActiveItem().items.items[0].scroller;NatsiaSetting.checkScroller(a)}},beforeactivate:function(){this.isActive=!0},deactivate:function(){this.isActive=!1;Ext.dispatch({controller:app.controllers.artwork,action:"showWinnersCategoryList",
overrideMainPanel:this})}}});Ext.reg("winnersContainer",app.views.WinnersContainer);

app.controllers.artwork=new Ext.Controller({_backConfig:null,showListFilterCategory:function(a){var b=parseInt(a.id),b=app.stores.categories.getById(b),c=b.get("name"),b=b.get("label");app.stores.artworks.clearFilter();app.stores.artworks.filterBy(function(a){if(a.get("category")==c)return!0;return!1});this._backConfig={IsCategory:!0,id:a.id};var d=new app.views.ArtworkListByCategory;d.setCategoryname(b);this.mainPanel.setActiveItem(d,a.animation)},showCategoryList:function(a){var b=this.mainPanel;
if(a.overrideMainPanel)b=a.overrideMainPanel;b.setActiveItem(new app.views.CategoryList,a.animation)},showWinnersCategoryList:function(a){var b=this.mainPanel;if(a.overrideMainPanel)b=a.overrideMainPanel;b.setActiveItem(new app.views.WinnersCategoryList,a.animation)},showCommendedCategoryList:function(a){var b=this.mainPanel;if(a.overrideMainPanel)b=a.overrideMainPanel;b.setActiveItem(new app.views.CommendedCategoryList,a.animation)},showPeopleChoice:function(a){var b=this.mainPanel;if(a.overrideMainPanel)b=
a.overrideMainPanel;b.setActiveItem(new app.views.PeopleChoice,a.animation)},backToList:function(a){this._backConfig.IsFavourites?(this.filterFavourites(),this.showFavouriteList(a)):this._backConfig.IsVirtual?(a.id=1,this.showTour(a)):this._backConfig.IsCategory?(a.id=this._backConfig.id,this.showListFilterCategory(a)):this._backConfig.IsSearch?this.showSearchPage(a):this._backConfig.IsWinners?this.showWinnersCategoryList(a):this._backConfig.IsCommended&&this.showCommendedCategoryList(a)},showArtworkDetail:function(a){var b=
parseInt(a.id),c=app.stores.artworks.getById(b);if(c){var d=new app.views.ArtworkDetails;app.stores.favourites.getById(b)&&d.setFavourite(!0);d.updateWithRecord(c);this.mainPanel.setActiveItem(d,a.animation)}},showImageDetail:function(a){var b=a.record,c=new app.views.ImageDetails;c.updateWithRecord(b);this.mainPanel.setActiveItem(c,a.animation);Ext.Anim.run(Ext.getCmp("pnlViewPort").getTabBar(),"slide",{direction:"down",autoClear:!1})},toggleFavourites:function(a){var b=this.mainPanel.getActiveItem(),
a=parseInt(a.record.data.id),c=app.stores.favourites.getById(a);c?(app.stores.favourites.remove(c),b.setFavourite(!1)):(app.stores.favourites.add({id:a}),b.setFavourite(!0));app.stores.favourites.sync()},setSeenWinners:function(){app.stores.persistedSettings.getById(1).set("value",1);app.stores.persistedSettings.sync();app.views.viewport.tabBar.items.items[4].setBadge("")},togglePlaySound:function(a){var b=this.mainPanel.getActiveItem();this.CurrentAudio?(this.stopSound(),b.setPlayButton(!1)):(this.CurrentAudio=
NatsiaSetting.isAndroid?new Media("/android_asset/www/audio/A"+a.recordId+".m4a"):new Audio("audio/A"+a.recordId+".m4a"),this.CurrentAudio.play(),b.setPlayButton(!0))},stopSound:function(){if(this.CurrentAudio)NatsiaSetting.isAndroid?this.CurrentAudio.stop():this.CurrentAudio.pause(),this.CurrentAudio=null},showVirtualTourList:function(a){var b=this.mainPanel;if(a.overrideMainPanel)b=a.overrideMainPanel;b.setActiveItem(new app.views.VirtualTourList,a.animation)},showTour:function(a){a.id==1?(app.stores.artworks.clearFilter(),
app.stores.artworks.sort(),this._backConfig={IsVirtual:!0},this.mainPanel.setActiveItem(new app.views.VirtualTourArtworkList,a.animation)):showVideoCommon("virtualtour")},filterFavourites:function(){this._backConfig={IsFavourites:!0};app.stores.artworks.clearFilter();app.stores.artworks.filterBy(function(a,b){if(app.stores.favourites.getById(b))return!0;return!1})},showFavouriteList:function(a){var b=this.mainPanel;if(a.overrideMainPanel)b=a.overrideMainPanel;b.setActiveItem(new app.views.FavouritesArtworkList,
a.animation)},filterSearch:function(){alert(123)},showSearchPage:function(a){var b=this.mainPanel;if(a.overrideMainPanel)b=a.overrideMainPanel;b.setActiveItem(new app.views.SearchArtworkList,a.animation)}});

Ext.regApplication({name:"app",launch:function(){NatsiaSetting.loadSettings();this.launched=!0;this.mainLaunch()},mainLaunch:function(){nativeAppOrientation=Ext.getOrientation();if(Ext.is.iOS&&navigator.userAgent.match(/safari/i)==null)document.body.style.overflow="hidden",document.getElementsByTagName("html")[0].style.overflow="hidden",Ext.EventManager.onWindowResize(function(){if(nativeAppOrientation!=Ext.getOrientation()){var a=document.createEvent("Events");a.initEvent("orientationchange",!0,
!1);document.dispatchEvent(a);nativeAppOrientation=Ext.getOrientation()}},this,{buffer:500});this.views.viewport=new this.views.Viewport}});
var NatsiaSetting={record:null,isAndroid:!1,backHandler:null,canRotate:!1,loadSettings:function(){NatsiaSetting.isAndroid=Ext.is.Android},setBackHander:function(a){NatsiaSetting.backHandler!=null&&document.removeEventListener("backbutton",NatsiaSetting.backHandler,!0);NatsiaSetting.backHandler=a;document.addEventListener("backbutton",a,!0)},resetBackHandler:function(){if(NatsiaSetting.backHandler!=null)document.removeEventListener("backbutton",NatsiaSetting.backHandler,!0),NatsiaSetting.backHandler=
null;navigator.app.overrideBackbutton(!1)},setArrow:function(a){var b=document.getElementById("arrow-cue");b&&Ext.defer(function(){b.style.display=a?"block":"none"},a?500:0)},checkScroller:function(a){a.containerBox.height!=a.size.height&&(NatsiaSetting.setArrow(!0),a.on("scroll",function(){NatsiaSetting.setArrow(!1)}))}};function shouldRotateToOrientation(a){switch(a){case 0:case 180:return!0;case 90:case -90:return NatsiaSetting.canRotate}};

var artDescription={artWorks:[{id:1,author:"Archie Moore",artName:"On a mission from God",type:"Paper sculpture",state:"QLD",dimensions:"3.5 x 3.5 x 4 cm",description:"<p> The bible and other texts have been referenced to communicate continuing colonialism/imperialism by Christian and state powers and intervention into sovereign people&#39;s lives, especially Indigenous Australians, by way of paper sculpture replicas of missions, churches, etc.</p> <p> &#39;Here I&#39;ve replicated the Mabuiag Mission church in the Torres Strait for my work <em>On a mission from God</em>, 2011. It is folded out of a passage of the bible in Genesis 28 in which &#39;God&#39; expounds: &quot;the land whereon thou liest, to thee will I give it, and to thy seed&quot;.&#39;</p> ",
category:"3d",winner:"",hasVideo:!0,hasSound:!0,isLandscape:!0},{id:2,author:"Crusoe Kurddal",artName:"Mimih spirit",type:"Natural pigments on kurrajong wood",state:"NT",dimensions:"240 x 18 x 10 cm",description:"<p> <em>Mimih</em> are spirit beings who reside in the rocky environment of the western Arnhem Land plateau. <em>Mimih</em> are said to have taught the first humans how to hunt and butcher game and also how to dance, sing and paint. The song and dance style of western Arnhem Land Aboriginal people is still known today as <em>mimih</em> style.</p> ",
category:"3d",winner:"",hasVideo:!0,hasSound:!0,isLandscape:!1},{id:3,author:"Dinni Kunoth Kemarre",artName:"Dinni&#8217;s chess set",type:"Synthetic polymer paint on wood",state:"NT",dimensions:"80 x 200 x 200 cm (overall)",description:"<p> Dinni uses wild colours and unexpected forms, carving with a flair and dynamism that is underpinned by an assured and perceptive vision. One of Dinni&#39;s friends is an avid chess set collector. Dinni was asked if he thought he could carve a chess set. <em>Dinni&#39;s chess set</em> provides another example of his extraordinary capacity to observe material relating to modern society and create his own idiosyncratic interpretations of the subject matter.</p> ",
category:"3d",winner:"3D Highly Commended",hasVideo:!0,hasSound:!0,isLandscape:!0},{id:4,author:"Gali Yalkarriwuy Gurruwiwi",artName:"Banumbirr (Morning Star pole)",type:"Natural pigments, feathers, wood, string",state:"NT",dimensions:"243 x 30 cm (overall - 2 poles)",description:"<p> Gali&#39;s <em>Banumbirr</em> (Morning Star pole) refers to the behaviour related to the beach and saltwater side of the Morning Star story, beginning at Naypinyu on the coast of Arnhem Land.</p> <p> The striped colours painted on the pole represent the movement of the Morning Star and the <em>Mokuy</em> (spirit) as it travels across the sea. The colours also reflect the different clan (moiety) groups. The bush strings attached to the pole tell of the Morning Star as it travels across the sea, giving life to creation. The black cockatoo feathers at the end of the bush string are reflective of the <em>Dhuwa</em> moiety, while the white cockatoo feathers signal that the pole is connected to the <em>Yirritja</em> moiety. The small grey feathers of the <em>birrkpirrk</em> (plover) represent the changing of the seasons. The Morning Star at the top of the pole is decorated with parrot feathers.</p> ",
category:"3d",winner:"3D Category Winner",hasVideo:!0,hasSound:!0,isLandscape:!1},{id:5,author:"Garawan Wanambi",artName:"Marrangu",type:"Natural pigments on wood",state:"NT",dimensions:"220x13.45cm 194x21cm 185x20cm",description:"<p> This painted surface depicts country close to Raymangirr, on the coast of Arnhem Bay. It is a sacred and restricted area where fresh water is known to spring to the surface of the beach at the low tide region.</p> ",category:"3d",winner:"",hasVideo:!0,hasSound:!0,isLandscape:!1},
{id:6,author:"Jeremiah Bonson",artName:"Wirrah Wirrah Bun Bun",type:"Synthetic polymer paint on wood",state:"NT",dimensions:"186 x 60 cm (overall)",description:"<p> The <em>Wirrah Wirrah Bun Bun</em> is a Yirritja spirit. The <em>Wirrah Wirrah Bun Bun</em> is a very tall spirit and when he dances he is covered with white ochre. This is represented by the white dots on the carving.</p> ",category:"3d",winner:"",hasVideo:!0,hasSound:!0,isLandscape:!1},{id:7,author:"Lena Yarinkura",artName:"Wyarra",
type:"Paperbark, natural pigments, feathers, string, pandanus fibre",state:"NT",dimensions:"174 x 38 x 2 cm",description:"<p> <em>Wyarra</em> are spirits that live in the bush and move around mainly at night. Humans can&#39;t see these spirits but can hear them at night. However, witch doctors are said to be able to see <em>wyarra </em>spirits at night. <em>Wyarra</em> spirits can follow humans, visit them and interact with them - they can be friendly and look after them if they&#39;re lost in the bush or be cheeky and play tricks on them.</p> <p> There are also dreaming sites for <em>wyarra</em> spirits and, if you move rocks on these sites, <em>wyarras</em> will appear from everywhere.</p> ",
category:"3d",winner:"",hasVideo:!0,hasSound:!0,isLandscape:!1},{id:8,author:"Lucy Malirrimurruwuy Wanapuyngu",artName:"Healthy food from the past",type:"Pandanus fibre, feathers, string",state:"NT",dimensions:"150 x 48 x 10 cm (overall)",description:"<p> <em>Djitama</em>, <em>bunbun</em>, <em>gandiwulk</em> and <em>garr&#39;barda</em> are four very healthy bush yams. If more Yolngu people ate them they would feel stronger and live longer, like our families in the past. I like to remind people about the foods from the past and make sure our grandchildren will learn about them.</p> ",
category:"3d",winner:"3D Highly Commended",hasVideo:!0,hasSound:!0,isLandscape:!1},{id:9,author:"Richard Djarrimili",artName:"Tree of Knowledge",type:"Wood, natural pigments, feathers, string",state:"NT",dimensions:"188 x 30 cm",description:"<p> Richard Djarrimili makes<em> Dhuwa</em> poles for the <em>Dhuwa</em> clans to be used in memorial ceremonies. They guide the deceased person&#39;s spirit to the Morning Star - the <em>Banumbirr</em>. The feathers represent the spirit&#39;s food. The bush string wrapped around the poles represents the different places to which the<em> Banumbirr</em> travels.</p> ",
category:"3d",winner:"",hasVideo:!0,hasSound:!0,isLandscape:!1},{id:10,author:"Vicki West",artName:"Luna",type:"Kelp, recycled material",state:"TAS",dimensions:"32 x 100 x 32 cm",description:"<p> &#39;<em>Luna</em> is created from bull kelp, a seaweed collected from my country in north-east Tasmania. Kelp was used by my ancestors to create water carriers, which were essential for their survival. <em>Luna</em> expresses my concern for country.&#39;</p> ",category:"3d",winner:"",hasVideo:!0,hasSound:!0,
isLandscape:!0},{id:11,author:"Djambawa Marawili",artName:"Yathikpa",type:"Natural pigments on bark",state:"NT",dimensions:"162 x 247 cm (overall)",description:"<p> This novel triptych ties together three ancestral forces that share the fire-imbued <em>Madarrpa</em> water of Yathikpa in Blue Mud Bay. By creating three separate but related images, Djambawa is instructing the viewer on how <em>Baru</em>, <em>Djunungayangu</em> and <em>Mundukul</em> fit together.</p> ",category:"bark",winner:"Bark Painting Highly Commended",
hasVideo:!1,hasSound:!0,isLandscape:!0},{id:12,author:"Djirrirra Wunungmurra ",artName:"Buyku",type:"Natural pigments on bark",state:"NT",dimensions:"73 x 54 cm",description:"<p> This intense incised work by Djirrirra symbolises an ancestral fishtrap ceremony, which unifies the groups along the Gangan River.</p> ",category:"bark",winner:"",hasVideo:!1,hasSound:!0,isLandscape:!1},{id:13,author:"Glen Namundja",artName:"Namorrodoh",type:"Natural pigments on bark",state:"NT",dimensions:"145 x 67 cm",
description:"<p> <em>Namorrodoh</em> beings are devil-like men who inhabited Arnhem Land during the Dreamtime. <em>Kuninjku</em> people believe <em>Namorrodoh</em> can steal the spirits of their dead if they are not laid to rest in the culturally appropriate way. It is said that <em>Namorrodoh</em> traverses the sky in the form of a shooting star, looking for souls to steal.</p> ",category:"bark",winner:"",hasVideo:!1,hasSound:!0,isLandscape:!1},{id:14,author:"Gunybi Ganambarr",artName:"Munbi",type:"Natural pigments on bark",
state:"NT",dimensions:"101 x 57 cm",description:"<p> This work shows the mounds created by long-neck turtle along the riverbank in the dry season. This is a metaphor for the life-bearing activities associated with the ancestral being, <em>Barrama</em>.</p> ",category:"bark",winner:"",hasVideo:!1,hasSound:!0,isLandscape:!1},{id:15,author:"Ivan Namirrkki",artName:"Stone country",type:"Natural pigments on bark",state:"NT",dimensions:"170 x 67 cm",description:"<p> In this painting, Ivan Namirrkki has depicted a creek at Kudjaldorrdo located near his outstation. This creek is a sacred site associated with <em>Ngalyod</em>, the rainbow serpent. <em>Ngalyod</em> is very important in <em>Kuninjku</em> cosmology and is associated with the creation of sacred sites in <em>Kuninjku</em> clan lands. <em>Ngalyod</em> has both powers of creation and destruction, and is most strongly associated with the monsoon season, bodies of water and waterfalls, and rainbows.</p> ",
category:"bark",winner:"",hasVideo:!1,hasSound:!0,isLandscape:!1},{id:16,author:"James Iyuna",artName:"Pregnant Buluwana at Dilebang",type:"Natural pigments on bark",state:"NT",dimensions:"188 x 73 cm",description:"<p> This painting depicts <em>Buluwana</em> superimposed on the background of crosshatching with her <em>kun-madj </em>(dilly bag) and digging stick. She is depicted at a site called Dilebang, which is regarded as one of the most dangerous and sacred of sites in the <em>Kun-Kurulk</em> clan estate. The billabong at Dilebang is near escarpment country rich in rock art and with a high concentration of sacred sites.</p> ",
category:"bark",winner:"",hasVideo:!1,hasSound:!0,isLandscape:!1},{id:17,author:"Nyapanyapa Yunupingu",artName:"Mayilimiriw",type:"Natural pigments on bark",state:"NT",dimensions:"168 x 68 cm",description:"<p> This is a work without a sacred meaning. It is an expression of the artist&#39;s hand.</p> ",category:"bark",winner:"",hasVideo:!1,hasSound:!0,isLandscape:!1},{id:18,author:"Paul Nabulumo Namarinjmak",artName:"Ngalyod - Rainbow serpent in the stone country",type:"Natural pigments on bark",state:"NT",
dimensions:"200 x 65 cm",description:"<p> <em>Ngalyod</em> is very important in <em>Kuninjku</em> cosmology and is associated with the creation of sacred sites in <em>Kuninjku</em> clan lands. <em>Ngalyod</em> has both powers of creation and destruction and is most strongly associated with the monsoon season, bodies of water and waterfalls, and rainbows. Aboriginal myths about the rainbow serpent often describe her as a fearful creature who swallows humans only to regurgitate them, transformed by her blood.</p> ",
category:"bark",winner:"",hasVideo:!1,hasSound:!0,isLandscape:!1},{id:19,author:"Raelene Kerinauia",artName:"Kayimwagakimi Jilamara",type:"Natural pigments on bark",state:"NT",dimensions:"139 x 70 cm",description:"<p> &#39;I paint with the <em>kayimwagakimi</em>, or comb, sometimes called <em>pwoja</em>, which also means bone. The painting comb is made from ironwood and is used to paint on the body, on <em>pukumani</em> poles, and on bark. My partner made me my comb; he was an artist, a great carver, and I used to paint his carvings and <em>tutini</em> (<em>pukumani</em> poles). He passed away not long ago. I use ochres from the Tiwi Islands for my painting and I mainly just use my <em>pwoja</em>; only sometimes do I use brushes.&#39;</p> ",
category:"bark",winner:"Bark Painting Category Winner",hasVideo:!1,hasSound:!0,isLandscape:!1},{id:20,author:"Susan Marawarr",artName:"Buluwana at Dilebang",type:"Natural pigments on bark",state:"NT",dimensions:"210 x 51 cm",description:"<p> This painting depicts <em>Buluwana</em> superimposed on the background of crosshatching with her <em>kun-madj</em> (dilly bag) and digging stick. She is depicted at a site called Dilebang, which is regarded as one of the most dangerous and sacred of sites in the <em>Kun-Kurulk</em> clan estate. The billabong at Dilebang is near escarpment country rich in rock art and with a high concentration of sacred sites.</p> ",
category:"bark",winner:"",hasVideo:!1,hasSound:!0,isLandscape:!1},{id:21,author:"Yumutjin Wunungmurra",artName:"Buyku",type:"Natural pigments on bark",state:"NT",dimensions:"133 x 64 cm",description:"<p> An ancestral being is driving fish towards the fishtrap at Gangan. These are <em>baypinnga</em> (saratoga), and the trap, the fishermen, the fish, and the water are all sanctified by the design of this place that belongs to the <em>Dhalwangu</em> clan.</p> ",category:"bark",winner:"",hasVideo:!1,
hasSound:!0,isLandscape:!1},{id:22,author:"David Lans",artName:"The Lennard identity",type:"Video",state:"WA",dimensions:"1.07 Minutes",description:"<p> This short film work showcases David&#39;s developing skills in writing, directing and editing &#39;action&#39; sequences. The film was created on remote Balgo Community in Western Australia with local actors as part of the skill development phases of <em>The Motika Project</em>.</p> ",category:"new_media",winner:"",hasVideo:!1,hasSound:!0,isLandscape:!0},
{id:23,author:"Ricardo Idagi",artName:"Upi mop le - Tail end man",type:"Mixed media",state:"VIC",dimensions:"130 x 90 x 130 cm",description:"<p> When I wear the mask, I am ready to take back my spirit that I lost as a child. When I dance my victory dance, I will take the power away from them. By performing my culture, I will turn defeat into victory.&#39;</p> ",category:"new_media",winner:"New Media Category Winner",hasVideo:!0,hasSound:!0,isLandscape:!1},{id:24,author:"Alison Riley",artName:"Seven sisters",
type:"Synthetic polymer paint on linen",state:"SA",dimensions:"197 x 197 cm",description:"<p> This is a <em>Tjukurpa</em> story (creation story) about the constellations of Pleiades and Orion. The sisters are the constellation of Pleiades and the other star, Orion, is said to be <em>Nyiru</em> or <em>Nyirunya</em> (described as a lusty or bad man). <em>Nyiru</em> is forever chasing the sisters as it is said he wants to marry the eldest sister.</p> ",category:"painting",winner:"People's Choice Award Winner",
hasVideo:!1,hasSound:!0,isLandscape:!0},{id:25,author:"Angkaliya Curtis",artName:"Cave Hill",type:"Synthetic polymer paint on linen",state:"SA",dimensions:"120 x 200 cm",description:"<p> Here there are four <em>perentie</em> lizards and some small lizards, as well as caterpillars and some small snakes that live in the water with the frogs. There are many black cockatoos. This is my husband Bill&#39;s country, Cave Hill. There are four rockholes and the creek is flowing, attracting the emus. One of the birds has hurt his foot and he&#39;s sitting down. There is a centipede and a large horned grasshopper.&#39;</p> ",
category:"painting",winner:"",hasVideo:!1,hasSound:!0,isLandscape:!1},{id:26,author:"Bernard Tjalkuri",artName:"Tjitji Tjuta",type:"Synthetic polymer paint on linen",state:"SA",dimensions:"200 x 120 cm",description:"<p> There are many children. They all go to that sacred place where they do their dance. There are blue-tongue lizard children and emu children and bush curlew children; all the different children. All the time the emu men are watching from behind the bush. The children have a special dancing ground where they dance close to Watarru. Their fathers have their own dance and the women have their own dance too.</p> ",
category:"painting",winner:"",hasVideo:!1,hasSound:!0,isLandscape:!1},{id:27,author:"Bobby West Tjupurrula",artName:"untitled",type:"Synthetic polymer paint on linen",state:"WA",dimensions:"122 x 122 cm",description:"<p> This painting depicts designs associated with the rockhole site of Tarkul, north of Mt Webb in Western Australia. In ancestral times a large group of <em>Tingari</em> men, both young and old, came to this site, where they were burnt in a large fire.</p> ",category:"painting",winner:"General Painting Winner",
hasVideo:!1,hasSound:!0,isLandscape:!1},{id:28,author:"Carol Maanyatja Golding",artName:"Walu",type:"Synthetic polymer paint on canvas",state:"WA",dimensions:"153 x 76 cm",description:"<p> There were two men and one little boy camping at the Walu rockhole. The men went hunting and left the little boy behind. The men returned with an emu and pulled out its heart. The boy was holding the heart and blood spilt on the rocks. He ran away with the heart and turned into wind.</p> ",category:"painting",winner:"",
hasVideo:!1,hasSound:!0,isLandscape:!1},{id:29,author:"Christopher Pease",artName:"Bling",type:"Oil paint on linen",state:"WA",dimensions:"213 x 152 cm",description:"<p> <em>Bling</em> has been composed from multiple photographs to create an ambiguous image. The individual wears a gorget and stands proud and defiant. He is a reclamation of past history. He is also in danger of being misinterpreted as a &#39;rap star&#39; and thus losing his identity. The painting raises the questions: who are we now and where are we going?</p> ",
category:"painting",winner:"General Painting Highly Commended",hasVideo:!1,hasSound:!0,isLandscape:!1},{id:30,author:"Dickie Minyintiri",artName:"Kanyalakutjina (Euro tracks)",type:"Synthetic polymer paint on canvas",state:"SA",dimensions:"155 x 184 cm",description:"<p> <em>Kanyalakutjina</em> are euro tracks. This is a creation story from the area of Dickie&#39;s <em>ngura</em> (birthplace). <em>Kanyala</em> stories are men&#39;s stories and hunting stories. <em>Kanyala</em> drink from the <em>kapi tjukula</em> (waterholes, depicted by circles) in Dickie&#39;s country. He is responsible for looking after this country and the creation beings from there.</p> ",
category:"painting",winner:"Telstra Award Winner",hasVideo:!1,hasSound:!0,isLandscape:!0},{id:31,author:"Eubena Nampitjin",artName:"Kinyu",type:"Synthetic polymer paint on linen",state:"WA",dimensions:"150 x 100 cm",description:"<p> Eubena has painted some of her country south-west of Balgo along the middle stretches of the Canning Stock Route. The majority of the painting shows the <em>tali</em> (sandhills) that dominate this country. The central circle is <em>tjurrnu</em> (soakwater) named Midjul. This is the country where <em>Kinyu</em> the spirit dog lives. Eubena would often cover Midjul with leaves so <em>Kinyu</em> wouldn&#39;t come out and would also leave gifts of goanna for <em>Kinyu</em>.</p> ",
category:"painting",winner:"",hasVideo:!1,hasSound:!0,isLandscape:!1},{id:32,author:"George Tjungurrayi",artName:"untitled",type:"Synthetic polymer paint on canvas",state:"NT",dimensions:"183 x 244 cm",description:"<p> This painting relates to the claypan site known as Mamultjulkulnga, on the western side of Wilkinkarra (Lake Mackay). Mamultjulkulnga is of great importance to the artist as his father passed away at this site.</p> ",category:"painting",winner:"General Painting Highly Commended",hasVideo:!1,
hasSound:!0,isLandscape:!0},{id:33,author:"Ginger Wikilyiri",artName:"Panakura",type:"Synthetic polymer paint on linen",state:"SA",dimensions:"200 x 200 cm",description:"<p> This is the story of two ancestral beings, the husband and wife desert death adder. They are sitting at their home. Each day they venture out to the cave and paint sacred designs on the cave walls before returning home again. Their home is in the sandhills close to Kunamata. Also painted here is the ant lion, which lives in the sandhills.</p> ",
category:"painting",winner:"",hasVideo:!1,hasSound:!0,isLandscape:!0},{id:34,author:"Gladdy Kemarre",artName:"Anwekety (Bush plum)",type:"Synthetic polymer paint on linen",state:"NT",dimensions:"133 x 180 cm",description:"<p> <em>Anwekety</em>, the bush plum, is a Dreaming story given to Gladdy by her grandmother. Viewed from above, the changing seasonal colours of the <em>anwekety</em> dominate the flora on the ground in <em>Ahalpere</em> country. Gladdy&#39;s shimmering and sweeping expanses of fine dots, transposed over a dark field, create a rich and vertiginous image of desert terrain. The joyful rhythms of the canvas reflect Gladdy&#39;s pride in passing down the story of the bush plum, just as her grandmother did before her.</p> ",
category:"painting",winner:"",hasVideo:!1,hasSound:!0,isLandscape:!0},{id:35,author:"Harry Tjutjuna",artName:"Wati Nyiru munu Wati Wanka",type:"Synthetic polymer paint on linen",state:"SA",dimensions:"244 x 183 cm",description:"<p> This is a painting of two stories - <em>Wati Nyiru</em> and <em>Wati Wanka</em>. The first story is a variation of the Seven Sisters Dreaming from a male perspective. <em>Wati Nyiru</em> chases the seven sisters around and catches the youngest. The second story is about a powerful spider man. As the artist describes, &#39;I am the spider man, <em>ngankari</em> [traditional healer]&#39;.</p> ",
category:"painting",winner:"",hasVideo:!1,hasSound:!0,isLandscape:!1},{id:36,author:"Hector Burton",artName:"Arumara Tjukurpa",type:"Synthetic polymer paint on linen",state:"SA",dimensions:"197 x 197 cm",description:"<p> This painting tells the story of the caterpillars - <em>anumara</em>. The <em>anumara</em> is a large edible caterpillar with a hook on its tail. All the caterpillars travelled from places in the north and the south. It is a story about kinship groups; Hector is in one group - the south (<em>anumara</em>) - and his uncles, nephews, and fathers are in the north.</p> ",
category:"painting",winner:"",hasVideo:!1,hasSound:!0,isLandscape:!1},{id:37,author:"Jean Baptiste Apuatimi",artName:"Jirtaka (Sawfish)",type:"Natural pigments on linen",state:"NT",dimensions:"153 x 123 cm",description:"<p> <em>Jirtaka</em> is lovely tucker. My husband used to get that fish and bring him home ... The first painting my husband did was on that bone. I like to paint this because my husband taught me.&#39;</p> ",category:"painting",winner:"",hasVideo:!1,hasSound:!0,isLandscape:!1},{id:38,
author:"Johnny Yungut Tjupurrula",artName:"untitled",type:"Synthetic polymer paint on linen",state:"NT",dimensions:"153 x 183 cm",description:"<p> This painting depicts designs associated with the soakage site of Wanaritjarra, north of Winparku (Mt Webb) in Western Australia. This is the artist&#39;s father&#39;s country.</p> <p> In ancestral times a large group of <em>Tingari</em> men camped at this site before continuing their travels north to the swamp site of Tingaritjarra and then Wilkinkarra (Lake Mackay).</p> ",
category:"painting",winner:"",hasVideo:!1,hasSound:!0,isLandscape:!0},{id:39,author:"Kawayi Nampitjinpa",artName:"untitled",type:"Synthetic polymer paint on linen",state:"NT",dimensions:"122 x 153 cm",description:"<p> This painting depicts the ancestral <em>wanampi</em> (water snakes) that travelled from the site of Pinpirrnga (Desert Bore) to Pinari, north-west of Kintore. The <em>wanampi</em> were of the <em>Tjakamarra</em> kinship subsection and they were searching for suitable mates of the <em>Napaltjarri</em> kinship subsection. On their travels, the snakes created the large <em>tali</em> (sandhills) and <em>puli</em> (rocky outcrops) throughout this area.</p> ",
category:"painting",winner:"",hasVideo:!1,hasSound:!0,isLandscape:!0},{id:40,author:"Margaret Boko",artName:"Looking for kampurarrpa",type:"Synthetic polymer paint on canvas",state:"NT",dimensions:"40 x 55 cm",description:"<p> This painting is about looking around for <em>kampurarrpa</em> (bush berries) out bush on the weekend.</p> ",category:"painting",winner:"",hasVideo:!1,hasSound:!0,isLandscape:!0},{id:41,author:"Maringka Baker",artName:"Kata Ala",type:"Synthetic polymer paint on linen",state:"SA",
dimensions:"200 x 120 cm",description:"<p> Kata Ala is my country in Western Australia. Song lines for the different <em>Tjukurpa</em> cross here. The two mythical serpent men from Pukara and the ancestral zebra finch women came here, and <em>Wati Nyiru</em> camped close by in his pursuit of the seven sisters.</p> ",category:"painting",winner:"",hasVideo:!1,hasSound:!0,isLandscape:!1},{id:42,author:"Mercy Paymurra Fredericks",artName:"Nature spirits",type:"Natural pigments on canvas",state:"WA",dimensions:"80 x 100 cm",
description:"<p> This work shows a crocodile hunting scene. The elongated figures are bush spirits, hunters of fish. They are hunting a crocodile, which can be seen at the top of the painting. The smaller figures in the central white dotted area are <em>Jarnba</em>, mischievous spirits. They are waiting around hungry, eager to eat.</p> ",category:"painting",winner:"",hasVideo:!1,hasSound:!0,isLandscape:!0},{id:43,author:"Molly Napurrurla Tasman",artName:"Bush Potato Dreaming",type:"Synthetic polymer paint on linen",
state:"NT",dimensions:"180 x 150 cm",description:"<p> This Dreaming tells about bush yam or potatoes. The trees are green all year round. When the flowers are on the tree the women know that the potatoes are ready to be dug. They are deep in the ground, sometimes more than one metre. The women gather them in the coolamon.</p> ",category:"painting",winner:"",hasVideo:!1,hasSound:!0,isLandscape:!1},{id:44,author:"Nellie Stewart",artName:"Minyma kutjara",type:"Synthetic polymer paint on linen",state:"SA",
dimensions:"200 x 200 cm",description:"<p> This is the story of two ancestral women. They were carrying a sacred digging stick and would throw it in front of them. The digging stick skidded along the ground and lay there. They picked it up and went north to a place called Ngurapila and performed sacred dancing.</p> ",category:"painting",winner:"",hasVideo:!1,hasSound:!0,isLandscape:!0},{id:45,author:"Nora Wompi",artName:"Kunawarritji",type:"Synthetic polymer paint on linen",state:"WA",dimensions:"180 x 120 cm",
description:"<p> Country near Kunawarritji Community (Well 33), Western Australia.</p> ",category:"painting",winner:"",hasVideo:!1,hasSound:!0,isLandscape:!1},{id:46,author:"Patrick Mung Mung ",artName:"Purnululu",type:"Natural pigments on canvas",state:"WA",dimensions:"150 x 180 cm",description:"<p> Patrick Mung Mung has painted his grandfather&#39;s and great-grandfather&#39;s country. &#39;That&#39;s all that sandy hill country with green grasses and the old people used to live there in the old days.&#39; <em>Nawugarlwin</em> (frog) is the <em>Gija</em> name for this place.</p> ",
category:"painting",winner:"",hasVideo:!1,hasSound:!0,isLandscape:!0},{id:47,author:"Pauline Moran",artName:"Memories of Roelands Mission",type:"Synthetic polymer paint on canvas",state:"NT",dimensions:"180 x 84 cm (overall)",description:"<p> Like so many of her generation, as a child Pauline Moran was removed from her family and placed in Roelands Mission, near Collie. Moran delves deep into her biography, going to great lengths to accurately record the minutiae of her experiences - whether it be capturing the details of dormitories and dining rooms or recalling very specific events from her childhood.</p> <p> This body of work was modelled from black and white photographs taken in the 1950s at Roelands Mission in the south-west of Western Australia.</p> ",
category:"painting",winner:"",hasVideo:!1,hasSound:!0,isLandscape:!0},{id:48,author:"Peter Datjing",artName:"Ganiny with fog",type:"Natural pigments on canvas",state:"NT",dimensions:"152 x 91 cm",description:"<p> This is a sacred story about the <em>Gamatj</em> clan, their life and laws.</p> <p> The painting depicts the <em>Ganiny</em> (<em>Gun-ning</em>) in the centre, a sacred ceremonial item that is held by the clan leader while dancing. It is part of a sacred and secret ceremony, generally a mortuary ceremony, belonging to the people of the <em>Yirritja</em> moiety and is performed by men only. The ceremony is held under a paperbark tree, which is symbolic and an important part of the ceremony.</p> <p> The white tips of the <em>Ganiny</em> represent the paperbark. This is also the same white ochre that is painted on the forehead of the local <em>Yolngu</em> for funerals and other ceremonies.</p> ",
category:"painting",winner:"",hasVideo:!1,hasSound:!0,isLandscape:!1},{id:49,author:"Ray Ken",artName:"Tali",type:"Synthetic polymer paint on linen",state:"SA",dimensions:"122 x 300 cm",description:"<p> In this painting Ray Ken has depicted weapons including <em>kulata</em> (spear), <em>miru</em> (spear thrower), <em>tjutinypa</em> (club), <em>kali</em> (boomerang) and <em>tjara</em> (shield). Ray says these instruments are used by men for hunting and also for fighting against the soldier. The country surrounding the weapons is Ray&#39;s country, which is <em>tali</em>, the sandhill country around Watarru.</p> ",
category:"painting",winner:"",hasVideo:!1,hasSound:!0,isLandscape:!0},{id:50,author:"Regina Pilawuk Wilson",artName:"Syaw (Fish net)",type:"Synthetic polymer paint on linen",state:"NT",dimensions:"200 x 120 cm",description:"<p>&#39;My grandfather used to make big fish net, <em>syaw</em>. A man&#39;s job for this one because he used to hunt for the women and children. They used to make a big <em>syaw</em> to catch fish, barramundi, turtle ...&#39;</p> ",category:"painting",winner:"",hasVideo:!1,hasSound:!0,
isLandscape:!1},{id:51,author:"Thelma Dixon",artName:"Olden times stockcamp",type:"Synthetic polymer paint on linen",state:"NT",dimensions:"110.5 x 89 cm",description:"<p> &#39;The riders on white horses are the head stockmen, the bosses. The rider on the black horse, he&#39;s called the headboy. He is the second boss. So the headboy listens to the head stockman, and then he tells the workers what needs to be done in the stockcamp - mustering. The horses that have a hobble strap are the spare horses. There are also packhorses to carry food.&#39;</p> ",
category:"painting",winner:"",hasVideo:!1,hasSound:!0,isLandscape:!1},{id:52,author:"Tiger Palpatja",artName:"Wanampi Tjukurpa",type:"Synthetic polymer paint on linen",state:"SA",dimensions:"122 x 300 cm",description:"<p> This story is about the mythical <em>wanampi</em> (rainbow or water snake). It tells the creation story related to the country around Piltati in north-west South Australia and is about two sisters and their husbands, who are brothers. This story has particular significance to Tiger as Piltati is his family&#39;s country and the <em>wanampi</em> are his ancestors.</p> ",
category:"painting",winner:"",hasVideo:!1,hasSound:!0,isLandscape:!0},{id:53,author:"Timothy Cook",artName:"Kulama",type:"Natural pigments on linen",state:"NT",dimensions:"120 x 200 cm",description:"<p> The way Timothy Cook uses ochre without hesitation, composing his paintings with pure instinct, masses of flat coloured spaces, and the ability to shift his perspective and translate his <em>kulama</em> (coming of age ceremony for young men) to new levels, is ongoing.</p> <p> Timothy&#39;s identity as an artist is based on a spirit of unpredictability. His art is imbued with a sense of purity and evokes a sense of the divine.</p> ",
category:"painting",winner:"",hasVideo:!1,hasSound:!0,isLandscape:!0},{id:54,author:"Tjapartji Bates",artName:"Kungkarangkalpa",type:"Synthetic polymer paint on canvas",state:"WA",dimensions:"152 x 76 cm",description:"<p> This painting is about the <em>Kungkarangkalpa</em> (Seven Sisters). They travelled through <em>tali</em> (sandhills) country, camping at rockholes and hunting for <em>kuka</em> (meat). They killed a <em>Tiwil</em>. They then went to Kalalu and went crawling along the creek, ending up in Wanarn.</p> ",
category:"painting",winner:"",hasVideo:!1,hasSound:!0,isLandscape:!1},{id:55,author:"Wintjiya Napaltjarri",artName:"untitled",type:"Synthetic polymer paint on linen",state:"NT",dimensions:"122 x 122 cm",description:"<p> This painting depicts designs associated with the soakage site of Watanuma, north-west of the Kintore community. A group of ancestral women once gathered at Watanuma to perform the dances and sing the songs associated with the area. The women also spun hair-string for making <em>nyimparra</em> (hair-string skirts), which are worn by both men and women during ceremonies.</p> ",
category:"painting",winner:"",hasVideo:!1,hasSound:!0,isLandscape:!1},{id:56,author:"Yukultji Napangati",artName:"untitled",type:"Synthetic polymer paint on linen",state:"WA",dimensions:"153 x 183 cm",description:"<p> During ancestral times a group of women camped at this site after travelling from further west. While at Yunala the women camped beside the rockhole, digging for edible roots also known as <em>yunala</em>. The lines in the work represent both the sandhills surrounding the site as well as the <em>yunala</em> tubers underground.</p> ",
category:"painting",winner:"",hasVideo:!1,hasSound:!0,isLandscape:!0},{id:57,author:"Brian Robinson",artName:"Sa mina las kaikai",type:"Embossed linocut on paper",state:"QLD",dimensions:"50 x 109 cm",description:"<p> <em>Sa mina las kaikai</em>, a phrase in broken English or Torres Strait Creole, translates as &#39;the last supper&#39;. <em>The Last Supper</em> is a magnificent 15th century mural by Leonardo da Vinci, a biblical narrative which, according to Christian belief, was the final meal that Jesus Christ shared with his twelve apostles in Jerusalem before his crucifixion. <em>Sa mina las kaikai</em> is the Torres Strait version.</p> ",
category:"paper",winner:"",hasVideo:!0,hasSound:!0,isLandscape:!0},{id:58,author:"Dennis Nona",artName:"Zuga Zug",type:"Etching on paper",state:"QLD",dimensions:"50 x 98 cm",description:"<p> This work relates to a <em>Dogai</em>, or witch, who comes to grief at the hands of villagers from the artist&#39;s island of Badu.</p> <p> On the <em>Dogai&#39;s</em> island of Zurath, her right arm and breasts are cut off and taken back to Badu. The night of the incident she comes looking for her appendages. She can&#39;t find her breasts as they had been thrown into the sea where they morphed into rocky outcrops that can be seen today between the two islands.</p> ",
category:"paper",winner:"Works on Paper Category Winner",hasVideo:!1,hasSound:!0,isLandscape:!0},{id:59,author:"Michael Nona",artName:"Mackerel",type:"Relief print on paper",state:"QLD",dimensions:"76 x 112 cm",description:"<p> &#39;<em>Dhubu</em> is our local name for the mackerel. The <em>Dhubu</em> is a big game fish and a very powerful swimmer. I caught my first big one from the island jetty when I was 12 years old. It was almost bigger than me and I had a hard time carrying it home.&#39;</p> ",
category:"paper",winner:"",hasVideo:!1,hasSound:!0,isLandscape:!0},{id:60,author:"Sadie Singer",artName:"Old trucks",type:"Etching on paper",state:"SA",dimensions:"21 x 24 cm",description:"<p> Sadie has created this etching of trucks because they remind her of good times when she was younger. Back then, her uncle used to take her and other friends and family out swimming, camping and hunting in his truck. They always had fun in that old truck.</p> ",category:"paper",winner:"",hasVideo:!1,hasSound:!0,
isLandscape:!1},{id:61,author:"Wukun Wanambi",artName:"Bamurrungu",type:"Embossed etching on paper",state:"NT",dimensions:"67 x 64 cm",description:"<p> This work emphasises the invisible forces that imbue the <em>Yolngu</em> reality. The <em>Marrakulu</em> clan sing themselves as mullet. They school in dance and overcome the barrier of mortality as a fish leaps a rock.</p> ",category:"paper",winner:"",hasVideo:!0,hasSound:!0,isLandscape:!0}]};
app.models.Artwork=Ext.regModel("app.models.Artwork",{fields:[{name:"id",type:"int"},{name:"author",type:"string"},{name:"artName",type:"string"},{name:"type",type:"string"},{name:"dimensions",type:"string"},{name:"description",type:"string"},{name:"category",type:"string"},{name:"state",type:"string"},{name:"hasVideo",type:"boolean"},{name:"hasSound",type:"boolean"},{name:"isLandscape",type:"boolean"},{name:"winner",type:"string"}]});
app.stores.artworks=new Ext.data.Store({model:"app.models.Artwork",sorters:"id",data:artDescription,proxy:{type:"memory",reader:{type:"json",root:"artWorks"}}});var dataCategories={categories:[{id:1,name:"painting",label:"Painting"},{id:2,name:"bark",label:"Bark Painting"},{id:3,name:"paper",label:"Work on Paper"},{id:4,name:"3d",label:"3D"},{id:5,name:"new_media",label:"New Media"}]};
app.models.Category=Ext.regModel("app.models.Category",{fields:[{name:"id",type:"int"},{name:"name",type:"string"},{name:"label",type:"string"}]});app.stores.categories=new Ext.data.Store({model:"app.models.Category",sorters:"id",data:dataCategories,proxy:{type:"memory",reader:{type:"json",root:"categories"}}});
var commendedData={commended:[{id:1,category:"General Painting",winnerId:29},{id:2,category:"General Painting",winnerId:32},{id:3,category:"Bark Painting",winnerId:11},{id:4,category:"3D",winnerId:3},{id:5,category:"3D",winnerId:8}]};app.models.Commended=Ext.regModel("app.models.Commended",{fields:[{name:"id",type:"int"},{name:"category",type:"string"},{name:"winnerId",type:"int"}]});
app.stores.commended=new Ext.data.Store({model:"app.models.Commended",sorters:"id",data:commendedData,proxy:{type:"memory",reader:{type:"json",root:"commended"}}});app.models.Event=Ext.regModel("app.models.Favourite",{fields:[{name:"id",type:"int"}]});app.stores.favourites=new Ext.data.Store({model:"app.models.Favourite",autoLoad:!0,autoSave:!0,proxy:{type:"localstorage",id:"NATSIAA28-Favourites"}});
app.models.PersistedSettings=Ext.regModel("app.models.PersistedSettings",{fields:[{name:"id",type:"int"},{name:"setting",type:"string"},{name:"value",type:"int"}]});app.stores.persistedSettings=new Ext.data.Store({model:"app.models.PersistedSettings",autoLoad:!0,autoSave:!0,proxy:{type:"localstorage",id:"NATSIAA28-Settings"}});var dataVirtual={virtuals:[{id:1,name:"Audio Tour"},{id:2,name:"Virtual Tour"}]};
app.models.Virtual=Ext.regModel("app.models.Virtual",{fields:[{name:"id",type:"int"},{name:"name",type:"string"}]});app.stores.virtuals=new Ext.data.Store({model:"app.models.Virtual",sorters:"id",data:dataVirtual,proxy:{type:"memory",reader:{type:"json",root:"virtuals"}}});
var winnersData={winners:[{id:1,category:"Telstra Award Winner",winnerId:30},{id:2,category:"Painting",winnerId:27},{id:3,category:"Bark Painting",winnerId:19},{id:4,category:"Work on Paper",winnerId:58},{id:5,category:"3D",winnerId:4},{id:6,category:"New Media",winnerId:23},{id:7,category:"People's Choice",winnerId:24},{id:8,category:"Highly commended"}]};app.models.Winner=Ext.regModel("app.models.Winner",{fields:[{name:"id",type:"int"},{name:"category",type:"string"},{name:"winnerId",type:"int"}]});
app.stores.winners=new Ext.data.Store({model:"app.models.Winner",sorters:"id",data:winnersData,proxy:{type:"memory",reader:{type:"json",root:"winners"}}});
