
 
    var deviceOS = "Android";
    var versionAppHosturi = "http://www.monorientationenligne.fr/qr/app/json/versionApp.json";
    var messageAppHosturi = "http://www.monorientationenligne.fr/qr/app/json/messageApp.json";
    var serviceOpenAppHosturi = "http://www.monorientationenligne.fr/qr/app/json/closeMailApp.json"; 
            var urlStore = "market://details?id=fr.onisep.moel";
	var version = "1.4";	
	    
	var idGA = "UA-16981700-1"; 
	var _gaq = _gaq || []; 

window.addEventListener('load', function () { new FastClick(document.body); }, false);










       OELChatSession.setEndPoint("http://www.monorientationenligne.fr/qr/chat/");
    

       OELMailForm.setEndPoint("http://www.monorientationenligne.fr/qr/sendmailapplimoel.php");
    

       OELGeolocView.setEndPoint("http://onigeo.monorientationenligne.fr/onigeo/");
    

// Compilation date : 2014-07-11-10-32-49
var OELLogger=function(){this.debugMode=!1;return{init:function(a){debugMode=a},log:function(a){debugMode&&console.log(a)}}}();

var OELisNotTransitionAware=!1,OELScroll=[],OELCurrentScroll=null,OELScrollConfig={hScroll:!1,vScroll:!0,hScrollbar:!1,vScrollbar:!0,fixedScrollbar:!0,fadeScrollbar:!1,hideScrollbar:!0,bounce:!0,momentum:!1,lockDirection:!0,onBeforeScrollStart:function(a){for(var b=a.target;1!=b.nodeType;)b=b.parentNode;"SELECT"!=b.tagName&&("INPUT"!=b.tagName&&"TEXTAREA"!=b.tagName)&&a.preventDefault()}},scrollInput,osTimeOut=0,wpScreen={portraitHeight:0,landscapeHeight:0},footerHandler=function(a,b){"chat-dialog"!=
a.attr("id")&&$(".ui-footer",a).css("display",b);"Android"!=deviceOS&&"windows-phone-8"!=deviceOS&&iScrollAdjust(a.attr("id")+"-content-page")};function keyboardScroll(a){var b=$("#container .ui-page-active .oel-page-content").attr("id");a.parents(".ui-footer").length||(b=OELScroll[b],b.scrollToElement("#"+$(a).attr("id"),0))}
var iScrollAdjust=function(a,b){OELCurrentScroll=a;var c=$("#"+a),d=$(".content-scroll:eq(0)",c);a in OELScroll?setTimeout(function(){if(b){var e=$("#container .ui-page-active");c.height($(window).innerHeight()-parseInt(e.css("padding-top"))-parseInt($(".ui-dialog-contain:eq(0)",e).css("margin-top")));d.height("auto");d.css("height",d.innerHeight())}else{var e=c.parent(),g=$(".ui-header",e),f=$(".ui-footer:visible",e);c.height("auto");d.height("auto");var h=$.mobile.media("screen and (orientation:portrait)");
if("chat-dialog-content-page"==a){var k=$("#incomingMessages",d);h&&0<$("#index-content-scroll .ui-footer").size()&&$("#index").append($("#index-content-scroll .ui-footer"));f.length?c.height($(window).innerHeight()-g.innerHeight()-f.innerHeight()):c.height($(window).innerHeight()-g.innerHeight());d.css("height",k.innerHeight()+parseInt(e.css("padding-top"))+parseInt(e.css("padding-bottom")));d.css("min-height",c.height())}else"index-content-page"!=a||h?(h&&0<$("#index-content-scroll .ui-footer").size()&&
$("#index").append($("#index-content-scroll .ui-footer")),"index-content-page"==a?c.height($(window).innerHeight()):f.length?c.height($(window).innerHeight()-g.innerHeight()-f.innerHeight()):c.height($(window).innerHeight()-g.innerHeight()),d.css("height",d.innerHeight()+parseInt(e.css("padding-top"))+parseInt(e.css("padding-bottom"))),d.css("min-height",c.height())):(f&&$("#index-content-scroll").append(f),c.height($(window).innerHeight()-g.innerHeight()),f.length?d.css("height",d.innerHeight()+
f.innerHeight()):d.css("height",d.innerHeight()));0==parseInt(e.css("padding-top"))&&e.css("padding-top",parseInt(g.outerHeight())+"px")}OELScroll[OELCurrentScroll].refresh()},500):0==parseInt(c.parent().css("padding-top"))&&c.parent().css("padding-top",parseInt($(".ui-header",c.parent()).outerHeight())+"px")};function exitAppMoel(a){1==a&&navigator.app.exitApp()}
$(document).on("mobileinit",function(){/Android\s([0-9\.]+)/.exec(navigator.userAgent)&&(OELisNotTransitionAware=!0,$.mobile.phonegapNavigationEnabled=!1,$.mobile.transitionFallbacks.fade="none",$.mobile.transitionFallbacks.slidedown="none",$.mobile.transitionFallbacks.slideup="none",$.mobile.transitionFallbacks.pop="none");$.mobile.allowCrossDomainPages=!0;$.mobile.page.prototype.options.domCache=!0;$.mobile.defaultPageTransition="none";$.mobile.pushStateEnabled=!0;$.mobile.hashListeningEnabled=
!0;$.mobile.ajaxEnabled=!0;"Android"!=deviceOS&&"windows-phone-8"!=deviceOS&&($.mobile.pageContainer=$("#container"));$(document).on("deviceready",function(){navigator.splashscreen.hide();"windows-phone-8"==deviceOS&&(osTimeOut=500);$("#messageText").keyup(function(b){if("Android"!=deviceOS&&"windows-phone-8"!=deviceOS){b=$("#chat-dialog-content-page");var c=b.parent(),a=$(".content-scroll:eq(0)",b);OELCurrentScroll="chat-dialog-content-page";var e=$(".ui-header",c),g=$(".ui-footer:visible",c);b.height("auto");
a.height("auto");var f=$.mobile.media("screen and (orientation:portrait)"),h=$("#incomingMessages",a);f&&0<$("#index-content-scroll .ui-footer").size()&&$("#index").append($("#index-content-scroll .ui-footer"));g.length?b.height($(window).innerHeight()-e.innerHeight()-g.innerHeight()):b.height($(window).innerHeight()-e.innerHeight());a.css("height",h.innerHeight()+parseInt(c.css("padding-top"))+parseInt(c.css("padding-bottom")));a.css("min-height",b.height());0==parseInt(c.css("padding-top"))&&c.css("padding-top",
parseInt(e.outerHeight())+"px");OELScroll[OELCurrentScroll].refresh()}});document.addEventListener("backbutton",function(){if("chat-dialog"==$.mobile.activePage.attr("id"))return!1;"index"===$.mobile.activePage.attr("id")?navigator.notification.confirm("Vous allez quitter l\u2019application. Voulez-vous continuer ?",exitAppMoel,"Mon Orientation en ligne","OK,Annuler"):navigator.app.backHistory()},!1);document.addEventListener("showkeyboard",function(b){footerHandler($.mobile.activePage,"none");"Android"!=
deviceOS&&"windows-phone-8"!=deviceOS&&(window.scrollTo(0,0),keyboardScroll(scrollInput))},!0);document.addEventListener("hidekeyboard",function(b){footerHandler($.mobile.activePage,"block")},!0);$("input[type=text], textarea").bind("blur",function(b){setTimeout(function(){footerHandler($.mobile.activePage,"block");"Android"!=deviceOS&&"windows-phone-8"!=deviceOS&&$("body,#container").height(screen.availHeight)},osTimeOut)});"windows-phone-8"==deviceOS?$("input[type=text], textarea").bind("click",
function(b){setTimeout(function(){footerHandler($.mobile.activePage,"none");$.mobile.media("screen and (orientation:portrait)")?wpScreen.portraitHeight=$(window).height():wpScreen.landscapeHeight=$(window).height()},osTimeOut);$(this).trigger("focus")}):$("input[type=text], textarea").bind("focus",function(b){footerHandler($.mobile.activePage,"none");"Android"!=deviceOS&&"windows-phone-8"!=deviceOS&&(window.scrollTo(0,0),scrollInput=$(this))});document.addEventListener("offline",function(b){OELGeoloc.checkConnection()},
!1);document.addEventListener("online",function(b){OELGeoloc.checkConnection()},!1);try{$.preload.images(),OELAddressBook.init(),OELGeoloc.refreshCurrentPosition()}catch(a){OELLogger.log("hello"),OELLogger.log(a.message)}"Android"==deviceOS&&window.plugins.analytics.start(function(){OELLogger.log("Start: success");_pushGaq("index-content-page")},function(){OELLogger.log("Start: failure")});"iOS"==deviceOS&&(window.GA.trackerWithTrackingId(idGA),_pushGaq("index-content-page"));$(document).delegate('[data-role="page"]',
"pageshow",function(){var b=$(this).find(".oel-page-content")[0],a=$("#"+b.id),a=a.parent(),d=$(".ui-header",a);a.css("padding-top",parseInt(d.outerHeight())+"px");"Android"!=deviceOS&&"windows-phone-8"!=deviceOS&&b.id in OELScroll?iScrollAdjust(b.id):"geo-map-content-page"==b.id&&(a=$("#"+b.id),0==parseInt(a.parent().css("padding-top"))&&a.parent().css("padding-top",parseInt($(".ui-header",a.parent()).outerHeight())+1+"px"));_pushGaq(b.id)});$(document).delegate('[data-role="dialog"]',"pageshow",
function(){var a=$(this).find(".oel-custom-page-content")[0];"Android"!=deviceOS&&("windows-phone-8"!=deviceOS&&a.id in OELScroll)&&iScrollAdjust(a.id,!0);_pushGaq(a.id)})});$(document).on("resume",function(){try{OELGeoloc.refreshCurrentPosition(),OELGeoloc.checkConnection(),OELGeoloc.checkServiceOpen(),OELGeoloc.checkVersionApp()}catch(a){OELLogger.log(a.message)}})});
function _pushGaq(a){"Android"!=deviceOS&&"iOS"!=deviceOS?(ga_storage._setAccount(idGA),ga_storage._trackPageview(a),ga_storage._setCustomVar(1,"OsVersion",deviceOS)):("Android"==deviceOS&&window.plugins.analytics.trackPageView(a,function(){OELLogger.log("Start: success page "+a)},function(){OELLogger.log("Start: failure page"+a)}),"iOS"==deviceOS&&window.GA.trackView(a))}$("#geo").on("pageinit",function(){$("#geo .geo-page-container .aroundme").listview("refresh")});
$(function(){OELLogger.init(!0);if("Android"!=deviceOS&&"windows-phone-8"!=deviceOS){var a="geo-map-content-page chat-logout-content-page chat-auto-logout-content-page chat-offline-content-page mail-offline-content-page geo-offline-content-page phone-contact-content-page".split(" ");$(".oel-page-content").each(function(){-1==a.indexOf(this.id)&&(OELScroll[this.id]=new iScroll(this.id,OELScrollConfig))});for(var b,c=1;c<a.length;c++)b="custom-"+a[c],OELScroll[b]=new iScroll(b,OELScrollConfig)}$(".icon-close a, .tabbar-link a, a.link-home, .icon-infos a, #home-page-link a, a.reload-geoloc, .infosHome a, a.link-map, a.link-list, #gochat, #mail-form-valid, .link-return, .geo-map-bureau").on("tap",
function(a){$(this).attr("href")!="#"+$(".ui-page-active").attr("id")&&$.mobile.loading("show",{text:"Chargement en cours...",textVisible:!0})})});

$(function(){try{($.mobile.media("screen and (min-width: 768px) and (orientation:portrait)")||$.mobile.media("screen and (-webkit-min-width: 768px) and (orientation:portrait)")||$.mobile.media("screen and (min-width: 1024px) and (orientation:landscape)")||$.mobile.media("screen and (-webkit-min-width: 1024px) and (orientation:landscape)"))&&$("#index img").each(function(a,b){if($(b).attr("src")&&!/(.+)(Tablette\.\w{3,4})/.test($(b).attr("src"))){var c=$(b).attr("src").replace(/(.+)(\.\w{3,4})$/,"$1Tablette$2");
$(b).attr("src",c).attr("width","auto").attr("height","auto")}});1.5<=window.devicePixelRatio&&($("body").addClass("retina"),$("img").each(function(a,b){if($(b).attr("src")&&!/(.+)(2x\.\w{3,4})/.test($(b).attr("src"))){var c=$(b).attr("src").replace(/(.+)(\.\w{3,4})$/,"$12x$2");OELLogger.log("on change: "+c);$(b).attr("src",c)}}));var e=function(){if("Android"!=deviceOS&&"windows-phone-8"!=deviceOS){var a=$(document).height();$("#container").height(a);$("body").height(a)}},d=function(a){$("#index [data-role=footer]").fixedtoolbar(a);
e()};$(window).on("orientationchange",function(a){$.mobile.media("screen and (orientation:landscape)")?d("hide"):d("show");"Android"!=deviceOS&&"windows-phone-8"!=deviceOS&&(a=$("#container .ui-page-active"),a.hasClass("ui-dialog")?iScrollAdjust($(".oel-custom-page-content",a).attr("id"),!0):iScrollAdjust($(".oel-page-content",a).attr("id")))});$(window).on("resize",function(a){"windows-phone-8"==deviceOS&&($.mobile.media("screen and (orientation:portrait)")?$(window).height()>=wpScreen.portraitHeight&&
footerHandler($.mobile.activePage,"block"):$(window).height()>=wpScreen.landscapeHeight&&footerHandler($.mobile.activePage,"block"))});$(document).bind("pageshow",function(a,b){e();"index"==a.target.id&&$.mobile.media("screen and (orientation:landscape)")?d("hide"):"geo"==a.target.id&&$("#geo .geo-page-container .aroundme").listview("refresh")})}catch(f){OELLogger.log(f.message)}$(document).on("deviceready",function(){try{OELChatSession.init()}catch(a){OELLogger.log("OELChatSession init: "+a.message)}try{OELMailForm.init()}catch(b){OELLogger.log("OELMailForm init: "+
b.message)}try{OELGeoloc.init()}catch(c){OELLogger.log("OELGeoloc init: "+c.message)}try{OELGeolocView.init()}catch(d){OELLogger.log("OELGeolocView init: "+d.message)}});window.addEventListener("message",OELGeolocView.handleIframeResponse,!1)});


// Compilation date : 2014-07-11-10-32-49
var OELGeoloc=function(){function m(){$.mobile.loading("hide");$(".button-manuel").css("display","block");$(".infos").css("display","block");$(".manuel").css("display","none");"Android"==deviceOS&&$(".manuel .selectMenus").css("display","none");$("#geo-manuel-valide").css("display","none")}function f(){$.mobile.loading("hide");$(".button-manuel").css("display","none");$(".button-manuel").removeClass("validateBtn");$(".parent_infos").removeClass("manual_open");$(".infos").css("display","none");$(".manuel").css("display",
"block");"Android"==deviceOS&&$(".manuel .selectMenus").css("display","block");$(".manuel").removeClass("manual_selected");$(".aroundme").css("display","none");$("#geo-manuel-valide").css("display","block")}function n(){var d=!0,c=(new Date).getTime();$.ajax({url:serviceOpenAppHosturi,dataType:"json",async:!1,cache:!1,success:function(a){var b=""!=$.trim(a.StartDate)?Date.parse(a.StartDate):Date.parse("1970/01/01"),g=""!=$.trim(a.EndDate)?Date.parse(a.EndDate):Date.parse("1970/01/01");a=$.trim(a.content);
d=c>b&&c<g&&a?a:!0},fail:function(){d=!0}});return serviceState=d}function p(){$.ajax({url:versionAppHosturi,dataType:"json",async:!1,cache:!1,success:function(d){var c=d["version"+deviceOS],a=$.trim(d.titleApp),b=$.trim(d.contentApp);d=$.trim(d.buttonNameApp);c>version?b&&(a&&d)&&navigator.notification.alert(b,v,a,d):w()}})}function v(){window.open(encodeURI(urlStore),"_system")}function w(){var d=(new Date).getTime();$.ajax({url:messageAppHosturi,dataType:"json",async:!1,cache:!1,success:function(c){var a=
$.trim(c.title),b=$.trim(c.content),g=$.trim(c.buttons),q=$.trim(c.button),f=$.trim(c.url),e=""!=$.trim(c.StartDate)?Date.parse(c.StartDate):Date.parse("1970/01/01");c=""!=$.trim(c.EndDate)?Date.parse(c.EndDate):Date.parse("1970/01/01");d>e&&d<c&&a&&b&&f&&a&&g?navigator.notification.confirm(b,x,a,g):d>e&&(d<c&&b&&a&&q)&&navigator.notification.alert(b,null,a,q)}})}function x(d){2===d&&$.ajax({url:messageAppHosturi,dataType:"json",async:!1,cache:!1,success:function(c){(c=$.trim(c.url))&&window.open(encodeURI(c),
"_blank")}})}function r(){if("windows-8"==deviceOS){var d=Windows.Devices.Geolocation.Geolocator();d.desiredAccuracy=Windows.Devices.Geolocation.PositionAccuracy.high;d.getGeopositionAsync().then(function(c){userPosition.position={coords:{latitude:c.coordinate.latitude,longitude:c.coordinate.longitude}};$.ajax({url:"http://maps.googleapis.com/maps/api/geocode/json?latlng="+userPosition.position.coords.latitude+","+userPosition.position.coords.longitude+"&sensor=false",type:"GET",timeout:28E3,dataType:"json",
success:function(a){try{var b=a.results[0];userPosition.address.formatted=b.formatted_address;var c=b.address_components.length;for(a=0;a<c;a++){var d=b.address_components[a];userPosition.address[d.types[0]]=d.short_name}h();k();OELGeolocView.resizeMapContainer()}catch(e){OELLogger.log(e.message)}},error:function(){e();f()}}).fail(function(){e();f()})},function(){e();f()})}else navigator.geolocation.getCurrentPosition(function(c){userPosition.position=c;$.ajax({url:"http://maps.googleapis.com/maps/api/geocode/json?latlng="+
userPosition.position.coords.latitude+","+userPosition.position.coords.longitude+"&sensor=false",type:"GET",timeout:28E3,dataType:"json",success:function(a){try{var b=a.results[0];userPosition.address.formatted=b.formatted_address;var c=b.address_components.length;for(a=0;a<c;a++){var d=b.address_components[a];userPosition.address[d.types[0]]=d.short_name}h();k();OELGeolocView.resizeMapContainer()}catch(e){OELLogger.log(e.message)}},error:function(){e();f()}}).fail(function(){e();f()})},function(c){e();
f();OELLogger.log("code: "+c.code+"\nmessage: "+c.message+"\n")},{timeout:3E4,enableHighAccuracy:!0})}function l(){return isConnected=!(0==navigator.connection.type||navigator.connection.type==Connection.NONE)}function h(){var d=s(),c=t(),a=$("#select_departement_chat_id, #select_departement_mail_id"),b=$("#select_country_chat_id, #select_country_mail_id");if("999"==d)f();else{m();try{a.val(d).selectmenu("refresh",!0),b.val(c).selectmenu("refresh",!0)}catch(e){}u($("div.manuel"),!0);OELGeolocView.clearMarkers();
OELGeolocView.autourdemoi(!1)}}function u(d,c){d.each(function(a,b){acceptGeo=!0;$(".localization .automatic").addClass("activeGeo");$(b).find("select[name='select_departement']").length?"FR"!=$(b).find("select[name='select_country'] option:selected").val()?($(b).parent().find(".infos .departement").text($(b).find("select[name='select_country'] option:selected").text()),$(b).parent().find(".infos .country").text(""),$(".geo-page-container .infos .departement").text(userPosition.address.locality)):
($(b).parent().find(".infos .departement").text($(b).find("select[name='select_departement'] option:selected").text()),$(b).parent().find(".infos .country").text($(b).find("select[name='select_country'] option:selected").text()),$(".geo-page-container .infos .departement").text(userPosition.address.locality+" "+(userPosition.address.administrative_area_level_2?userPosition.address.administrative_area_level_2:""))):!0==c?"FR"!=$(".chat-form .manuel").find("select[name='select_country'] option:selected").val()?
($(b).parent().find(".infos .departement").text($(".chat-form .manuel").find("select[name='select_country'] option:selected").text()),$(b).parent().find(".infos .country").text(""),$(".geo-page-container .infos .departement").text(userPosition.address.locality)):($(b).parent().find(".infos .departement").text($(".chat-form .manuel").find("select[name='select_departement'] option:selected").text()),$(b).parent().find(".infos .country").text($(".chat-form .manuel").find("select[name='select_country'] option:selected").text()),
$(".geo-page-container .infos .departement").text(userPosition.address.locality+" "+(userPosition.address.administrative_area_level_2?userPosition.address.administrative_area_level_2:""))):($(b).parent().find(".infos .departement").text($(b).find("#city_zipCode").val()),$(b).parent().find(".infos .country").text(""),OELGeolocView.refreshBureaux());$(b).parent().find(".infos").css("display","block");$(b).slideUp();$(b).parent().find(".button-manuel").css("display","block")})}function e(){l()||$(".link-map").css("display",
"none")}function k(){l()&&$(".link-map").css("display","inline-block")}function t(){return userPosition.address.country}function s(){return matchingDROM[userPosition.address.country]?matchingDROM[userPosition.address.country]:"FR"==userPosition.address.country?userPosition.address.administrative_area_level_2:"999"}this.userPosition={position:null,address:{formatted:null,street_number:null,route:null,neighborhood:null,sublocality:null,locality:null,administrative_area_level_2:null,administrative_area_level_1:null,
country:null,postal_code:null}};this.matchingDROM={};this.isConnected=this.acceptGeo=!1;this.serviceState=!0;return{init:function(){$("#geo-manuel-valide").css("display","none");e();l();n();p();$(".geo-page-container .aroundme").css("display","none");if("windows-8"==deviceOS){var d=Windows.Devices.Geolocation.Geolocator();d.desiredAccuracy=Windows.Devices.Geolocation.PositionAccuracy.high;d.getGeopositionAsync().then(function(a){userPosition.position={coords:{latitude:a.coordinate.latitude,longitude:a.coordinate.longitude}};
$.mobile.loading("show",{text:"Chargement en cours...",textVisible:!0});$.ajax({url:"http://maps.googleapis.com/maps/api/geocode/json?latlng="+userPosition.position.coords.latitude+","+userPosition.position.coords.longitude+"&sensor=false",type:"GET",dataType:"json",timeout:28E3,success:function(b){try{var a=b.results[0];userPosition.address.formatted=a.formatted_address;var c=a.address_components.length;for(b=0;b<c;b++){var d=a.address_components[b];userPosition.address[d.types[0]]=d.short_name}h();
k();m();OELGeolocView.resizeMapContainer()}catch(e){OELLogger.log(e.message)}},error:function(b,a,c){e();f()}}).fail(function(){e();f()})},function(){e();f()})}else navigator.geolocation.getCurrentPosition(function(a){userPosition.position=a;$.mobile.loading("show",{text:"Chargement en cours...",textVisible:!0});$.ajax({url:"http://maps.googleapis.com/maps/api/geocode/json?latlng="+userPosition.position.coords.latitude+","+userPosition.position.coords.longitude+"&sensor=false",type:"GET",dataType:"json",
timeout:28E3,success:function(b){try{var a=b.results[0];userPosition.address.formatted=a.formatted_address;var c=a.address_components.length;for(b=0;b<c;b++){var d=a.address_components[b];userPosition.address[d.types[0]]=d.short_name}h();k();OELGeolocView.resizeMapContainer()}catch(e){OELLogger.log(e.message)}},error:function(a,c,d){e();f()}}).fail(function(){e();f()})},function(a){e();f();OELLogger.log("code: "+a.code+"\nmessage: "+a.message+"\n")},{timeout:3E4,enableHighAccuracy:!0});matchingDROM.GP=
"971";matchingDROM.MQ="972";matchingDROM.GF="973";matchingDROM.RE="974";matchingDROM.PM="975";matchingDROM.YT="976";matchingDROM.TF="984";matchingDROM.WF="986";matchingDROM.PF="987";matchingDROM.NC="988";try{$(".button-manuel a").click(function(){var a=$(this).parents("div.automatic"),b=$(this).parents(".localization").find(".selectMenus");a.find(".parent_infos").hasClass("manual_open")?(a.find(".parent_infos").removeClass("manual_open"),a.find(".manuel").removeClass("manual_selected"),a=$(this).data("text"),
$(this).data("text",$("span",this).html()),$("span",this).html(a),"Android"==deviceOS&&b.css("display","none"),$(this).parent().siblings("div.manuel").slideUp(500),$(this).parents(".button-manuel").removeClass("validateBtn"),u($(this).parent().siblings("div.manuel"),!1)):(a.find(".parent_infos").addClass("manual_open"),a.find(".manuel").addClass("manual_selected"),a=$(this).data("text"),$(this).data("text",$("span",this).html()),$("span",this).html(a),$(this).parent().siblings("div.manuel").slideDown(300,
function(){"Android"==deviceOS&&b.css("display","block")}),$(this).parents(".button-manuel").addClass("validateBtn"));"Android"!=deviceOS&&"windows-phone-8"!=deviceOS&&iScrollAdjust($.mobile.activePage.attr("id")+"-content-page");return!1})}catch(c){OELLogger.log(c.message)}$(".mail a, .navbar_mail a").click(function(){if(isConnected){if(!0!=serviceState)return $(".serviceout-page-container").find("p").text(serviceState.toString().replace('"',"")),$.mobile.changePage("#mail-serviceout",{transition:"pop",
role:"dialog"}),!1}else return $.mobile.changePage("#mail-offline",{transition:"pop",role:"dialog"}),!1});$(".chat a, .navbar_chat a").click(function(){if(!isConnected)return $.mobile.changePage("#chat-offline",{transition:"pop",role:"dialog"}),!1});$(".geoloc a, .navbar_geo a").click(function(){if(!isConnected)return $.mobile.changePage("#geo-offline",{transition:"pop",role:"dialog"}),!1});$(".phone a").click(function(){if(!isConnected)return window.location.href="#phone-no-connection",!1});$(".reload-geoloc").click(function(){r()})},
getCountry:t,getDepartement:s,getPostalCode:function(){return userPosition.address.postal_code},getPosition:function(){return userPosition.position},checkConnection:l,refreshCurrentPosition:r,checkServiceOpen:n,checkVersionApp:p}}();

var OELChatSession=function(){function m(){for(var a=document.cookie.split(";"),b=0;b<a.length;b++){var c=a[b],d=c.indexOf("="),c=-1<d?c.substr(0,d):c;document.cookie=c+"=;expires=Thu, 01 Jan 1970 00:00:00 GMT"}}function g(a){OELLogger.log(a.url+" ["+a.data+"] ("+a.type+")");$.ajax({url:a.url,type:a.type,dataType:"xml",data:a.data,success:a.success})}function n(a){$(a).find("infos>info").each(function(){var a="Type:"+$(this).attr("type")+" = "+$(this).text();OELLogger.log(a)})}function k(a){var b=
"";$(".msgContainerDiv > .message").not(".pending").each(function(){contentMessage=$(this).find(".message-content").html();contentMessage=$(this).hasClass("oel")?"monorientationenligne : "+contentMessage:"moi : "+contentMessage;b+="("+$(this).find(".time").html()+") "+contentMessage;b+="\n"});return b}function l(a){var b=!1,c="",d="",f="";if(null!=a){if(d=a.find(">username").text(),f=a.find(">text").text(),f=f.replace("\n","<br />"),"oel"==d||"(oel)"==d||"monorientationenligne"==d||"monorientationenligne.fr"==
d)c="oel",b=!0}else c="oel suspenssion",b=!0,f="...";a=$(".suspenssion");a.length&&a.remove();!0==b&&(d=new Date,b=d.getHours(),a=d.getMinutes(),d=d.getSeconds(),10>b&&(b="0"+b.toString()),10>a&&(a="0"+a.toString()),10>d&&(d="0"+d.toString()),$(".msgContainerDiv").append('<div class="message '+c+'" id="'+lastID+'"><em class="time">'+b+":"+a+":"+d+'</em><p class="message-content '+c+'">'+f+'</p></div><div class="clear"></div>').animate({scrollTop:$(document).height()},1E3),"Android"!=deviceOS&&"windows-phone-8"!=
deviceOS&&iScrollAdjust($.mobile.activePage.attr("id")+"-content-page"),c="#"+$.mobile.activePage.attr("id")+"-content-page",c=$(c).innerHeight(),f=$("#incomingMessages",$.mobile.activePage.find(".content-scroll")).innerHeight(),"Android"!=deviceOS&&"windows-phone-8"!=deviceOS&&c<f?OELScroll[$.mobile.activePage.attr("id")+"-content-page"].scrollToElement("#incomingMessages div:last-child"):$("html, body").animate({scrollTop:$("#incomingMessages div:last-child").offset().top-parseInt($("#chat-dialog").css("padding-top"))},
500),clearTimeout(scheduleTimeout),scheduleTimeout=null,scheduleTimeout=setTimeout(OELChatSession.timeoutLogout,18E4))}function h(){stopTimer=!0;loggedIn=!1;clearTimeout(scheduleNewMessage);clearTimeout(scheduleState);null!=scheduleTimeout&&(clearTimeout(scheduleTimeout),scheduleTimeout=null);m();g({type:"POST",url:chatSocketServer+"?ajax=true&lastID="+lastID,data:{logout:!0}});return!1}function r(a){$(a).find("root>infos info").each(function(){var a=$(this).attr("type"),c=$(this).text();switch(a){case "userID":user.id=
c;break;case "userName":user.pseudo=c;break;case "userRole":user.roleID=c;break;case "channelID":user.channelID=c;break;case "channelName":user.channelName=c}})}function s(){stopTimer=!1;var a=function(){g({url:chatSocketServer+"?ajax=true&getInfos=userID,userName,userRole,channelID,channelName&login=login&channelName=d"+user.dept+"&sexe="+user.sexe+"&source="+user.source+"&evenement=&userName="+user.name,type:"GET",success:function(a,b){r(a);p();q();loggedIn=!0;n(a)}})};!0==loggedIn?t(a):a();var b=
new Date,a=b.getHours(),c=b.getMinutes(),b=b.getSeconds();10>a&&(a="0"+a.toString());10>c&&(c="0"+c.toString());10>b&&(b="0"+b.toString());$(".msgContainerDiv").append('<div class="message oel"><em class="time">'+a+":"+c+":"+b+'</em><p class="message-content oel">Bonjour, veuillez patienter...</p></div><div class="clear"></div>');scheduleTimeout=setTimeout(OELChatSession.timeoutLogout,18E4)}function t(a){loggedIn=!1;m();g({url:chatSocketServer+"?ajax=true",type:"POST",data:{logout:!0},success:a})}
function p(){g({type:"GET",url:chatSocketServer+"?ajax=true&lastID="+lastID+"&activity="+state,success:function(a,b){1==$(a).find("infos>info").attr("type","activity").text()?l(null):$(a).find("messages>message").each(function(){lastID=$(this).attr("id");l($(this))});!1==stopTimer&&(scheduleNewMessage=setTimeout(OELChatSession.fetchNewMessages,1E3))}})}function q(){var a=$("#messageText").val().trim();a!=lastMessageValue?(lastMessageValue=a,state="editing"):state=0<a.length?"edited":"none";!1==stopTimer&&
(scheduleState=setTimeout(OELChatSession.updateState,1E3))}this.chatSocketServer=null;this.user={id:0,name:"Anonymous",pseudo:"",roleID:0,channelID:0,channelName:"",sexe:"M",dept:"999",source:"applimoel"};this.loggedIn=!1;this.state="none";this.lastMessageValue=null;this.lastID=0;this.scheduleTimeout=this.scheduleState=this.scheduleNewMessage=null;this.stopTimer=!1;this.error=null;return{init:function(){OELLogger.log("Init chat Session");$("#gochat").click(function(){var a=$("input[name=chat-genre]:checked"),
b=$("#select_country_chat_id").val(),c=$("#select_departement_chat_id").val(),d="";0==a.length&&(d+="Vous devez obligatoirement choisir votre genre\n");""==b&&(d+="Vous devez obligatoirement choisir votre pays\n");!c&&"FR"==b&&(d+="Vous devez obligatoirement choisir votre d\u00e9partement\n");error=d;if(""!=d)return $.mobile.loading("hide"),navigator.notification.alert(error,null,"Message"),!1;$.mobile.loading("hide");$("#messageText").val("");$(".msgContainerDiv").html("");OELChatSession.startChat(((new Date).getTime()+
device.uuid).toString(16),$("#select_departement_chat_id").val(),$("input[name=chat-genre]:checked").val());$(".mode-register:checked").attr("checked",!1).checkboxradio("refresh")});$("#send-message").click(function(){var a=$("#messageText").val().trim();$("#messageText").val("");OELLogger.log(a);OELGeoloc.checkConnection()?g({url:chatSocketServer+"?ajax=true&lastID="+lastID,type:"POST",data:{lastID:lastID,text:a},success:function(a,c){$(a).find("messages>message").each(function(){var a=$(this),b=
a.find(">username").text(),c=a.find(">text").text(),c=c.replace("\n","<br />");if("oel"==b||"(oel)"==b||"monorientationenligne"==b||"monorientationenligne.fr"==b)l(a);else{var e=new Date,a=e.getHours(),b=e.getMinutes(),e=e.getSeconds();10>a&&(a="0"+a.toString());10>b&&(b="0"+b.toString());10>e&&(e="0"+e.toString());$(".msgContainerDiv").append('<div class="message "><em class="time">'+a+":"+b+":"+e+'</em><p class="message-content ">'+c+'</p></div><div class="clear"></div>').animate({scrollTop:$(document).height()},
1E3);"Android"!=deviceOS&&"windows-phone-8"!=deviceOS?(iScrollAdjust($.mobile.activePage.attr("id")+"-content-page"),OELScroll[$.mobile.activePage.attr("id")+"-content-page"].scrollToElement("#incomingMessages div:last-child")):$("html, body").animate({scrollTop:$("#incomingMessages div:last-child").offset().top-parseInt($("#chat-dialog").css("padding-top"))},500)}lastID=$(this).attr("id")});n(a);clearTimeout(scheduleTimeout);scheduleTimeout=null;scheduleTimeout=setTimeout(OELChatSession.timeoutLogout,
18E4)}}):$.mobile.changePage("#chat-offline",{transition:"pop",role:"dialog"});return!1});$(".chat-form form").submit(function(){return!1});$("#select_country_chat_id").change(function(){"FR"!=$(this).val()?$(".chat-page-container #select_departement_chat_id").parents("p").css("display","none"):$(".chat-page-container #select_departement_chat_id").parents("p").css("display","block")});$("#chat-disconnect-sms, #chat-auto-disconnect-sms").click(function(){h();if("iOS"==deviceOS||"windows-phone-8"==
deviceOS)"iOS"==deviceOS&&window.GA.trackEventWithCategory("Tchat","Clic","sms",1,null,null),window.plugins.smsComposer.showSMSComposer("",k(deviceOS));else{$.mobile.showPageLoadingMsg();$(".chat-disconnect-withoutsave,#chat-disconnect-mail, #chat-auto-disconnect-mail, .nein").addClass("ui-disabled");"Android"==deviceOS&&window.plugins.analytics.trackEvent("Tchat","Clic","sms",1,null,null);var a=$(this).parent().find(".sms-composer").attr("href").replace("text_body_content",k());$(".sms-composer").each(function(){$(this).attr("href",
a)});setTimeout(OELChatSession.executeSMS,2E3)}null!=scheduleTimeout&&(clearTimeout(scheduleTimeout),scheduleTimeout=null)});$("#chat-disconnect-mail, #chat-auto-disconnect-mail").click(function(){$.mobile.showPageLoadingMsg();$(".chat-disconnect-withoutsave,#chat-disconnect-sms, #chat-auto-disconnect-sms, .nein").addClass("ui-disabled");"Android"==deviceOS&&window.plugins.analytics.trackEvent("Tchat","Clic","mail",1,null,null);"iOS"==deviceOS&&window.GA.trackEventWithCategory("Tchat","Clic","mail",
1,null,null);h();var a=$(this).parent().find(".mail-composer").attr("href").replace("text_body_content",k());$(".mail-composer").each(function(){$(this).attr("href",a)});setTimeout(OELChatSession.executeMail,2E3);null!=scheduleTimeout&&(clearTimeout(scheduleTimeout),scheduleTimeout=null)});$(".chat-disconnect-withoutsave").click(function(){"Android"==deviceOS&&window.plugins.analytics.trackEvent("Tchat","Clic","withoutsave",1,null,null);"iOS"==deviceOS&&window.GA.trackEventWithCategory("Tchat","Clic",
"withoutsave",1,null,null);h();null!=scheduleTimeout&&(clearTimeout(scheduleTimeout),scheduleTimeout=null)})},updateState:q,startChat:function(a,b,c){a!=user.name&&(user.name=a,b&&"FR"==$("#select_country_chat_id").val()&&(user.dept=b),c&&(user.sexe=c));s()},fetchNewMessages:p,setEndPoint:function(a){chatSocketServer=a},executeMail:function(){var a=$(".mail-composer").attr("href");$(".mail-composer").each(function(){$(this).attr("href","mailto:?subject=[mon orientation en ligne] Conversation avec un conseiller&body=text_body_content")});
$(".chat-disconnect-withoutsave, #chat-disconnect-mail, #chat-auto-disconnect-mail, #chat-disconnect-sms, #chat-auto-disconnect-sms, .nein").removeClass("ui-disabled");window.open(encodeURI(a),"_system")},executeSMS:function(){var a=$(".sms-composer").attr("href");$(".sms-composer").each(function(){$(this).attr("href","sms:?body=text_body_content")});$(".chat-disconnect-withoutsave, #chat-disconnect-mail, #chat-auto-disconnect-mail, #chat-disconnect-sms, #chat-auto-disconnect-sms, .nein").removeClass("ui-disabled");
window.open(encodeURI(a),"_system")},timeoutLogout:function(){$.mobile.changePage("#chat-auto-logout",{transition:"pop",role:"dialog"});h()}}}();

var OELAddressBook=function(){function f(b){if(0==b.length){b=[];var a=[];a[0]=new ContactField("work","+0177771225",!1);b[0]=navigator.contacts.create({displayName:"ONISEP M\u00e9tropole",note:"T\u00e9l\u00e9phone ONISEP pour le service M\u00e9tropole",phoneNumbers:a});a=new ContactName;a.givenName="ONISEP M\u00e9tropole";b[0].name=a;b[0].save();navigator.notification.alert("Les coordonn\u00e9es t\u00e9l\u00e9phoniques de ONISEP M\u00e9tropole ont \u00e9t\u00e9 ajout\u00e9es \u00e0 vos contacts",
null,"Message")}else return navigator.notification.alert("Le Contact ONISEP M\u00e9tropole est d\u00e9j\u00e0 enregistr\u00e9",null,"Message"),!1}function g(b){if(0==b.length){b=[];var a=[];a[0]=new ContactField("work","+0596531225",!1);b[0]=navigator.contacts.create({displayName:"ONISEP Antilles-Guyane",note:"T\u00e9l\u00e9phone ONISEP pour le service Antilles",phoneNumbers:a});a=new ContactName;a.givenName="ONISEP Antilles-Guyane";b[0].name=a;b[0].save();navigator.notification.alert("Les coordonn\u00e9es t\u00e9l\u00e9phoniques de ONISEP Antilles-Guyane ont \u00e9t\u00e9 ajout\u00e9es \u00e0 vos contacts",
null,"Message")}else return navigator.notification.alert("Le Contact ONISEP Antilles-Guyane est d\u00e9j\u00e0 enregistr\u00e9",null,"Message"),!1}function e(b){var a="Une erreur s'est produite";20==b.code&&(a='L\'acc\u00e8s \u00e0 vos contacts est d\u00e9sactiv\u00e9. Si vous le souhaitez, r\u00e9activez cette option en allant dans  "r\u00e9glage" -> "confidentialit\u00e9" -> "contacts"');navigator.notification.alert(a,null,"Erreur");return!1}function d(b,a){var c=["displayName","name"];"Metro"==
a?navigator.contacts.find(c,f,e,b):navigator.contacts.find(c,g,e,b)}return{init:function(){function b(a){a?($("#phone-share").addClass("open"),0==$("#phone > #phone-overlay").size()&&$("#phone").prepend($("#phone-overlay")),$("#phone-overlay").css("display","block"),$("#phone .oel-page-header").addClass("fixedHeader"),$("[data-role=header]").fixedtoolbar({tapToggle:!1}),$("body").addClass("hiddenScroll"),$("#phone-share-items").slideDown("fast",function(){$("#toggle-phone-share span.ui-icon-arrow-d").removeClass("ui-icon-arrow-d").addClass("ui-icon-arrow-u")})):
($("#phone-overlay").css("display","none"),$("#phone .oel-page-header").removeClass("fixedHeader"),$("[data-role=header]").fixedtoolbar({tapToggle:!0}),$("body").removeClass("hiddenScroll"),$("#phone-share-items").slideUp("fast",function(){$("#toggle-phone-share span.ui-icon-arrow-u").removeClass("ui-icon-arrow-u").addClass("ui-icon-arrow-d");$("#phone-share").removeClass("open")}))}var a=new ContactFindOptions;a.filter="ONISEP M\u00e9tropole";var c=new ContactFindOptions;c.filter="ONISEP Antilles-Guyane";
$("#add-contact-metro").click(function(){d(a,"Metro")});$("#add-contact-anti").click(function(){d(c,"Anti")});$("#phone-share-contacts").click(function(b){if("windows-phone-8"==deviceOS||"windows-8"==deviceOS||"Android"==deviceOS||"iOS"==deviceOS)$.mobile.changePage("#phone-contact",{transition:"pop",role:"dialog"});else{if("Blackberry"==deviceOS)return navigator.notification.alert("Vous ne pouvez pas sauvegarder dans vos contacts",null,"Message"),!1;d(a,"Metro");d(c,"Anti")}});$(".iphone-share-sms").click(function(){window.plugins.smsComposer.showSMSComposer("",
"Mon orientation en ligne : contacter un conseiller par t\u00e9l\u00e9phone\nPour une mise en relation avec le service en M\u00e9tropole : 01 77 77 12 25. Pour une mise en relation avec le service aux Antilles-Guyane : 05 96 53 12 25")});$("#phone-share-mail").click(function(){});$("#phone-share-twitter").click(function(){var a="https://twitter.com/share?url="+encodeURIComponent("www.monorientationenligne.fr")+"&text="+encodeURIComponent("Mon orientation en ligne : contacter un conseiller par t\u00e9l\u00e9phone en M\u00e9tropole au 01 77 77 12 25 et aux Antilles-Guyane au 05 96 53 12 25");
("windows-phone-8"==deviceOS||"windows-8"==deviceOS)&&ChildBrowser.install();window.plugins.childBrowser.showWebPage(a,{showLocationBar:!1})});$("#phone-content-page").prepend($("#phone-share")).prepend($("#phone-overlay"));$("#toggle-phone-share").off("click").click(function(){b($("#phone-overlay").is(":hidden"));return!1});$("#phone-overlay").click(function(a){a.preventDefault()})}}}();

var OELMailForm=function(){function q(b){b=b.toUpperCase();b=b.replace(/\\u00c1|\u00c0|\u00c4|\u00c2/g,"A");b=b.replace(/\\u00c9|\u00c8|\u00cb|\u00ca/g,"E");b=b.replace(/\\u00cd|\u00cc|\u00cf|\u00ce/g,"I");b=b.replace(/\\u00d3|\u00d2|\u00d6|\u00d4/g,"O");return b=b.replace(/\\u00da|\u00d9|\u00dc|\u00db/g,"U")}this.mailServer=null;return{init:function(){$("#select_country_mail_id").change(function(){"FR"!=$(this).val()?$(".mail-page-container #select_departement_mail_id").parents("p").css("display",
"none"):$(".mail-page-container #select_departement_mail_id").parents("p").css("display","block")});$("#mail-form-valid").click(function(b){var a="",f=RegExp(/(((\"[^\"\f\n\r\t\v\b]+\")|([A-Za-z0-9_\!\#\$\%\&\'\*\+\-\~\/\^\`\|\{\}]+(\.[A-Za-z0-9_\!\#\$\%\&\'\*\+\-\~\/\^\`\|\{\}]+)*))@((\[(((25[0-5])|(2[0-4][0-9])|([0-1]?[0-9]?[0-9]))\.((25[0-5])|(2[0-4][0-9])|([0-1]?[0-9]?[0-9]))\.((25[0-5])|(2[0-4][0-9])|([0-1]?[0-9]?[0-9]))\.((25[0-5])|(2[0-4][0-9])|([0-1]?[0-9]?[0-9])))\])|(((25[0-5])|(2[0-4][0-9])|([0-1]?[0-9]?[0-9]))\.((25[0-5])|(2[0-4][0-9])|([0-1]?[0-9]?[0-9]))\.((25[0-5])|(2[0-4][0-9])|([0-1]?[0-9]?[0-9]))\.((25[0-5])|(2[0-4][0-9])|([0-1]?[0-9]?[0-9])))|((([A-Za-z0-9\-])+\.)+[A-Za-z\-]{2,})))/),
d=$("#mail-form-question").val(),e=$("textarea[name='mail-form-question-texte']").val(),c=$("input[name='form-mail-etude']").val(),g=$("select[name='mail-form-cadre']").val(),p=$("input[name='mail-form-sexe']:checked"),h=$("#mail-form-email").val(),m=$("#select_country_mail_id").val(),k=$("#select_departement_mail_id").val();""==m&&(a+="Merci de choisir votre pays.\n");!k&&"FR"==m&&(a+="Merci de choisir votre d\u00e9partement.\n");!h||""==h.trim()?a+="Merci de saisir votre m\u00e9l.\n":f.test(h)||
(a+="Le format de l\u2019email n\u2019est pas valide.\n");if(!d||""==d.trim())a+="Merci de saisir une valeur dans le champ qui \u00eates vous.\n";0==p.length&&(a+="Merci de choisir le genre (Gar\u00e7on ou Fille) de la personne pour laquelle vous posez la question.\n");if(!g||""==g)a+="Merci de choisir le profil de la personne concern\u00e9e.\n";if(!c||""==c)a+="Merci d'indiquer votre niveau de formation.\n";if(!e||""==e)a+="Merci de saisir votre question.\n";if(""!=a)return $.mobile.loading("hide"),
navigator.notification.alert("Tous les champs sont obligatoires.\n"+a,null,"Message"),b.stopPropagation(),!1;OELGeoloc.checkConnection()?($.mobile.loading("hide"),OELMailForm.sendMailWS(),$.mobile.changePage("#mail-thanks")):($.mobile.loading("hide"),$.mobile.changePage("#mail-offline",{transition:"pop",role:"dialog"}));b.stopPropagation();return!0})},setEndPoint:function(b){mailServer=b},sendMailWS:function(){var b=$("input[name='form-mail-etude']").val(),a="oui",f=1,d=b,e="NC",c=$("select[name='mail-form-cadre']"),
g=$("#select_country_mail_id");"NonScolaris\u00e9"==c.val()?(f=2,a="non",e=b,d="NC"):"Autre"==c.val()&&(f=3,a="NC",e=b,d="NC");var b=$("#mail-form-question").val(),p=$("textarea[name='mail-form-question-texte']").val(),c=c.val(),h=$("input[name='mail-form-sexe']:checked").val(),m=$("#mail-form-email").val(),k=g.val(),n=999,l=999;"FR"==g.val()&&(l=$("#select_departement_mail_id option:selected").val(),n=q($("#select_departement_mail_id option:selected").text()),2==l.length&&(l="0"+l.toString()));"FR"==
k&&(k="FRANCE");"999"==n&&(n="Etranger");$.ajax({url:mailServer,type:"POST",dataType:"xml",data:{autorisation:0,email:m,kelfrm:f,scolarise:a,qualite:c,parcours1:d,age:"NC",statut:"NC",sexe:h,etab:"NC",villeetab:"NC",paysetab:"NC",ville:"NC",pays:k,departement:n,codepost:l,question:p,infodemandeur:b,parcours2:e,media:"Phone",ticketnumber:"NC",satisfaction:"NC",commentaire:"NC",provenance:"",source:"applimoel"},success:function(a,b){},error:function(a,b,c){}})}}}();

var OELGeolocView=function(){function m(){if("windows-8"==deviceOS)document.getElementById("map_canvas_iframe").contentWindow.postMessage("createMap?",d);else if(null==mapDiv){var a={zoom:12,mapTypeId:google.maps.MapTypeId.ROADMAP,disableDefaultUI:!0};mapDiv=new google.maps.Map(document.getElementById("map_canvas"),a)}}function r(){var a=$(".geo-page-container").find("#city_zipCode").val();s();var b=parseInt(a);4==b.length||5==b.length?(4==b.length&&(b="0"+b.toString()),t(!1,b)):t(a,!1)}function h(a){a&&
(distance=a.distance,distance=500<distance?"\u00e0 "+parseFloat(distance/1E3).toFixed(2)+" km":"\u00e0 "+parseFloat(distance).toFixed(2)+" m",$("#geo-map-top .map-text h2").html(a.name),$("#geo-map-top .map-text .distence").html(distance),$("#geo-map-top .map-text .addresse").html(a.street+" - "+a.address))}function s(){if(markers)if("windows-8"==deviceOS)document.getElementById("map_canvas_iframe").contentWindow.postMessage("clearMarkers?",d);else{for(i in markers)markers[i].setMap(null),delete markers[i];
markers=[]}}function u(a){a=a%bureaux.length+1;var b="";if(markers)if("windows-8"==deviceOS)document.getElementById("map_canvas_iframe").contentWindow.postMessage("updateMarkers?"+a,d);else for(i in markers)0==i?markers[i].visible||markers[i].setVisible(!0):(b=1.5<=window.devicePixelRatio?"img/icons/gmap/marker2x.png":"img/icons/gmap/marker.png",a==i&&(b=b.replace("marker","currentMarker")),b=new google.maps.MarkerImage(b,null,null,null,new google.maps.Size(24,37)),markers[i].setIcon(b),markers[i].centerMapOnShow=
!1,markers[i].setVisible(!0))}function w(a,b){this.MarkerIndex=this.MarkerIndex||0;var e=new google.maps.LatLng(180*a.location.latitude/Math.PI,180*a.location.longitude/Math.PI),c=1.5<=window.devicePixelRatio?"img/icons/gmap/marker2x.png":"img/icons/gmap/marker.png";b&&(c=c.replace("marker","currentMarker"));c=new google.maps.MarkerImage(c,null,null,null,new google.maps.Size(24,37));marker=new google.maps.Marker({content:"<h3>"+a.name+"</h3><br />"+a.street+" "+a.address+"<br />"+a.tel+"<br />"+a.fax+
"<br />"+a.email+"<br />"+a.site,position:e,title:a.name,bounds:!0,animation:google.maps.Animation.DROP,zIndex:11,zoom:12,map:mapDiv,icon:c,MarkerIndex:this.MarkerIndex,centerMapOnShow:!1,optimized:!1});google.maps.event.addListener(marker,"click",function(){$("#geo .aroundme li:eq("+this.MarkerIndex+") a").trigger("click")});google.maps.event.addListener(marker,"mousedown",function(){$("#geo .aroundme li:eq("+this.MarkerIndex+") a").trigger("click")});marker.setMap(mapDiv);markers.push(marker);this.MarkerIndex++}
function p(){if("windows-8"==deviceOS)if(!1!=customCoords)document.getElementById("map_canvas_iframe").contentWindow.postMessage("addMeOnMap?"+customCoords.latitude+":"+customCoords.longitude,d);else{var a=OELGeoloc.getPosition();document.getElementById("map_canvas_iframe").contentWindow.postMessage("addMeOnMap?"+a.coords.latitude+":"+a.coords.longitude,d)}else{!1!=customCoords?a=new google.maps.LatLng(customCoords.latitude,customCoords.longitude):(a=OELGeoloc.getPosition(),a=new google.maps.LatLng(a.coords.latitude,
a.coords.longitude));var b=new google.maps.MarkerImage(1.5<=window.devicePixelRatio?"img/icons/gmap/myPositionMarker2x.png":"img/icons/gmap/myPositionMarker.png",null,null,null,new google.maps.Size(18,18));marker=new google.maps.Marker({content:'<div class="marker-window-text"><h3>Moi</h3></div>',position:a,title:"Moi",bounds:!0,animation:google.maps.Animation.DROP,zIndex:11,zoom:12,map:mapDiv,icon:b,centerMapOnShow:!1,optimized:!1});marker.setMap(mapDiv);markers.push(marker)}}function t(a,b){var e=
!1!=a?geoServer+"city_complete/"+a+"/(limit)/1":geoServer+"city_complete/"+b,c=$(".geo-page-container .aroundme");c.empty().append('<li class="ui-li ui-li-static ui-btn-up-f ui-corner-top ui-corner-bottom ui-li-last"><span>Chargement</span></li>');c.css("display","block");$.ajax({url:e,type:"GET",dataType:"json",success:function(a){try{if(0<a.length){var b={latitude:180*a[0].latitude/Math.PI,longitude:180*a[0].longitude/Math.PI};customCoords=b;v(b)}else OELLogger.log("Pas de correspondance pour l'entr\u00e9e",
null,"Message"),n(),$("#geo-manuel-valide").val("")}catch(c){OELLogger.log("Pas de correspondance pour l'entr\u00e9e",null,"Message"),n(),$("#geo-manuel-valide").val("")}},error:function(a,b,c){OELLogger.log("Pas de correspondance pour l'entr\u00e9e",null,"Message");n();$("#geo-manuel-valide").val("")}})}function n(){var a=$(".geo-page-container .aroundme");a.empty().append('<li class="ui-li ui-li-static ui-btn-up-f ui-corner-top ui-corner-bottom ui-li-last"><span>Aucun centre \u00e0 proximit\u00e9</span></li>');
a.css("display","block");$(".link-map").css("display","none")}function v(a){if(!1==a){a=OELGeoloc.getPosition();var b=a.coords.latitude;a=a.coords.longitude;customCoords=!1}else b=a.latitude,a=a.longitude;var e=$(".geo-page-container .aroundme");e.css("display","block");e.empty().append('<li class="ui-li ui-li-static ui-btn-up-f ui-corner-top ui-corner-bottom ui-li-last"><span>Chargement</span></li>');$(".geo-page-container .infos .infos-automatique-titre").remove();$('<p class="infos-automatique-titre">Pr\u00e8s de chez moi</p>').insertBefore($(".geo-page-container .infos .departement"));
$.ajax({url:geoServer+"search/"+b+"\u00b0/"+a+"\u00b0/(limit)/5",type:"GET",dataType:"json",success:function(a){try{if(0<a.locations.length){var b=null;e.empty();for(var k=0;k<a.locations.length;k++){"windows-8"==deviceOS&&document.getElementById("map_canvas_iframe").contentWindow.postMessage("setBureauDetails?"+a.locations[k].latitude+":"+a.locations[k].longitude+":"+k,d);var h=bureaux,m=k,g=a.locations[k],f=new details;f.type=g.type;f.name=g.name;f.url=g.url;f.address=g.address;f.street=g.street;
f.tel=g.phone;f.fax=g.fax;f.email=g.email;f.site=g.website;f.location.latitude=g.latitude;f.location.longitude=g.longitude;f.distance=g.distance;h[m]=f;b=bureaux[k].distance;b=500<b?parseFloat(b/1E3).toFixed(2)+" km":parseFloat(b).toFixed(2)+" m";h='data-transition="slide"';OELisNotTransitionAware&&(h="");e.append("<li><a "+h+' class="aroundme_bureau" id="bureau_'+k+'" href="#geo-details">'+bureaux[k].name+' <span class="ui-li-count">'+b+"</span></a></li>")}var l=$.mobile.activePage;"geo"==l.attr("id")&&
(e.listview("refresh"),"Android"!=deviceOS&&"windows-phone-8"!=deviceOS&&iScrollAdjust($(".oel-page-content",l).attr("id")));$(".link-map").css("display","inline-block")}else n()}catch(p){n()}},error:function(a,b,e){n()}});$.mobile.loading("hide");"Android"!=deviceOS&&("windows-phone-8"!=deviceOS&&$.mobile.activePage.attr("id")in OELScroll)&&iScrollAdjust($.mobile.activePage.attr("id")+"-content-page")}function q(){for(var a=!1,b=0;b<bureaux.length;b++)a=0==b?!0:!1,"windows-8"==deviceOS?document.getElementById("map_canvas_iframe").contentWindow.postMessage("addMarker?"+
b+":"+a,d):w(bureaux[b],a)}function l(){var a=$(window).height()-$("#geo-map .oel-page-header").height()-$("#geo-map-top").height()-8;if($("#map_canvas").length)var b=$("#map_canvas");else b=$("#map_canvas_iframe"),document.getElementById("map_canvas_iframe").contentWindow.postMessage("resizeMapContainer?"+a,d);b.css("height",a)}this.infoWindow=this.mapDiv=this.geoServer=null;this.markers=[];this.bureaux=[];this.customCoords=!1;this.details=function(){this.distance=this.site=this.email=this.fax=this.tel=
this.address=this.street=this.url=this.name=this.type=null;this.location={longitude:null,latitude:null}};this.currentBureau=null;this.centerOnMyPosition=!0;var d="ms-appx-web://"+document.location.host;$(document).bind("pageshow",function(a,b){if("geo-map"==a.target.id){l();var e;if("windows-8"==deviceOS)document.getElementById("map_canvas_iframe").contentWindow.postMessage("refreshMap?"+centerOnMyPosition,d);else{google.maps.event.trigger(mapDiv,"resize");if(centerOnMyPosition)e=markers[0].getPosition(),
centerOnMyPosition=!1;else for(i in markers)if(!0==markers[i].centerMapOnShow){e=markers[i].getPosition();break}mapDiv.setCenter(e)}$("#geo-map [data-role=header]").fixedtoolbar({tapToggle:!1})}});return{init:function(){$(".geo-map-itineraire").click(function(){var a=$(this).attr("data-url");"windows-8"!=deviceOS&&($(this).attr("href",""),window.plugins.childBrowser.showWebPage(a,{showLocationBar:!1}))});$(".geo-map-bureau").click(function(){centerOnMyPosition=!1;idBureau=$(this).attr("id").split("_");
currentBureau=idBureau=parseInt(idBureau[1]);m();h(bureaux[idBureau]);var a=idBureau+1,b="";if(markers)if("windows-8"==deviceOS)document.getElementById("map_canvas_iframe").contentWindow.postMessage("hideMarkers?"+a+":false",d);else for(i in markers)a==i?(markers[i].centerMapOnShow=!0,markers[i].setVisible(!0)):(markers[i].centerMapOnShow=!1,markers[i].setVisible(!1)),0!=i&&(b=markers[i].icon.url,-1!=b.indexOf("current-marker")&&(b=b.replace("current-marker","marker"),b=new google.maps.MarkerImage(b,
null,null,null,new google.maps.Size(24,37)),markers[i].setIcon(b)))});$(".link-map").click(function(){m();if(0==markers.length)p(),q(),h(bureaux[0]);else if(markers)if("windows-8"==deviceOS)document.getElementById("map_canvas_iframe").contentWindow.postMessage("showMarkers?",d);else for(i in markers)markers[i].centerMapOnShow=!1,markers[i].setVisible(!0);centerOnMyPosition=!0});$(document).on("click","a.aroundme_bureau",function(){"windows-8"==deviceOS?(m(),p(),q()):(null==mapDiv&&m(),0==markers.length&&
(p(),q()));idBureau=$(this).attr("id").split("_");currentBureau=idBureau=parseInt(idBureau[1]);var a=bureaux[idBureau],b=a.site,e=a.site;/^http?:\/\//i.test(b)||(b="http://"+b);var e=b.split(/\/+/g)[1],c=$("#geo-details .geo-page-container.page-details .ui-body"),d="";$("h1",c).html(a.name);$("address",c).html(a.street+" "+a.address);$("p",c).html("Fax : "+a.fax);d=0<$(".call-tel span.ui-btn-text",c).size()?" span.ui-btn-text":"";$(".call-tel",c).attr("href","tel:"+a.tel.replace(/\s+/g,""));$(".call-tel"+
d,c).html(a.tel);d=0<$(".cio_mail span.ui-btn-text",c).size()?" span.ui-btn-text":"";$(".cio_mail",c).attr("href","mailto:"+a.email);$(".cio_mail"+d,c).html(a.email);d=0<$(".geo-website span.ui-btn-text",c).size()?" span.ui-btn-text":"";$(".geo-website",c).attr("href",b);$(".geo-website",c).attr("data-url",b);$(".geo-website"+d,c).html(e);$(".geo-map-bureau",c).attr("id","geo-map-bureau_"+currentBureau);$(".geo-map-itineraire",c).attr("id","geo-map-itineraire_"+currentBureau);h(bureaux[void 0]);b=
OELGeoloc.getPosition();a=180*a.location.latitude/Math.PI+","+180*a.location.longitude/Math.PI;b=b?b.coords.latitude+","+b.coords.longitude:"";$(".geo-map-itineraire",c).attr("href","http://maps.google.com/?daddr="+encodeURIComponent(a)+"&saddr="+encodeURIComponent(b));$(".geo-map-itineraire",c).attr("data-url","http://maps.google.com/?daddr="+encodeURIComponent(a)+"&saddr="+encodeURIComponent(b))});$("#geo-map-top .map-back").click(function(){currentBureau=0==currentBureau?bureaux.length-1:currentBureau-
1;h(bureaux[currentBureau]);u(currentBureau);bureauToShow=currentBureau+1;currentBureau+1==bureaux.length&&(bureauToShow=0);"windows-8"==deviceOS?document.getElementById("map_canvas_iframe").contentWindow.postMessage("setCenter?"+bureauToShow,d):mapDiv.setCenter(markers[currentBureau+1].getPosition());l()});$("#geo-map-top .map-next").click(function(){currentBureau=currentBureau==bureaux.length-1?0:currentBureau+1;h(bureaux[currentBureau]);u(currentBureau);"windows-8"==deviceOS?document.getElementById("map_canvas_iframe").contentWindow.postMessage("setCenter?"+
(currentBureau+1),d):mapDiv.setCenter(markers[currentBureau+1].getPosition());l()});$(".link-map").css("display","none");$("#geo-manuel-valide").click(function(){r();$("#city_zipCode").blur();return!1});$("#city_zipCode").focus(function(){$(this).val("")});$(".geo-website").click(function(){var a=$(this).attr("data-url");if("iOS"==deviceOS||"windows-phone-8"==deviceOS)"windows-phone-8"==deviceOS&&ChildBrowser.install(),$(this).attr("href",""),window.plugins.childBrowser.showWebPage(a)})},autourdemoi:v,
setEndPoint:function(a){geoServer=a},refreshBureaux:r,clearMarkers:s,resizeMapContainer:l,handleIframeResponse:function(a){var b=a.data.split("?")[0];a=a.data.split("?")[1];"showBureau"==b&&$("#geo .aroundme li:eq("+a+") a").trigger("click")}}}();

