
/**
 * Notification that the UI is about to transition to a new page.
 * Perform custom prepage-transition logic here.
 * @param {String} currentPageId 
 * @param {String} targetPageId 
 * @returns {boolean} true to continue transtion; false to halt transition
 */
phoneui.prePageTransition = function(currentPageId,targetPageId) {
  // add custom pre-transition code here
  // return false to terminate transition
  return true;
}

/**
 * Notification that the UI has transition to a new page.
 * 
 * @param {String} newPageId 
 */
phoneui.postPageTransition = function(newPageId) {
  
}

/**
 * Notification that device orientation has changed. 
 * 
 * @param {String} newOrientation 
 */
phoneui.postOrientationChange = function(newOrientation) {
  
}

/**
 * Called when document is loaded.
 */
phoneui.documentReadyHandler = function() {
}















var m1Design = function() { m1Design = {}; (function() {var aa="data-layout-content-height";var b="e0";var ba="e1";var f="e10";var ca="e100";var u="e101";var ea="e102";var fa="e103";var v="e104";var ga="e105";var ha="e106";var ia="e107";var ja="e108";var ka="e109";var la="e110";var ma="e111";var na="e112";var w="e113";var oa="e114";var x="e115";var qa="e116";var ra="e117";var y="e118";var sa="e119";var ta="e120";var ua="e121";var va="e122";var wa="e123";var xa="e124";var ya="e125";var za="e126";var z="e127";var Aa="e128";var A="e129";var Ba="e13";
var Ca="e130";var Da="e131";var B="e132";var Ea="e133";var Fa="e134";var Ga="e135";var Ha="e136";var Ia="e137";var Ja="e138";var Ka="e139";var C="e14";var La="e140";var D="e141";var Ma="e142";var E="e143";var Na="e144";var Oa="e145";var F="e146";var Pa="e147";var Qa="e148";var Ra="e149";var Sa="e15";var Ta="e150";var Ua="e151";var Va="e152";var Wa="e153";var Xa="e154";var G="e155";var Ya="e156";var H="e157";var Za="e158";var $a="e159";var ab="e16";var I="e160";var bb="e161";var cb="e162";var db="e163";
var eb="e164";var fb="e165";var gb="e166";var hb="e167";var ib="e168";var jb="e169";var kb="e17";var lb="e170";var J="e171";var mb="e172";var K="e173";var nb="e174";var ob="e175";var L="e176";var pb="e177";var qb="e178";var rb="e179";var sb="e18";var tb="e180";var ub="e181";var vb="e182";var wb="e183";var xb="e184";var yb="e185";var M="e19";var N="e2";var zb="e20";var Ab="e21";var Bb="e22";var Cb="e23";var O="e24";var Db="e25";var Eb="e26";var Fb="e27";var Gb="e28";var P="e29";var Hb="e3";
var Ib="e30";var Jb="e31";var Kb="e32";var Lb="e33";var Q="e34";var Mb="e35";var Nb="e36";var Ob="e37";var Pb="e38";var R="e39";var Qb="e4";var Rb="e40";var Sb="e41";var Tb="e42";var Ub="e45";var Vb="e46";var Wb="e47";var Xb="e48";var Yb="e49";var Zb="e5";var S="e50";var $b="e51";var T="e52";var ac="e53";var bc="e54";var U="e55";var cc="e56";var dc="e57";var ec="e58";var fc="e59";var V="e6";var gc="e60";var hc="e61";var ic="e62";var jc="e63";var kc="e64";var lc="e65";var mc="e66";var nc="e67";
var oc="e68";var pc="e69";var qc="e7";var rc="e70";var sc="e71";var W="e72";var tc="e73";var uc="e74";var X="e75";var vc="e76";var wc="e77";var xc="e78";var yc="e79";var zc="e8";var Ac="e80";var Bc="e81";var Cc="e82";var Dc="e83";var Ec="e84";var Fc="e85";var Gc="e86";var Y="e87";var Hc="e88";var Ic="e89";var Jc="e9";var Kc="e90";var Z="e91";var Lc="e92";var Mc="e93";var Nc="e94";var Oc="e95";var Pc="e96";var Qc="e97";var Rc="e98";var Sc="e99";var Tc="home";var Uc="m1-";var Vc="m1-bisteccheria-back1";
var Wc="m1-bisteccheria-image1";var Xc="m1-bisteccheria-image2";var Yc="m1-bisteccheria-image3";var Zc="m1-bisteccheria-image4";var $c="m1-bisteccheria-image5";var ad="m1-bisteccheria-image6";var bd="m1-bisteccheria-image7";var cd="m1-bisteccheria-image8";var dd="m1-bisteccheria-text1";var ed="m1-bisteccheria-text2";var fd="m1-bisteccheria-toolbar1";var gd="m1-caf_-back1";var hd="m1-caf_-image1";var id="m1-caf_-image2";var jd="m1-caf_-image3";var kd="m1-caf_-image4";var ld="m1-caf_-image5";
var md="m1-caf_-image6";var nd="m1-caf_-image7";var od="m1-caf_-image8";var pd="m1-caf_-text1";var qd="m1-caf_-text2";var rd="m1-caf_-toolbar1";var sd="m1-cocktails-back1";var td="m1-cocktails-image1";var ud="m1-cocktails-image2";var vd="m1-cocktails-image3";var wd="m1-cocktails-image4";var xd="m1-cocktails-image5";var yd="m1-cocktails-image6";var zd="m1-cocktails-image7";var Ad="m1-cocktails-image8";var Bd="m1-cocktails-text1";var Cd="m1-cocktails-text2";var Dd="m1-cocktails-toolbar1";var Ed="m1-credits-back1";
var Fd="m1-credits-image1";var Gd="m1-credits-image2";var Hd="m1-credits-image3";var Id="m1-credits-image4";var Jd="m1-credits-image5";var Kd="m1-credits-image6";var Ld="m1-credits-image7";var Md="m1-credits-image8";var Nd="m1-credits-text1";var Od="m1-credits-text2";var Pd="m1-credits-text3";var Qd="m1-credits-toolbar1";var Rd="m1-dessert-back1";var Sd="m1-dessert-image1";var Td="m1-dessert-image2";var Ud="m1-dessert-image3";var Vd="m1-dessert-image4";var Wd="m1-dessert-image5";var Xd="m1-dessert-image6";
var Yd="m1-dessert-image7";var Zd="m1-dessert-image8";var $d="m1-dessert-text1";var ae="m1-dessert-text2";var be="m1-dessert-toolbar1";var ce="m1-dove_siamo-back1";var de="m1-dove_siamo-image1";var ee="m1-dove_siamo-image2";var fe="m1-dove_siamo-image3";var ge="m1-dove_siamo-image4";var he="m1-dove_siamo-image5";var ie="m1-dove_siamo-image6";var je="m1-dove_siamo-image7";var ke="m1-dove_siamo-map1";var le="m1-dove_siamo-map1outer";var me="m1-dove_siamo-text1";var ne="m1-dove_siamo-text2";var oe="m1-dove_siamo-toolbar1";
var pe="m1-home-accessoryImage1";var qe="m1-home-accessoryImage15";var re="m1-home-accessoryImage16";var se="m1-home-accessoryImage4";var te="m1-home-accessoryImage5";var ue="m1-home-accessoryImage6";var ve="m1-home-image1";var we="m1-home-image10";var xe="m1-home-image11";var ye="m1-home-image12";var ze="m1-home-image13";var Ae="m1-home-image2";var Be="m1-home-image3";var Ce="m1-home-image4";var De="m1-home-image5";var Ee="m1-home-image6";var Fe="m1-home-image7";var Ge="m1-home-image8";var He="m1-home-image9";
var Ie="m1-home-listItem1-inner-div";var Je="m1-home-listItem16-inner-div";var Ke="m1-home-listItem4-inner-div";var Le="m1-home-listItem5-inner-div";var Me="m1-home-listItem6-inner-div";var Ne="m1-home-panel1";var Oe="m1-home-panel1-scroller";var Pe="m1-home-pizzeria-inner-div";var Qe="m1-home-push7";var Re="m1-home-text1";var Se="m1-home-text15";var Te="m1-home-text16";var Ue="m1-home-text2";var Ve="m1-home-text5";var We="m1-home-text6";var Xe="m1-home-text7";var Ye="m1-home-toolbar1";var Ze="m1-il_locale-back1";
var $e="m1-il_locale-image1";var af="m1-il_locale-image10";var bf="m1-il_locale-image11";var cf="m1-il_locale-image2";var df="m1-il_locale-image3";var ef="m1-il_locale-image4";var ff="m1-il_locale-image5";var gf="m1-il_locale-image6";var hf="m1-il_locale-image7";var jf="m1-il_locale-image8";var kf="m1-il_locale-image9";var lf="m1-il_locale-text1";var mf="m1-il_locale-toolbar1";var nf="m1-images-preloader";var of="m1-images-preloader2";var pf="m1-orari-back1";var qf="m1-orari-image1";var rf="m1-orari-image2";
var sf="m1-orari-image3";var tf="m1-orari-image4";var uf="m1-orari-image5";var vf="m1-orari-image6";var wf="m1-orari-image7";var xf="m1-orari-text1";var yf="m1-orari-text3";var zf="m1-orari-text4";var Af="m1-orari-text5";var Bf="m1-orari-text6";var Cf="m1-orari-text7";var Df="m1-orari-text8";var Ef="m1-orari-text9";var Ff="m1-orari-toolbar1";var Gf="m1-pizzeria-back1";var Hf="m1-pizzeria-image1";var If="m1-pizzeria-image2";var Jf="m1-pizzeria-image3";var Kf="m1-pizzeria-image4";var Lf="m1-pizzeria-image5";
var Mf="m1-pizzeria-image6";var Nf="m1-pizzeria-image7";var Of="m1-pizzeria-image8";var Pf="m1-pizzeria-text1";var Qf="m1-pizzeria-text2";var Rf="m1-pizzeria-toolbar1";var $="px";var Sf=function(d){return Uc+d};
var Xf={"home":{"id":Tc,"anchor_id":"#m1-home","resize":function(d,e){var a;var c={};var g;a=c[N]={w:d,h:e,py:0};try{a=c[b]={w:0,h:0,py:0,p:c[N]};a.w=Math.max(a.p.w,0);a.h=43;a.p.py+=43}catch(h){}try{a=c[ba]={e:document.getElementById(Re),w:0,h:0,py:0,p:c[b]};a.e.style.width=97+$;a.e.style.left=Math.max((a.p.w-97)*0.4978,0)+$;a.w=97;a.e.style.height=25+$;a.e.style.top=Math.max(a.p.h-34,0)-a.p.py+$;a.h=25;a.p.py+=25}catch(i){}try{a=c[Hb]={e:document.getElementById(Qe),w:0,h:0,py:0,p:c[b]};a.w=83;a.e.style.height=
30+$;a.e.style.top=Math.max(a.p.h-36,0)-a.p.py+$;a.h=30;a.p.py+=30}catch(j){}try{a=c[Qb]={e:document.getElementById(Ee),w:0,h:0,py:0,p:c[b]};a.w=32;a.e.style.height=Math.max(a.p.h-11,0)+$;a.e.style.lineHeight=Math.max(a.p.h-11,0)-2+$;a.e.style.top=6-a.p.py+$;a.h=Math.max(a.p.h-11,0);a.p.py+=Math.max(2,a.p.h-11)}catch(k){}try{a=c[Zb]={e:document.getElementById(Ne),w:0,h:0,py:0,p:c[N]};a.w=Math.max(a.p.w,0);a.e.style.height=Math.max(a.p.h-87,0)+$;a.e.style.top=43-a.p.py+$;a.h=Math.max(a.p.h-87,0);a.p.py+=
Math.max(0,a.p.h-87)}catch(l){}try{a=c[zc]={e:document.getElementById(Oe),w:0,h:0,py:0,p:c[Zb]};a.conth=a.e.getAttribute(aa);a.w=Math.max(a.p.w,0);a.e.style.height=(a.conth||(373<Math.max(a.p.h,0)?Math.max(a.p.h,0):Math.max(373,a.p.h)))+$;a.e.style.top=0-a.p.py+$;a.h=a.conth||(373<Math.max(a.p.h,0)?Math.max(a.p.h,0):Math.max(373,a.p.h));a.p.py+=Math.max(a.conth||(373<Math.max(a.p.h,0)?Math.max(a.p.h,0):Math.max(373,a.p.h)),0)}catch(m){}try{a=c[Jc]={e:document.getElementById(Be),w:0,h:0,py:0,p:c[zc]};
a.e.style.width=200+$;a.e.style.left=Math.max((a.p.w-200)*0.5,0)+$;a.w=200;a.h=32;a.p.py+=32}catch(n){}try{a=c[f]={w:0,h:0,py:0,p:c[zc]};a.w=Math.max(a.p.w,0);a.h=363;a.p.py+=363}catch(o){}try{a=c[Ba]={w:0,h:0,py:0,p:c[f]};a.w=Math.max(a.p.w-18,0);a.h=45;a.p.py+=45}catch(p){}try{a=c[C]={e:document.getElementById(Pe),w:0,h:0,py:0,p:c[Ba]};a.w=Math.max(a.p.w- -20,0);a.e.style.height=Math.max(a.p.h,0)+$;a.e.style.top=0-a.p.py+$;a.h=Math.max(a.p.h,0);a.p.py+=Math.max(0,a.p.h)}catch(q){}try{a=c[Sa]={e:document.getElementById(qe),
w:0,h:0,py:0,p:c[C]};a.w=9;a.e.style.height=13+$;a.e.style.top=Math.max((a.p.h-13)*0.5,0)-a.p.py+$;a.h=13;a.p.py+=13}catch(r){}try{a=c[ab]={e:document.getElementById(Se),w:0,h:0,py:0,p:c[C]};a.w=68;a.e.style.height=22+$;a.e.style.top=Math.max((a.p.h-22)*0.4783,0)-a.p.py+$;a.h=22;a.p.py+=22}catch(s){}try{a=c[kb]={e:document.getElementById(Ge),w:0,h:0,py:0,p:c[C]};a.w=48;a.e.style.height=45+$;a.e.style.top=0-a.p.py+$;a.h=45;a.p.py+=45}catch(t){}try{a=c[sb]={w:0,h:0,py:0,p:c[f]};a.w=Math.max(a.p.w-18,
0);a.h=45;a.p.py+=45}catch(da){}try{a=c[M]={e:document.getElementById(Le),w:0,h:0,py:0,p:c[sb]};a.w=Math.max(a.p.w- -20,0);a.e.style.height=Math.max(a.p.h,0)+$;a.e.style.top=0-a.p.py+$;a.h=Math.max(a.p.h,0);a.p.py+=Math.max(0,a.p.h)}catch(pa){}try{a=c[zb]={e:document.getElementById(te),w:0,h:0,py:0,p:c[M]};a.w=9;a.e.style.height=13+$;a.e.style.top=Math.max((a.p.h-13)*0.5,0)-a.p.py+$;a.h=13;a.p.py+=13}catch(Tf){}try{a=c[Ab]={e:document.getElementById(We),w:0,h:0,py:0,p:c[M]};a.w=109;a.e.style.height=
22+$;a.e.style.top=Math.max((a.p.h-22)*0.4783,0)-a.p.py+$;a.h=22;a.p.py+=22}catch(Uf){}try{a=c[Bb]={e:document.getElementById(He),w:0,h:0,py:0,p:c[M]};a.w=48;a.e.style.height=45+$;a.e.style.top=0-a.p.py+$;a.h=45;a.p.py+=45}catch(Vf){}try{a=c[Cb]={w:0,h:0,py:0,p:c[f]};a.w=Math.max(a.p.w-18,0);a.h=45;a.p.py+=45}catch(Wf){}try{a=c[O]={e:document.getElementById(Ke),w:0,h:0,py:0,p:c[Cb]};a.w=Math.max(a.p.w- -20,0);a.e.style.height=Math.max(a.p.h,0)+$;a.e.style.top=0-a.p.py+$;a.h=Math.max(a.p.h,0);a.p.py+=
Math.max(0,a.p.h)}catch(Yf){}try{a=c[Db]={e:document.getElementById(se),w:0,h:0,py:0,p:c[O]};a.w=9;a.e.style.height=13+$;a.e.style.top=Math.max((a.p.h-13)*0.5,0)-a.p.py+$;a.h=13;a.p.py+=13}catch(Zf){}try{a=c[Eb]={e:document.getElementById(Ve),w:0,h:0,py:0,p:c[O]};a.w=40;a.e.style.height=22+$;a.e.style.top=Math.max((a.p.h-22)*0.4783,0)-a.p.py+$;a.h=22;a.p.py+=22}catch($f){}try{a=c[Fb]={e:document.getElementById(we),w:0,h:0,py:0,p:c[O]};a.w=48;a.e.style.height=45+$;a.e.style.top=0-a.p.py+$;a.h=45;a.p.py+=
45}catch(ag){}try{a=c[Gb]={w:0,h:0,py:0,p:c[f]};a.w=Math.max(a.p.w-18,0);a.h=47;a.p.py+=47}catch(bg){}try{a=c[P]={e:document.getElementById(Ie),w:0,h:0,py:0,p:c[Gb]};a.w=Math.max(a.p.w- -20,0);a.e.style.height=Math.max(a.p.h,0)+$;a.e.style.top=0-a.p.py+$;a.h=Math.max(a.p.h,0);a.p.py+=Math.max(0,a.p.h)}catch(cg){}try{a=c[Ib]={e:document.getElementById(pe),w:0,h:0,py:0,p:c[P]};a.w=9;a.e.style.height=13+$;a.e.style.top=Math.max((a.p.h-13)*0.5,0)-a.p.py+$;a.h=13;a.p.py+=13}catch(dg){}try{a=c[Jb]={e:document.getElementById(Ue),
w:0,h:0,py:0,p:c[P]};a.w=80;a.e.style.height=22+$;a.e.style.top=Math.max((a.p.h-22)*0.48,0)-a.p.py+$;a.h=22;a.p.py+=22}catch(eg){}try{a=c[Kb]={e:document.getElementById(xe),w:0,h:0,py:0,p:c[P]};a.w=48;a.e.style.height=45+$;a.e.style.top=0-a.p.py+$;a.h=45;a.p.py+=45}catch(fg){}try{a=c[Lb]={w:0,h:0,py:0,p:c[f]};a.w=Math.max(a.p.w-18,0);a.h=47;a.p.py+=47}catch(gg){}try{a=c[Q]={e:document.getElementById(Je),w:0,h:0,py:0,p:c[Lb]};a.w=Math.max(a.p.w- -20,0);a.e.style.height=Math.max(a.p.h,0)+$;a.e.style.top=
0-a.p.py+$;a.h=Math.max(a.p.h,0);a.p.py+=Math.max(0,a.p.h)}catch(hg){}try{a=c[Mb]={e:document.getElementById(re),w:0,h:0,py:0,p:c[Q]};a.w=9;a.e.style.height=13+$;a.e.style.top=Math.max((a.p.h-13)*0.5,0)-a.p.py+$;a.h=13;a.p.py+=13}catch(ig){}try{a=c[Nb]={e:document.getElementById(Te),w:0,h:0,py:0,p:c[Q]};a.w=68;a.e.style.height=22+$;a.e.style.top=Math.max((a.p.h-22)*0.48,0)-a.p.py+$;a.h=22;a.p.py+=22}catch(jg){}try{a=c[Ob]={e:document.getElementById(ye),w:0,h:0,py:0,p:c[Q]};a.w=48;a.e.style.height=
45+$;a.e.style.top=0-a.p.py+$;a.h=45;a.p.py+=45}catch(kg){}try{a=c[Pb]={w:0,h:0,py:0,p:c[f]};a.w=Math.max(a.p.w-18,0);a.h=48;a.p.py+=48}catch(lg){}try{a=c[R]={e:document.getElementById(Me),w:0,h:0,py:0,p:c[Pb]};a.w=Math.max(a.p.w- -20,0);a.e.style.height=Math.max(a.p.h,0)+$;a.e.style.top=0-a.p.py+$;a.h=Math.max(a.p.h,0);a.p.py+=Math.max(0,a.p.h)}catch(mg){}try{a=c[Rb]={e:document.getElementById(ue),w:0,h:0,py:0,p:c[R]};a.w=9;a.e.style.height=13+$;a.e.style.top=Math.max((a.p.h-13)*0.4857,0)-a.p.py+
$;a.h=13;a.p.py+=13}catch(ng){}try{a=c[Sb]={e:document.getElementById(Xe),w:0,h:0,py:0,p:c[R]};a.w=73;a.e.style.height=22+$;a.e.style.top=Math.max((a.p.h-22)*0.5,0)-a.p.py+$;a.h=22;a.p.py+=22}catch(og){}try{a=c[Tb]={e:document.getElementById(ze),w:0,h:0,py:0,p:c[R]};a.w=40;a.e.style.height=40+$;a.e.style.top=5-a.p.py+$;a.h=40;a.p.py+=40}catch(pg){}try{a=c[V]={e:document.getElementById(Ye),w:0,h:0,py:0,p:c[N]};a.w=Math.max(a.p.w,0);a.e.style.height=44+$;a.e.style.top=Math.max(a.p.h-44,0)-a.p.py+$;
a.h=44;a.p.py+=44}catch(qg){}try{a=c[Ub]={e:document.getElementById(ve),w:0,h:0,py:0,p:c[V]};a.e.style.width=40+$;a.e.style.left=Math.max((a.p.w-40)*0.9036,0)+$;a.w=40;a.h=40;a.p.py+=40}catch(rg){}try{a=c[Vb]={e:document.getElementById(Ae),w:0,h:0,py:0,p:c[V]};a.e.style.width=32+$;a.e.style.left=Math.max((a.p.w-32)*0.6806,0)+$;a.w=32;a.h=32;a.p.py+=32}catch(sg){}try{a=c[Wb]={e:document.getElementById(Ce),w:0,h:0,py:0,p:c[V]};a.e.style.width=32+$;a.e.style.left=Math.max((a.p.w-32)*0.4826,0)+$;a.w=
32;a.h=32;a.p.py+=32}catch(tg){}try{a=c[Xb]={e:document.getElementById(De),w:0,h:0,py:0,p:c[V]};a.e.style.width=32+$;a.e.style.left=Math.max((a.p.w-32)*0.2847,0)+$;a.w=32;a.h=32;a.p.py+=32}catch(ug){}try{a=c[Yb]={e:document.getElementById(Fe),w:0,h:0,py:0,p:c[V]};a.e.style.width=32+$;a.e.style.left=Math.max((a.p.w-32)*0.0868,0)+$;a.w=32;a.h=32;a.p.py+=32}catch(vg){}try{a=c[qc]={e:document.getElementById(nf),w:0,h:0,py:0,p:c[N]};a.w=0;a.e.style.height=0+$;a.e.style.top=-3E3-a.p.py+$;a.h=0;a.p.py+=
0}catch(wg){}}},"orari":{"id":"orari","anchor_id":"#m1-orari","resize":function(d,e){var a;var c={};var g;a=c[T]={w:d,h:e,py:0};try{a=c[S]={w:0,h:0,py:0,p:c[T]};a.w=Math.max(a.p.w,0);a.h=43;a.p.py+=43}catch(h){}try{a=c[$b]={e:document.getElementById(pf),w:0,h:0,py:0,p:c[S]};a.w=60;a.e.style.height=30+$;a.e.style.top=Math.max(a.p.h-36,0)-a.p.py+$;a.h=30;a.p.py+=30}catch(i){}try{a=c[ac]={e:document.getElementById(xf),w:0,h:0,py:0,p:c[S]};a.e.style.width=47+$;a.e.style.left=Math.max((a.p.w-47)*0.4982,
0)+$;a.w=47;a.e.style.height=25+$;a.e.style.top=Math.max(a.p.h-34,0)-a.p.py+$;a.h=25;a.p.py+=25}catch(j){}try{a=c[bc]={e:document.getElementById(uf),w:0,h:0,py:0,p:c[S]};a.w=32;a.e.style.height=Math.max(a.p.h-11,0)+$;a.e.style.lineHeight=Math.max(a.p.h-11,0)-2+$;a.e.style.top=6-a.p.py+$;a.h=Math.max(a.p.h-11,0);a.p.py+=Math.max(2,a.p.h-11)}catch(k){}try{a=c[U]={e:document.getElementById(Ff),w:0,h:0,py:0,p:c[T]};a.w=Math.max(a.p.w,0);a.e.style.height=44+$;a.e.style.top=Math.max(a.p.h-44,0)-a.p.py+
$;a.h=44;a.p.py+=44}catch(l){}try{a=c[lc]={e:document.getElementById(qf),w:0,h:0,py:0,p:c[U]};a.e.style.width=40+$;a.e.style.left=Math.max((a.p.w-40)*0.9036,0)+$;a.w=40;a.h=40;a.p.py+=40}catch(m){}try{a=c[mc]={e:document.getElementById(rf),w:0,h:0,py:0,p:c[U]};a.e.style.width=32+$;a.e.style.left=Math.max((a.p.w-32)*0.6806,0)+$;a.w=32;a.h=32;a.p.py+=32}catch(n){}try{a=c[nc]={e:document.getElementById(sf),w:0,h:0,py:0,p:c[U]};a.e.style.width=32+$;a.e.style.left=Math.max((a.p.w-32)*0.4826,0)+$;a.w=32;
a.h=32;a.p.py+=32}catch(o){}try{a=c[oc]={e:document.getElementById(tf),w:0,h:0,py:0,p:c[U]};a.e.style.width=32+$;a.e.style.left=Math.max((a.p.w-32)*0.2847,0)+$;a.w=32;a.h=32;a.p.py+=32}catch(p){}try{a=c[pc]={e:document.getElementById(vf),w:0,h:0,py:0,p:c[U]};a.e.style.width=32+$;a.e.style.left=Math.max((a.p.w-32)*0.0868,0)+$;a.w=32;a.h=32;a.p.py+=32}catch(q){}try{a=c[cc]={e:document.getElementById(wf),w:0,h:0,py:0,p:c[T]};a.e.style.width=200+$;a.e.style.left=Math.max((a.p.w-200)*0.5,0)+$;a.w=200;
a.e.style.height=32+$;a.e.style.top=60-a.p.py+$;a.h=32;a.p.py+=32}catch(r){}try{a=c[dc]={e:document.getElementById(yf),w:0,h:0,py:0,p:c[T]};a.e.style.width=Math.max((a.p.w-56)*0.7992,0)+$;a.e.style.left=56+$;a.w=Math.max((a.p.w-56)*0.7992,0);a.e.style.height=Math.max((a.p.h-147)*0.0607,0)+$;a.e.style.top=147-a.p.py+$;a.h=Math.max((a.p.h-147)*0.0607,0);a.p.py+=Math.max(0,(a.p.h-147)*0.0607)}catch(s){}try{a=c[ec]={e:document.getElementById(zf),w:0,h:0,py:0,p:c[T]};a.e.style.width=Math.max((a.p.w-56)*
0.7992,0)+$;a.e.style.left=56+$;a.w=Math.max((a.p.w-56)*0.7992,0);a.e.style.height=Math.max((a.p.h-178)*0.0674,0)+$;a.e.style.top=178-a.p.py+$;a.h=Math.max((a.p.h-178)*0.0674,0);a.p.py+=Math.max(0,(a.p.h-178)*0.0674)}catch(t){}try{a=c[fc]={e:document.getElementById(Af),w:0,h:0,py:0,p:c[T]};a.e.style.width=Math.max((a.p.w-56)*0.4735,0)+$;a.e.style.left=56+$;a.w=Math.max((a.p.w-56)*0.4735,0);a.e.style.height=Math.max((a.p.h-210)*0.076,0)+$;a.e.style.top=210-a.p.py+$;a.h=Math.max((a.p.h-210)*0.076,0);
a.p.py+=Math.max(0,(a.p.h-210)*0.076)}catch(da){}try{a=c[gc]={e:document.getElementById(Bf),w:0,h:0,py:0,p:c[T]};a.e.style.width=Math.max((a.p.w-56)*0.803,0)+$;a.e.style.left=56+$;a.w=Math.max((a.p.w-56)*0.803,0);a.e.style.height=Math.max((a.p.h-243)*0.0876,0)+$;a.e.style.top=243-a.p.py+$;a.h=Math.max((a.p.h-243)*0.0876,0);a.p.py+=Math.max(0,(a.p.h-243)*0.0876)}catch(pa){}try{a=c[hc]={e:document.getElementById(Cf),w:0,h:0,py:0,p:c[T]};a.e.style.width=Math.max((a.p.w-56)*0.8068,0)+$;a.e.style.left=
56+$;a.w=Math.max((a.p.w-56)*0.8068,0);a.e.style.height=Math.max((a.p.h-277)*0.1038,0)+$;a.e.style.top=277-a.p.py+$;a.h=Math.max((a.p.h-277)*0.1038,0);a.p.py+=Math.max(0,(a.p.h-277)*0.1038)}catch(Tf){}try{a=c[ic]={e:document.getElementById(Df),w:0,h:0,py:0,p:c[T]};a.e.style.width=Math.max((a.p.w-56)*0.8068,0)+$;a.e.style.left=56+$;a.w=Math.max((a.p.w-56)*0.8068,0);a.e.style.height=Math.max((a.p.h-316)*0.1319,0)+$;a.e.style.top=316-a.p.py+$;a.h=Math.max((a.p.h-316)*0.1319,0);a.p.py+=Math.max(0,(a.p.h-
316)*0.1319)}catch(Uf){}try{a=c[jc]={e:document.getElementById(Ef),w:0,h:0,py:0,p:c[T]};a.e.style.width=Math.max((a.p.w-56)*0.7841,0)+$;a.e.style.left=56+$;a.w=Math.max((a.p.w-56)*0.7841,0);a.e.style.height=Math.max((a.p.h-353)*0.1776,0)+$;a.e.style.top=353-a.p.py+$;a.h=Math.max((a.p.h-353)*0.1776,0);a.p.py+=Math.max(0,(a.p.h-353)*0.1776)}catch(Vf){}try{a=c[kc]={e:document.getElementById(of),w:0,h:0,py:0,p:c[T]};a.w=0;a.e.style.height=0+$;a.e.style.top=-3E3-a.p.py+$;a.h=0;a.p.py+=0}catch(Wf){}}},
"dove_siamo":{"id":"dove_siamo","anchor_id":"#m1-dove_siamo","resize":function(d,e){var a;var c={};var g;a=c[W]={w:d,h:e,py:0};try{a=c[rc]={w:0,h:0,py:0,p:c[W]};a.w=Math.max(a.p.w,0);a.h=43;a.p.py+=43}catch(h){}try{a=c[sc]={e:document.getElementById(ce),w:0,h:0,py:0,p:c[rc]};a.w=60;a.e.style.height=30+$;a.e.style.top=Math.max(a.p.h-36,0)-a.p.py+$;a.h=30;a.p.py+=30}catch(i){}try{a=c[tc]={e:document.getElementById(me),w:0,h:0,py:0,p:c[rc]};a.e.style.width=109+$;a.e.style.left=Math.max((a.p.w-109)*0.4976,
0)+$;a.w=109;a.e.style.height=25+$;a.e.style.top=Math.max(a.p.h-34,0)-a.p.py+$;a.h=25;a.p.py+=25}catch(j){}try{a=c[uc]={e:document.getElementById(he),w:0,h:0,py:0,p:c[rc]};a.w=32;a.e.style.height=Math.max(a.p.h-11,0)+$;a.e.style.lineHeight=Math.max(a.p.h-11,0)-2+$;a.e.style.top=6-a.p.py+$;a.h=Math.max(a.p.h-11,0);a.p.py+=Math.max(2,a.p.h-11)}catch(k){}try{a=c[X]={e:document.getElementById(oe),w:0,h:0,py:0,p:c[W]};a.w=Math.max(a.p.w,0);a.e.style.height=44+$;a.e.style.top=Math.max(a.p.h-44,0)-a.p.py+
$;a.h=44;a.p.py+=44}catch(l){}try{a=c[yc]={e:document.getElementById(de),w:0,h:0,py:0,p:c[X]};a.e.style.width=32+$;a.e.style.left=Math.max((a.p.w-32)*0.8958,0)+$;a.w=32;a.h=32;a.p.py+=32}catch(m){}try{a=c[Ac]={e:document.getElementById(ee),w:0,h:0,py:0,p:c[X]};a.e.style.width=32+$;a.e.style.left=Math.max((a.p.w-32)*0.6944,0)+$;a.w=32;a.h=32;a.p.py+=32}catch(n){}try{a=c[Bc]={e:document.getElementById(fe),w:0,h:0,py:0,p:c[X]};a.e.style.width=32+$;a.e.style.left=Math.max((a.p.w-32)*0.4931,0)+$;a.w=32;
a.h=32;a.p.py+=32}catch(o){}try{a=c[Cc]={e:document.getElementById(ge),w:0,h:0,py:0,p:c[X]};a.e.style.width=32+$;a.e.style.left=Math.max((a.p.w-32)*0.2917,0)+$;a.w=32;a.h=32;a.p.py+=32}catch(p){}try{a=c[Dc]={e:document.getElementById(ie),w:0,h:0,py:0,p:c[X]};a.e.style.width=32+$;a.e.style.left=Math.max((a.p.w-32)*0.0903,0)+$;a.w=32;a.h=32;a.p.py+=32}catch(q){}try{a=c[vc]={e:document.getElementById(je),w:0,h:0,py:0,p:c[W]};a.e.style.width=200+$;a.e.style.left=Math.max((a.p.w-200)*0.5,0)+$;a.w=200;
a.e.style.height=32+$;a.e.style.top=60-a.p.py+$;a.h=32;a.p.py+=32}catch(r){}try{a=c[wc]={e:document.getElementById(le),w:0,h:0,py:0,p:c[W]};a.w=287;a.e.style.height=226+$;a.e.style.top=117-a.p.py+$;a.h=226;a.p.py+=226}catch(s){}try{a=c[Ec]={e:document.getElementById(ke),w:0,h:0,py:0,p:c[wc]};a.conth=a.e.getAttribute(aa);a.w=Math.max(a.p.w-2,0);a.e.style.height=(a.conth||(-1<Math.max(a.p.h-2,0)?Math.max(a.p.h-2,0):Math.max(224,a.p.h-2)))+$;a.e.style.top=0-a.p.py+$;a.h=a.conth||(-1<Math.max(a.p.h-2,
0)?Math.max(a.p.h-2,0):Math.max(224,a.p.h-2));a.p.py+=Math.max(a.conth||(-1<Math.max(a.p.h-2,0)?Math.max(a.p.h-2,0):Math.max(224,a.p.h-2)),0)}catch(t){}try{a=c[xc]={e:document.getElementById(ne),w:0,h:0,py:0,p:c[W]};a.w=287;a.e.style.height=38+$;a.e.style.top=363-a.p.py+$;a.h=38;a.p.py+=38}catch(da){}}},"pizzeria":{"id":"pizzeria","anchor_id":"#m1-pizzeria","resize":function(d,e){var a;var c={};var g;a=c[Y]={w:d,h:e,py:0};try{a=c[Fc]={w:0,h:0,py:0,p:c[Y]};a.w=Math.max(a.p.w,0);a.h=43;a.p.py+=43}catch(h){}try{a=
c[Gc]={e:document.getElementById(Gf),w:0,h:0,py:0,p:c[Fc]};a.w=60;a.e.style.height=30+$;a.e.style.top=Math.max(a.p.h-36,0)-a.p.py+$;a.h=30;a.p.py+=30}catch(i){}try{a=c[Hc]={e:document.getElementById(Pf),w:0,h:0,py:0,p:c[Fc]};a.e.style.width=73+$;a.e.style.left=Math.max((a.p.w-73)*0.498,0)+$;a.w=73;a.e.style.height=25+$;a.e.style.top=Math.max(a.p.h-34,0)-a.p.py+$;a.h=25;a.p.py+=25}catch(j){}try{a=c[Ic]={e:document.getElementById(If),w:0,h:0,py:0,p:c[Fc]};a.w=32;a.e.style.height=Math.max(a.p.h-11,0)+
$;a.e.style.lineHeight=Math.max(a.p.h-11,0)-2+$;a.e.style.top=6-a.p.py+$;a.h=Math.max(a.p.h-11,0);a.p.py+=Math.max(2,a.p.h-11)}catch(k){}try{a=c[Kc]={e:document.getElementById(Hf),w:0,h:0,py:0,p:c[Y]};a.e.style.width=200+$;a.e.style.left=Math.max((a.p.w-200)*0.5,0)+$;a.w=200;a.h=32;a.p.py+=32}catch(l){}try{a=c[Z]={e:document.getElementById(Rf),w:0,h:0,py:0,p:c[Y]};a.w=Math.max(a.p.w,0);a.e.style.height=44+$;a.e.style.top=Math.max(a.p.h-44,0)-a.p.py+$;a.h=44;a.p.py+=44}catch(m){}try{a=c[Nc]={e:document.getElementById(Jf),
w:0,h:0,py:0,p:c[Z]};a.e.style.width=40+$;a.e.style.left=Math.max((a.p.w-40)*0.9036,0)+$;a.w=40;a.h=40;a.p.py+=40}catch(n){}try{a=c[Oc]={e:document.getElementById(Kf),w:0,h:0,py:0,p:c[Z]};a.e.style.width=32+$;a.e.style.left=Math.max((a.p.w-32)*0.6806,0)+$;a.w=32;a.h=32;a.p.py+=32}catch(o){}try{a=c[Pc]={e:document.getElementById(Lf),w:0,h:0,py:0,p:c[Z]};a.e.style.width=32+$;a.e.style.left=Math.max((a.p.w-32)*0.4826,0)+$;a.w=32;a.h=32;a.p.py+=32}catch(p){}try{a=c[Qc]={e:document.getElementById(Mf),
w:0,h:0,py:0,p:c[Z]};a.e.style.width=32+$;a.e.style.left=Math.max((a.p.w-32)*0.2847,0)+$;a.w=32;a.h=32;a.p.py+=32}catch(q){}try{a=c[Rc]={e:document.getElementById(Nf),w:0,h:0,py:0,p:c[Z]};a.e.style.width=32+$;a.e.style.left=Math.max((a.p.w-32)*0.0868,0)+$;a.w=32;a.h=32;a.p.py+=32}catch(r){}try{a=c[Lc]={e:document.getElementById(Qf),w:0,h:0,py:0,p:c[Y]};a.e.style.width=310+$;a.e.style.left=Math.max((a.p.w-310)*0.6,0)+$;a.w=310;a.e.style.height=152+$;a.e.style.top=220-a.p.py+$;a.h=152;a.p.py+=152}catch(s){}try{a=
c[Mc]={e:document.getElementById(Of),w:0,h:0,py:0,p:c[Y]};a.e.style.width=140+$;a.e.style.left=Math.max((a.p.w-140)*0.5,0)+$;a.w=140;a.e.style.height=140+$;a.e.style.top=88-a.p.py+$;a.h=140;a.p.py+=140}catch(t){}}},"bisteccheria":{"id":"bisteccheria","anchor_id":"#m1-bisteccheria","resize":function(d,e){var a;var c={};var g;a=c[u]={w:d,h:e,py:0};try{a=c[Sc]={w:0,h:0,py:0,p:c[u]};a.w=Math.max(a.p.w,0);a.h=43;a.p.py+=43}catch(h){}try{a=c[ca]={e:document.getElementById(Vc),w:0,h:0,py:0,p:c[Sc]};a.w=
60;a.e.style.height=30+$;a.e.style.top=Math.max(a.p.h-36,0)-a.p.py+$;a.h=30;a.p.py+=30}catch(i){}try{a=c[ea]={e:document.getElementById(dd),w:0,h:0,py:0,p:c[Sc]};a.e.style.width=116+$;a.e.style.left=Math.max((a.p.w-116)*0.5,0)+$;a.w=116;a.e.style.height=25+$;a.e.style.top=Math.max(a.p.h-34,0)-a.p.py+$;a.h=25;a.p.py+=25}catch(j){}try{a=c[fa]={e:document.getElementById(Wc),w:0,h:0,py:0,p:c[Sc]};a.w=Math.max(a.p.w-288,0);a.e.style.height=Math.max(a.p.h-11,0)+$;a.e.style.lineHeight=Math.max(a.p.h-11,
0)-2+$;a.e.style.top=6-a.p.py+$;a.h=Math.max(a.p.h-11,0);a.p.py+=Math.max(2,a.p.h-11)}catch(k){}try{a=c[v]={e:document.getElementById(fd),w:0,h:0,py:0,p:c[u]};a.w=Math.max(a.p.w,0);a.e.style.height=44+$;a.e.style.top=Math.max(a.p.h-44,0)-a.p.py+$;a.h=44;a.p.py+=44}catch(l){}try{a=c[ja]={e:document.getElementById(Xc),w:0,h:0,py:0,p:c[v]};a.e.style.width=40+$;a.e.style.left=Math.max((a.p.w-40)*0.9036,0)+$;a.w=40;a.h=40;a.p.py+=40}catch(m){}try{a=c[ka]={e:document.getElementById(Yc),w:0,h:0,py:0,p:c[v]};
a.e.style.width=32+$;a.e.style.left=Math.max((a.p.w-32)*0.6806,0)+$;a.w=32;a.h=32;a.p.py+=32}catch(n){}try{a=c[la]={e:document.getElementById(Zc),w:0,h:0,py:0,p:c[v]};a.e.style.width=32+$;a.e.style.left=Math.max((a.p.w-32)*0.4826,0)+$;a.w=32;a.h=32;a.p.py+=32}catch(o){}try{a=c[ma]={e:document.getElementById($c),w:0,h:0,py:0,p:c[v]};a.e.style.width=32+$;a.e.style.left=Math.max((a.p.w-32)*0.2847,0)+$;a.w=32;a.h=32;a.p.py+=32}catch(p){}try{a=c[na]={e:document.getElementById(ad),w:0,h:0,py:0,p:c[v]};
a.e.style.width=32+$;a.e.style.left=Math.max((a.p.w-32)*0.0868,0)+$;a.w=32;a.h=32;a.p.py+=32}catch(q){}try{a=c[ga]={e:document.getElementById(bd),w:0,h:0,py:0,p:c[u]};a.e.style.width=200+$;a.e.style.left=Math.max((a.p.w-200)*0.5,0)+$;a.w=200;a.e.style.height=32+$;a.e.style.top=60-a.p.py+$;a.h=32;a.p.py+=32}catch(r){}try{a=c[ha]={e:document.getElementById(ed),w:0,h:0,py:0,p:c[u]};a.e.style.width=300+$;a.e.style.left=Math.max((a.p.w-300)*0.5,0)+$;a.w=300;a.e.style.height=133+$;a.e.style.top=253-a.p.py+
$;a.h=133;a.p.py+=133}catch(s){}try{a=c[ia]={e:document.getElementById(cd),w:0,h:0,py:0,p:c[u]};a.e.style.width=150+$;a.e.style.left=Math.max((a.p.w-150)*0.5,0)+$;a.w=150;a.e.style.height=120+$;a.e.style.top=108-a.p.py+$;a.h=120;a.p.py+=120}catch(t){}}},"caf_s":{"id":"caf_s","anchor_id":"#m1-caf_s","resize":function(d,e){var a;var c={};var g;a=c[x]={w:d,h:e,py:0};try{a=c[w]={w:0,h:0,py:0,p:c[x]};a.w=Math.max(a.p.w,0);a.h=43;a.p.py+=43}catch(h){}try{a=c[oa]={e:document.getElementById(gd),w:0,h:0,py:0,
p:c[w]};a.w=60;a.e.style.height=30+$;a.e.style.top=Math.max(a.p.h-36,0)-a.p.py+$;a.h=30;a.p.py+=30}catch(i){}try{a=c[qa]={e:document.getElementById(pd),w:0,h:0,py:0,p:c[w]};a.e.style.width=42+$;a.e.style.left=Math.max((a.p.w-42)*0.5,0)+$;a.w=42;a.e.style.height=25+$;a.e.style.top=Math.max(a.p.h-34,0)-a.p.py+$;a.h=25;a.p.py+=25}catch(j){}try{a=c[ra]={e:document.getElementById(hd),w:0,h:0,py:0,p:c[w]};a.w=32;a.e.style.height=Math.max((a.p.h-5)*0.8421,0)+$;a.e.style.lineHeight=Math.max((a.p.h-5)*0.8421,
0)-2+$;a.e.style.top=Math.max((a.p.h-5)*0.1579,0)-a.p.py+$;a.h=Math.max((a.p.h-5)*0.8421,0);a.p.py+=Math.max(2,(a.p.h-5)*0.8421)}catch(k){}try{a=c[y]={e:document.getElementById(rd),w:0,h:0,py:0,p:c[x]};a.w=Math.max(a.p.w,0);a.e.style.height=44+$;a.e.style.top=Math.max(a.p.h-44,0)-a.p.py+$;a.h=44;a.p.py+=44}catch(l){}try{a=c[va]={e:document.getElementById(id),w:0,h:0,py:0,p:c[y]};a.e.style.width=40+$;a.e.style.left=Math.max((a.p.w-40)*0.9036,0)+$;a.w=40;a.h=40;a.p.py+=40}catch(m){}try{a=c[wa]={e:document.getElementById(jd),
w:0,h:0,py:0,p:c[y]};a.e.style.width=32+$;a.e.style.left=Math.max((a.p.w-32)*0.6806,0)+$;a.w=32;a.h=32;a.p.py+=32}catch(n){}try{a=c[xa]={e:document.getElementById(kd),w:0,h:0,py:0,p:c[y]};a.e.style.width=32+$;a.e.style.left=Math.max((a.p.w-32)*0.4826,0)+$;a.w=32;a.h=32;a.p.py+=32}catch(o){}try{a=c[ya]={e:document.getElementById(ld),w:0,h:0,py:0,p:c[y]};a.e.style.width=32+$;a.e.style.left=Math.max((a.p.w-32)*0.2847,0)+$;a.w=32;a.h=32;a.p.py+=32}catch(p){}try{a=c[za]={e:document.getElementById(md),
w:0,h:0,py:0,p:c[y]};a.e.style.width=32+$;a.e.style.left=Math.max((a.p.w-32)*0.0868,0)+$;a.w=32;a.h=32;a.p.py+=32}catch(q){}try{a=c[sa]={e:document.getElementById(nd),w:0,h:0,py:0,p:c[x]};a.e.style.width=200+$;a.e.style.left=Math.max((a.p.w-200)*0.5,0)+$;a.w=200;a.e.style.height=32+$;a.e.style.top=60-a.p.py+$;a.h=32;a.p.py+=32}catch(r){}try{a=c[ta]={e:document.getElementById(qd),w:0,h:0,py:0,p:c[x]};a.e.style.width=300+$;a.e.style.left=Math.max((a.p.w-300)*0.5,0)+$;a.w=300;a.e.style.height=114+$;
a.e.style.top=232-a.p.py+$;a.h=114;a.p.py+=114}catch(s){}try{a=c[ua]={e:document.getElementById(od),w:0,h:0,py:0,p:c[x]};a.e.style.width=140+$;a.e.style.left=Math.max((a.p.w-140)*0.5,0)+$;a.w=140;a.e.style.height=120+$;a.e.style.top=105-a.p.py+$;a.h=120;a.p.py+=120}catch(t){}}},"cocktails":{"id":"cocktails","anchor_id":"#m1-cocktails","resize":function(d,e){var a;var c={};var g;a=c[A]={w:d,h:e,py:0};try{a=c[z]={w:0,h:0,py:0,p:c[A]};a.w=Math.max(a.p.w,0);a.h=43;a.p.py+=43}catch(h){}try{a=c[Aa]={e:document.getElementById(sd),
w:0,h:0,py:0,p:c[z]};a.w=60;a.e.style.height=30+$;a.e.style.top=Math.max(a.p.h-36,0)-a.p.py+$;a.h=30;a.p.py+=30}catch(i){}try{a=c[Ca]={e:document.getElementById(Bd),w:0,h:0,py:0,p:c[z]};a.e.style.width=86+$;a.e.style.left=Math.max((a.p.w-86)*0.5,0)+$;a.w=86;a.e.style.height=25+$;a.e.style.top=Math.max(a.p.h-34,0)-a.p.py+$;a.h=25;a.p.py+=25}catch(j){}try{a=c[Da]={e:document.getElementById(xd),w:0,h:0,py:0,p:c[z]};a.w=32;a.e.style.height=Math.max(a.p.h-11,0)+$;a.e.style.lineHeight=Math.max(a.p.h-11,
0)-2+$;a.e.style.top=6-a.p.py+$;a.h=Math.max(a.p.h-11,0);a.p.py+=Math.max(2,a.p.h-11)}catch(k){}try{a=c[B]={e:document.getElementById(Dd),w:0,h:0,py:0,p:c[A]};a.w=Math.max(a.p.w,0);a.e.style.height=44+$;a.e.style.top=Math.max(a.p.h-44,0)-a.p.py+$;a.h=44;a.p.py+=44}catch(l){}try{a=c[Ha]={e:document.getElementById(td),w:0,h:0,py:0,p:c[B]};a.e.style.width=40+$;a.e.style.left=Math.max((a.p.w-40)*0.9036,0)+$;a.w=40;a.h=40;a.p.py+=40}catch(m){}try{a=c[Ia]={e:document.getElementById(ud),w:0,h:0,py:0,p:c[B]};
a.e.style.width=32+$;a.e.style.left=Math.max((a.p.w-32)*0.6806,0)+$;a.w=32;a.h=32;a.p.py+=32}catch(n){}try{a=c[Ja]={e:document.getElementById(vd),w:0,h:0,py:0,p:c[B]};a.e.style.width=32+$;a.e.style.left=Math.max((a.p.w-32)*0.4826,0)+$;a.w=32;a.h=32;a.p.py+=32}catch(o){}try{a=c[Ka]={e:document.getElementById(wd),w:0,h:0,py:0,p:c[B]};a.e.style.width=32+$;a.e.style.left=Math.max((a.p.w-32)*0.2847,0)+$;a.w=32;a.h=32;a.p.py+=32}catch(p){}try{a=c[La]={e:document.getElementById(yd),w:0,h:0,py:0,p:c[B]};
a.e.style.width=32+$;a.e.style.left=Math.max((a.p.w-32)*0.0868,0)+$;a.w=32;a.h=32;a.p.py+=32}catch(q){}try{a=c[Ea]={e:document.getElementById(zd),w:0,h:0,py:0,p:c[A]};a.e.style.width=200+$;a.e.style.left=Math.max((a.p.w-200)*0.5,0)+$;a.w=200;a.e.style.height=32+$;a.e.style.top=60-a.p.py+$;a.h=32;a.p.py+=32}catch(r){}try{a=c[Fa]={e:document.getElementById(Ad),w:0,h:0,py:0,p:c[A]};a.e.style.width=300+$;a.e.style.left=Math.max((a.p.w-300)*0.5,0)+$;a.w=300;a.e.style.height=150+$;a.e.style.top=104-a.p.py+
$;a.h=150;a.p.py+=150}catch(s){}try{a=c[Ga]={e:document.getElementById(Cd),w:0,h:0,py:0,p:c[A]};a.e.style.width=300+$;a.e.style.left=Math.max((a.p.w-300)*0.5,0)+$;a.w=300;a.e.style.height=57+$;a.e.style.top=284-a.p.py+$;a.h=57;a.p.py+=57}catch(t){}}},"dessert":{"id":"dessert","anchor_id":"#m1-dessert","resize":function(d,e){var a;var c={};var g;a=c[E]={w:d,h:e,py:0};try{a=c[D]={w:0,h:0,py:0,p:c[E]};a.w=Math.max(a.p.w,0);a.h=43;a.p.py+=43}catch(h){}try{a=c[Ma]={e:document.getElementById(Rd),w:0,h:0,
py:0,p:c[D]};a.w=60;a.e.style.height=30+$;a.e.style.top=Math.max(a.p.h-36,0)-a.p.py+$;a.h=30;a.p.py+=30}catch(i){}try{a=c[Na]={e:document.getElementById($d),w:0,h:0,py:0,p:c[D]};a.e.style.width=72+$;a.e.style.left=Math.max((a.p.w-72)*0.5,0)+$;a.w=72;a.e.style.height=25+$;a.e.style.top=Math.max(a.p.h-34,0)-a.p.py+$;a.h=25;a.p.py+=25}catch(j){}try{a=c[Oa]={e:document.getElementById(Sd),w:0,h:0,py:0,p:c[D]};a.w=32;a.e.style.height=Math.max(a.p.h-11,0)+$;a.e.style.lineHeight=Math.max(a.p.h-11,0)-2+$;
a.e.style.top=6-a.p.py+$;a.h=Math.max(a.p.h-11,0);a.p.py+=Math.max(2,a.p.h-11)}catch(k){}try{a=c[F]={e:document.getElementById(be),w:0,h:0,py:0,p:c[E]};a.w=Math.max(a.p.w,0);a.e.style.height=44+$;a.e.style.top=Math.max(a.p.h-44,0)-a.p.py+$;a.h=44;a.p.py+=44}catch(l){}try{a=c[Ta]={e:document.getElementById(Td),w:0,h:0,py:0,p:c[F]};a.e.style.width=40+$;a.e.style.left=Math.max((a.p.w-40)*0.9036,0)+$;a.w=40;a.h=40;a.p.py+=40}catch(m){}try{a=c[Ua]={e:document.getElementById(Ud),w:0,h:0,py:0,p:c[F]};a.e.style.width=
32+$;a.e.style.left=Math.max((a.p.w-32)*0.6806,0)+$;a.w=32;a.h=32;a.p.py+=32}catch(n){}try{a=c[Va]={e:document.getElementById(Vd),w:0,h:0,py:0,p:c[F]};a.e.style.width=32+$;a.e.style.left=Math.max((a.p.w-32)*0.4826,0)+$;a.w=32;a.h=32;a.p.py+=32}catch(o){}try{a=c[Wa]={e:document.getElementById(Wd),w:0,h:0,py:0,p:c[F]};a.e.style.width=32+$;a.e.style.left=Math.max((a.p.w-32)*0.2847,0)+$;a.w=32;a.h=32;a.p.py+=32}catch(p){}try{a=c[Xa]={e:document.getElementById(Xd),w:0,h:0,py:0,p:c[F]};a.e.style.width=
32+$;a.e.style.left=Math.max((a.p.w-32)*0.0868,0)+$;a.w=32;a.h=32;a.p.py+=32}catch(q){}try{a=c[Pa]={e:document.getElementById(Yd),w:0,h:0,py:0,p:c[E]};a.e.style.width=200+$;a.e.style.left=Math.max((a.p.w-200)*0.5,0)+$;a.w=200;a.e.style.height=32+$;a.e.style.top=60-a.p.py+$;a.h=32;a.p.py+=32}catch(r){}try{a=c[Qa]={e:document.getElementById(ae),w:0,h:0,py:0,p:c[E]};a.e.style.width=300+$;a.e.style.left=Math.max((a.p.w-300)*0.5,0)+$;a.w=300;a.e.style.height=133+$;a.e.style.top=250-a.p.py+$;a.h=133;a.p.py+=
133}catch(s){}try{a=c[Ra]={e:document.getElementById(Zd),w:0,h:0,py:0,p:c[E]};a.e.style.width=150+$;a.e.style.left=Math.max((a.p.w-150)*0.5,0)+$;a.w=150;a.e.style.height=130+$;a.e.style.top=106-a.p.py+$;a.h=130;a.p.py+=130}catch(t){}}},"il_locale":{"id":"il_locale","anchor_id":"#m1-il_locale","resize":function(d,e){var a;var c={};var g;a=c[H]={w:d,h:e,py:0};try{a=c[G]={w:0,h:0,py:0,p:c[H]};a.w=Math.max(a.p.w,0);a.h=43;a.p.py+=43}catch(h){}try{a=c[Ya]={e:document.getElementById(Ze),w:0,h:0,py:0,p:c[G]};
a.w=60;a.e.style.height=30+$;a.e.style.top=Math.max(a.p.h-36,0)-a.p.py+$;a.h=30;a.p.py+=30}catch(i){}try{a=c[Za]={e:document.getElementById(lf),w:0,h:0,py:0,p:c[G]};a.e.style.width=77+$;a.e.style.left=Math.max((a.p.w-77)*0.4979,0)+$;a.w=77;a.e.style.height=25+$;a.e.style.top=Math.max(a.p.h-34,0)-a.p.py+$;a.h=25;a.p.py+=25}catch(j){}try{a=c[$a]={e:document.getElementById(ff),w:0,h:0,py:0,p:c[G]};a.w=32;a.e.style.height=Math.max(a.p.h-11,0)+$;a.e.style.lineHeight=Math.max(a.p.h-11,0)-2+$;a.e.style.top=
6-a.p.py+$;a.h=Math.max(a.p.h-11,0);a.p.py+=Math.max(2,a.p.h-11)}catch(k){}try{a=c[I]={e:document.getElementById(mf),w:0,h:0,py:0,p:c[H]};a.w=Math.max(a.p.w,0);a.e.style.height=44+$;a.e.style.top=Math.max(a.p.h-44,0)-a.p.py+$;a.h=44;a.p.py+=44}catch(l){}try{a=c[gb]={e:document.getElementById($e),w:0,h:0,py:0,p:c[I]};a.e.style.width=40+$;a.e.style.left=Math.max((a.p.w-40)*0.9036,0)+$;a.w=40;a.h=40;a.p.py+=40}catch(m){}try{a=c[hb]={e:document.getElementById(cf),w:0,h:0,py:0,p:c[I]};a.e.style.width=
32+$;a.e.style.left=Math.max((a.p.w-32)*0.6806,0)+$;a.w=32;a.h=32;a.p.py+=32}catch(n){}try{a=c[ib]={e:document.getElementById(df),w:0,h:0,py:0,p:c[I]};a.e.style.width=32+$;a.e.style.left=Math.max((a.p.w-32)*0.4826,0)+$;a.w=32;a.h=32;a.p.py+=32}catch(o){}try{a=c[jb]={e:document.getElementById(ef),w:0,h:0,py:0,p:c[I]};a.e.style.width=32+$;a.e.style.left=Math.max((a.p.w-32)*0.2847,0)+$;a.w=32;a.h=32;a.p.py+=32}catch(p){}try{a=c[lb]={e:document.getElementById(gf),w:0,h:0,py:0,p:c[I]};a.e.style.width=
32+$;a.e.style.left=Math.max((a.p.w-32)*0.0868,0)+$;a.w=32;a.h=32;a.p.py+=32}catch(q){}try{a=c[bb]={e:document.getElementById(hf),w:0,h:0,py:0,p:c[H]};a.e.style.width=200+$;a.e.style.left=Math.max((a.p.w-200)*0.5,0)+$;a.w=200;a.e.style.height=32+$;a.e.style.top=60-a.p.py+$;a.h=32;a.p.py+=32}catch(r){}try{a=c[cb]={e:document.getElementById(jf),w:0,h:0,py:0,p:c[H]};a.e.style.width=105+$;a.e.style.left=Math.max((a.p.w-105)*0.1721,0)+$;a.w=105;a.e.style.height=141+$;a.e.style.top=99-a.p.py+$;a.h=141;
a.p.py+=141}catch(s){}try{a=c[db]={e:document.getElementById(kf),w:0,h:0,py:0,p:c[H]};a.w=101;a.e.style.height=141+$;a.e.style.top=99-a.p.py+$;a.h=141;a.p.py+=141}catch(t){}try{a=c[eb]={e:document.getElementById(af),w:0,h:0,py:0,p:c[H]};a.w=104;a.e.style.height=139+$;a.e.style.top=254-a.p.py+$;a.h=139;a.p.py+=139}catch(da){}try{a=c[fb]={e:document.getElementById(bf),w:0,h:0,py:0,p:c[H]};a.w=101;a.e.style.height=139+$;a.e.style.top=254-a.p.py+$;a.h=139;a.p.py+=139}catch(pa){}}},"credits":{"id":"credits",
"anchor_id":"#m1-credits","resize":function(d,e){var a;var c={};var g;a=c[K]={w:d,h:e,py:0};try{a=c[J]={w:0,h:0,py:0,p:c[K]};a.w=Math.max(a.p.w,0);a.h=43;a.p.py+=43}catch(h){}try{a=c[mb]={e:document.getElementById(Ed),w:0,h:0,py:0,p:c[J]};a.w=60;a.e.style.height=30+$;a.e.style.top=Math.max(a.p.h-36,0)-a.p.py+$;a.h=30;a.p.py+=30}catch(i){}try{a=c[nb]={e:document.getElementById(Nd),w:0,h:0,py:0,p:c[J]};a.e.style.width=110+$;a.e.style.left=Math.max((a.p.w-110)*0.5,0)+$;a.w=110;a.e.style.height=25+$;
a.e.style.top=Math.max(a.p.h-34,0)-a.p.py+$;a.h=25;a.p.py+=25}catch(j){}try{a=c[ob]={e:document.getElementById(Fd),w:0,h:0,py:0,p:c[J]};a.e.style.width=Math.max((a.p.w-5)*0.1016,0)+$;a.e.style.left=Math.max((a.p.w-5)*0.8984,0)+$;a.w=Math.max((a.p.w-5)*0.1016,0);a.e.style.height=Math.max(a.p.h-11,0)+$;a.e.style.lineHeight=Math.max(a.p.h-11,0)-2+$;a.e.style.top=6-a.p.py+$;a.h=Math.max(a.p.h-11,0);a.p.py+=Math.max(2,a.p.h-11)}catch(k){}try{a=c[L]={e:document.getElementById(Qd),w:0,h:0,py:0,p:c[K]};a.w=
Math.max(a.p.w,0);a.e.style.height=44+$;a.e.style.top=Math.max(a.p.h-44,0)-a.p.py+$;a.h=44;a.p.py+=44}catch(l){}try{a=c[ub]={e:document.getElementById(Gd),w:0,h:0,py:0,p:c[L]};a.e.style.width=40+$;a.e.style.left=Math.max((a.p.w-40)*0.9036,0)+$;a.w=40;a.h=40;a.p.py+=40}catch(m){}try{a=c[vb]={e:document.getElementById(Hd),w:0,h:0,py:0,p:c[L]};a.e.style.width=32+$;a.e.style.left=Math.max((a.p.w-32)*0.6806,0)+$;a.w=32;a.h=32;a.p.py+=32}catch(n){}try{a=c[wb]={e:document.getElementById(Id),w:0,h:0,py:0,
p:c[L]};a.e.style.width=32+$;a.e.style.left=Math.max((a.p.w-32)*0.4826,0)+$;a.w=32;a.h=32;a.p.py+=32}catch(o){}try{a=c[xb]={e:document.getElementById(Jd),w:0,h:0,py:0,p:c[L]};a.e.style.width=32+$;a.e.style.left=Math.max((a.p.w-32)*0.2847,0)+$;a.w=32;a.h=32;a.p.py+=32}catch(p){}try{a=c[yb]={e:document.getElementById(Kd),w:0,h:0,py:0,p:c[L]};a.e.style.width=32+$;a.e.style.left=Math.max((a.p.w-32)*0.0868,0)+$;a.w=32;a.h=32;a.p.py+=32}catch(q){}try{a=c[pb]={e:document.getElementById(Ld),w:0,h:0,py:0,
p:c[K]};a.e.style.width=200+$;a.e.style.left=Math.max((a.p.w-200)*0.5,0)+$;a.w=200;a.e.style.height=32+$;a.e.style.top=50-a.p.py+$;a.h=32;a.p.py+=32}catch(r){}try{a=c[qb]={e:document.getElementById(Od),w:0,h:0,py:0,p:c[K]};a.w=241;a.e.style.height=Math.max((a.p.h-122)*0.0562,0)+$;a.e.style.top=122-a.p.py+$;a.h=Math.max((a.p.h-122)*0.0562,0);a.p.py+=Math.max(0,(a.p.h-122)*0.0562)}catch(s){}try{a=c[rb]={e:document.getElementById(Md),w:0,h:0,py:0,p:c[K]};a.w=288;a.e.style.height=149+$;a.e.style.top=
156-a.p.py+$;a.h=149;a.p.py+=149}catch(t){}try{a=c[tb]={e:document.getElementById(Pd),w:0,h:0,py:0,p:c[K]};a.e.style.width=Math.max((a.p.w-136)*0.2609,0)+$;a.e.style.left=136+$;a.w=Math.max((a.p.w-136)*0.2609,0);a.e.style.height=Math.max((a.p.h-350)*0.1727,0)+$;a.e.style.top=350-a.p.py+$;a.h=Math.max((a.p.h-350)*0.1727,0);a.p.py+=Math.max(0,(a.p.h-350)*0.1727)}catch(da){}}}};m1Design["css"]=Sf;m1Design["pages"]=Xf;m1Design["_resizing"]={};m1Design["softSpinnerEnabled"]=true;
m1Design["shouldHideAddressBar"]=true;m1Design["root"]=function(){return Tc};})(); return m1Design; }();m1Design['actions']={'action124':function() { phoneui.back();
; },'action125':function() { phoneui.callPhone('');
; },'action75':function() { phoneui.callPhone('0708940394 ');
; },'action63':function() { phoneui.callPhone('0708940394');
; },'action114':function() { phoneui.gotoPage('m1-bisteccheria', 'SLIDE_LEFT');
; },'action115':function() { phoneui.gotoPage('m1-caf_s', 'SLIDE_LEFT');
; },'action116':function() { phoneui.gotoPage('m1-cocktails', 'SLIDE_LEFT');
; },'action111':function() { phoneui.gotoPage('m1-credits', 'SLIDE_RIGHT');
; },'action117':function() { phoneui.gotoPage('m1-dessert', 'SLIDE_LEFT');
; },'action128':function() { phoneui.gotoPage('m1-dove_siamo', 'SLIDE_UP');
; },'action67':function() { phoneui.gotoPage('m1-home', 'DEFAULT');
; },'action130':function() { phoneui.gotoPage('m1-home', 'SLIDE_UP');
; },'action118':function() { phoneui.gotoPage('m1-il_locale', 'SLIDE_LEFT');
; },'action129':function() { phoneui.gotoPage('m1-orari', 'SLIDE_UP');
; },'action113':function() { phoneui.gotoPage('m1-pizzeria', 'SLIDE_LEFT');
; },'action127':function() { phoneui.showURL('http://it-it.facebook.com/HollywoodCafe12/posts/368644183158465', '_child', {showLocationBar: true, showAddress: true, showNavigationBar: true, });
; },'action110':function() { phoneui.showURL('http://www.agenziawebapp.it/mobile/home.html', '_blank', {});
; },'action64':function() { phoneui.showURL('http://www.pizzeria-hollywood.it/emailform-www/emailform.html', '_child', {showLocationBar: true, showAddress: true, showNavigationBar: true, });
; },'action126':function() { phoneui.showURL('http://www.pizzeria-hollywood.it/jq/jq/index.html', '_child', {showLocationBar: true, showAddress: true, showNavigationBar: true, });
; }};m1Design['actions']['action71']=m1Design['actions']['action83']=m1Design['actions']['action89']=m1Design['actions']['action107']=m1Design['actions']['action77']=m1Design['actions']['action95']=m1Design['actions']['action101']=m1Design['actions']['action65']=m1Design['actions']['action120']=m1Design['actions']['action127'];m1Design['actions']['action72']=m1Design['actions']['action84']=m1Design['actions']['action78']=m1Design['actions']['action96']=m1Design['actions']['action108']=m1Design['actions']['action66']=m1Design['actions']['action90']=m1Design['actions']['action102']=m1Design['actions']['action121']=m1Design['actions']['action128'];m1Design['actions']['action138']=m1Design['actions']['action131']=m1Design['actions']['action133']=m1Design['actions']['action132']=m1Design['actions']['action122']=m1Design['actions']['action135']=m1Design['actions']['action134']=m1Design['actions']['action137']=m1Design['actions']['action136']=m1Design['actions']['action129'];m1Design['actions']['action112']=m1Design['actions']['action75'];m1Design['actions']['action85']=m1Design['actions']['action109']=m1Design['actions']['action97']=m1Design['actions']['action73']=m1Design['actions']['action79']=m1Design['actions']['action91']=m1Design['actions']['action103']=m1Design['actions']['action123']=m1Design['actions']['action130'];m1Design['actions']['action105']=m1Design['actions']['action69']=m1Design['actions']['action125'];m1Design['actions']['action82']=m1Design['actions']['action76']=m1Design['actions']['action94']=m1Design['actions']['action119']=m1Design['actions']['action88']=m1Design['actions']['action106']=m1Design['actions']['action70']=m1Design['actions']['action100']=m1Design['actions']['action64'];m1Design['actions']['action98']=m1Design['actions']['action74']=m1Design['actions']['action68']=m1Design['actions']['action86']=m1Design['actions']['action104']=m1Design['actions']['action92']=m1Design['actions']['action80']=m1Design['actions']['action62']=m1Design['actions']['action124'];m1Design['actions']['action99']=m1Design['actions']['action81']=m1Design['actions']['action93']=m1Design['actions']['action87']=m1Design['actions']['action63']

